### ISSUE TITLE
django: sending an event from settings module swallows exceptions

### ISSUE THREAD

**Issue by blueyed** [getsentry/sentry-python#1148]
I've noticed that using the recommended way of setting up Sentry in Django's settings.py causes exceptions to be swallowed, if you also trigger sending an event from there directly.

Given the following in `settings.py`, before `INSTALLED_APPS`:

```python
SENTRY_DSN = os.environ.get("SENTRY_DSN", None)
if SENTRY_DSN:
    environment = os.environ.get("ENVIRONMENT", None)  # required for release tracking
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[],  # [DjangoIntegration()],
        release=None,
        attach_stacktrace=True,  # also with logging messages.
        environment="debug",
        traces_sample_rate=1.0,
    )
    event_id = sentry_sdk.capture_message("Initialized Sentry", extras={
        "env": os.environ,
    })
    import doesnotexist
```

If there then is an error later in `settings.py`, e.g. an ImportError like above, it gets swallowed, which results in the following:

```
% SENTRY_DSN=https://XXX@o158426.ingest.sentry.io/YYY python manage.py shell_plus
Unknown command: 'shell_plus'. Did you mean shell?
Type 'manage.py help' for usage.
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

Whereas when putting the failing import before sending of the event it will result in the expected (far more helpful) output:
```
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 237, in fetch_command
    app_name = commands[subcommand]
KeyError: 'shell_plus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 22, in <module>
    main()
  File "/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 420, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 414, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 244, in fetch_command
    settings.INSTALLED_APPS
  File "/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/csd/settings/__init__.py", line 63, in <module>
    import doesnotexit
ModuleNotFoundError: No module named 'doesnotexit'
```

The problem appears to be that sending of the event triggers settings to be touched
It looks like (queuing of) sending an event triggers Django's `django.conf.settings.configured` to become True, via:

```
[14]   /app/csd/settings/__init__.py(64)<module>()
-> event_id = sentry_sdk.capture_message("Initialized Sentry", extras={
[15]   /venv/lib/python3.9/site-packages/sentry_sdk/api.py(87)capture_message()
-> return Hub.current.capture_message(message, level, scope=scope, **scope_args)
[16]   /venv/lib/python3.9/site-packages/sentry_sdk/hub.py(344)capture_message()
-> return self.capture_event(
[17]   /venv/lib/python3.9/site-packages/sentry_sdk/hub.py(321)capture_event()
-> rv = client.capture_event(event, hint, scope)
[18]   /venv/lib/python3.9/site-packages/sentry_sdk/client.py(322)capture_event()
-> event_opt = self._prepare_event(event, hint, scope)
[19]   /venv/lib/python3.9/site-packages/sentry_sdk/client.py(190)_prepare_event()
-> event = serialize(
[20]   /venv/lib/python3.9/site-packages/sentry_sdk/serializer.py(429)serialize()
-> rv = _serialize_node(event, **kwargs)
[21]   /venv/lib/python3.9/site-packages/sentry_sdk/serializer.py(222)_serialize_node()
-> return _serialize_node_impl(
[22]   /venv/lib/python3.9/site-packages/sentry_sdk/serializer.py(307)_serialize_node_impl()
-> v = _serialize_node(
[23] > /venv/lib/python3.9/site-packages/sentry_sdk/serializer.py(214)_serialize_node()
-> if segment is not None:
```

Relevant code in Django,  where this is happening, and it then either has settings configured there then (when an event is sent through Sentry), or not (when no event is being sent already): https://github.com/django/django/blob/843c34b3ab921c1acf77ee2014a97bc7975595b8/django/core/management/__init__.py#L362-L369

I can investigate further, but wanted to leave this here already for now.
Also, I think that the recommended way / suitable workaround probably is to not send an event from there already, but only when apps are ready anyway.

Note that when not emitting a manual event before the error (in `settings.py`) it will not get swallowed, but also not reported to Sentry. 

```
% pip list
Package           Version
----------------- ---------
asgiref           3.3.4
certifi           2021.5.30
Django            3.2.4
django-extensions 3.1.3
pip               21.1.1
psycopg2-binary   2.9.1
pytz              2021.1
sentry-sdk        1.1.0
setuptools        56.0.0
sqlparse          0.4.1
urllib3           1.26.5
whitenoise        5.2.0
```
It also happens with the current sentry-sdk==1.3.0.

**Comment by HazAT** [comment]
Hey, @blueyed thanks for opening an issue.
We will try to investigate how to fix this but if you want to have this sooner we would really love it if you open a PR for this

**Comment by antonpirker** [comment]
I have now tried this with Django 3.1.14 and Sentry SDK 1.5.4:

I added this to `settings.py`:
```python

sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN", None),
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=1.0,
    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True,
)
event_id = sentry_sdk.capture_message("Initialized Sentry")
import doesnotexist

```

And when running Django with `manage.py runserver` the error is not swallowed but printed to the terminal:

```bash 
antonpirker@Antons-MacBook-Pro$ ./manage.py runserver 0.0.0.0:8000
Traceback (most recent call last):
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/antonpirker/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/demosite/settings.py", line 191, in <module>
    import doesnotexist
ModuleNotFoundError: No module named 'doesnotexist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/./manage.py", line 22, in <module>
    main()
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 343, in run_from_argv
    connections.close_all()
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/db/utils.py", line 232, in close_all
    for alias in self:
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/db/utils.py", line 226, in __iter__
    return iter(self.databases)
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/antonpirker/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/antonpirker/code/sample-projects-for-sentry/django3-project/demosite/demosite/settings.py", line 191, in <module>
    import doesnotexist
ModuleNotFoundError: No module named 'doesnotexist'
```

So could you @blueyed check if this is still swallowed when you update your sentry SDK?
