### ISSUE TITLE
aiohttp integration failing with aiohttp 3.7.4.post0 (current version)

### ISSUE THREAD

**Issue by NathanEscandor** [getsentry/sentry-python#1160]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
e.g: Python SDK 1.3.0 (have also tried with 1.3.1, but that didn't solve the issue)

### Steps to Reproduce

```
from sentry_sdk import init
from sentry_sdk.integrations.aiohttp import AioHttpIntegration
init(dsn=SENTRY_DSN, environment=SENTRY_ENVIRONMENT, integrations=[AioHttpIntegration()])
```

### Expected Result
Application starts up without error

### Actual Result
It seems like the AioHttpIntegration() function doesn't like that the current version of aiohttp (3.7.4.post0) has 'post0' appended to the end.

`ValueError: invalid literal for int() with base 10: 'post0'`
`raise DidNotEnable("AIOHTTP version unparseable: {}".format(version))`

full trace:
```
Sentry environment: production
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 53, in setup_once
    version = tuple(map(int, AIOHTTP_VERSION.split(".")))
ValueError: invalid literal for int() with base 10: 'post0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 56, in serve
    config.load()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/./app/main.py", line 55, in <module>
    init(dsn=SENTRY_DSN, environment=SENTRY_ENVIRONMENT, integrations=[AioHttpIntegration()])
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/hub.py", line 106, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/client.py", line 84, in __init__
    self._init_impl()
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/client.py", line 121, in _init_impl
    self.integrations = setup_integrations(
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/__init__.py", line 120, in setup_integrations
    type(integration).setup_once()
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 55, in setup_once
    raise DidNotEnable("AIOHTTP version unparseable: {}".format(version))
UnboundLocalError: local variable 'version' referenced before assignment
sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8080)>
```

**Comment by AbhiPrasad** [comment]
Thanks for reporting! Your right that our parsing logic expects each identifier on the version (major, minor, patch, etc.) to be an integer. Downgrading to `3.7.4` should work for now.

Contributions are welcome for fixes!

**Comment by NathanEscandor** [comment]
Thanks for the quick reply! 

Just realized that my docker image was out of date and was actually using python sdk 0.14.3

Updating to the most recent python sdk seems to have fixed it. Cheers!

**Comment by AbhiPrasad** [comment]
Ah yes, didn't catch that. Thanks for double checking by bumping the sdk!
