### ISSUE TITLE
Poor error when calling sentry_sdk.init with too much *args

### ISSUE THREAD

**Issue by touilleMan** [getsentry/sentry-python#1178]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry_sdk for python version *1.3.1*

### Steps to Reproduce

```python
>>> import sentry_sdk
>>> sentry_sdk.VERSION
'1.3.1'
>>> sentry_sdk.init(None, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/emmanuel/projects/parsec-cloud/venv/lib/python3.8/site-packages/sentry_sdk/hub.py", line 105, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "/home/emmanuel/projects/parsec-cloud/venv/lib/python3.8/site-packages/sentry_sdk/client.py", line 84, in __init__
    self.options = get_options(*args, **kwargs)  # type: Dict[str, Any]
  File "/home/emmanuel/projects/parsec-cloud/venv/lib/python3.8/site-packages/sentry_sdk/client.py", line 51, in _get_options
    options = dict(*args, **kwargs)
TypeError: 'int' object is not iterable
>>> sentry_sdk.init(None, 1, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/emmanuel/projects/parsec-cloud/venv/lib/python3.8/site-packages/sentry_sdk/hub.py", line 105, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "/home/emmanuel/projects/parsec-cloud/venv/lib/python3.8/site-packages/sentry_sdk/client.py", line 84, in __init__
    self.options = get_options(*args, **kwargs)  # type: Dict[str, Any]
  File "/home/emmanuel/projects/parsec-cloud/venv/lib/python3.8/site-packages/sentry_sdk/client.py", line 51, in _get_options
    options = dict(*args, **kwargs)
TypeError: dict expected at most 1 argument, got 2
```

### Expected Result

`Client.__init__` should raise an explicit `TypeError` exception about the fact it only accept one non-kwargs argument.

### Actual Result

Currently the client crash due to an improper usage of `dict`:
https://github.com/getsentry/sentry-python/blob/832263bedca595be1e31a519d4f49f477bd77760/sentry_sdk/client.py#L51

**Comment by antonpirker** [comment]
Hey @touilleMan 
Thanks for writing in. Yes, here the error message could be way better, I agree. 
We will put in on our internal Backelog. (But our backlog right now is quite big, so please don't hold your breath on it! :-))

**Comment by targhs** [comment]
Added a PR https://github.com/getsentry/sentry-python/pull/1361
