### ISSUE TITLE
Sentry gets JSON serialization exception when trying to send trace results

### ISSUE THREAD

**Issue by ripperdoc** [getsentry/sentry-python#1222]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Python 1.4.3

### Steps to Reproduce

In my auth module, I call this function from sentry_sdk:
```
        with configure_scope() as scope:
            scope.user = {"email": g.user.email, "id": g.user.id}
```

The `g.user.id` is actually a pymongo ObjectId. That has never caused issues before with Sentry, as it's been stringified somewhere in Sentry. But when I updated to 1.4.3 this seems to create an error in my logs, that appears randomly for different requests, which I think are those requests selected for sampling. It fails to encode the tracing data to JSON as ObjectId is not JSON serializable on its own.

Example trace:
```
[2021-10-19 18:00:33 +0000] [461] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 320, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/flask.py", line 90, in sentry_patched_wsgi_app
    return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/wsgi.py", line 140, in __call__
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/tracing.py", line 163, in __exit__
    self.finish(hub)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/tracing.py", line 595, in finish
    "contexts": {"trace": self.get_trace_context()},
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/tracing.py", line 468, in get_trace_context
    sentry_tracestate = self.get_or_set_sentry_tracestate()
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/tracing.py", line 351, in get_or_set_sentry_tracestate
    transaction._sentry_tracestate = compute_tracestate_entry(self)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/tracing_utils.py", line 340, in compute_tracestate_entry
    return "sentry=" + compute_tracestate_value(data)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/tracing_utils.py", line 291, in compute_tracestate_value
    tracestate_json = json.dumps(data)
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
```

I do get these errors reported to Sentry themselves, which is great. The errors are a bit cryptic there, as the request is never captured, but I could see there that the `obj` that is being encoded on `File "/usr/local/lib/python3.9/json/__init__.py", line 231` is the transaction data:

```
{
environment: 'production', 
public_key: '18af24f075334fb786cb19d44649dd59', 
release: '2021-10-17-4658198', 
trace_id: '7e23f1d02215472588d4425b7f060b89', 
transaction: '/', 
user: {
id: ObjectId('5df955e1598132f42c56e9ba')
}
}
```

### Expected Result

I expected it to be stringified and that the JSON dumping wont fail.

Does this make sense?

**Comment by benzkji** [comment]
pinning the sdk to `sentry-sdk<1.4` has normal/expected behaviour. same for you?

**Comment by ibushong** [comment]
I was also getting this error (confirmed it only happens in 1.4.0+). I traced it down to my `release` argument to `sentry_sdk.init()` getting passed as bytes. After adding `.decode()` to convert it to str, it works properly. But interesting that it worked fine before v1.4.0.

**Comment by Carnageous** [comment]
Can confirm, that this is an issue in `<=1.4.0`, also in latest latest (`1.5.7`). For us the issue is not in the sentry_sdk.init() params like release, but seems to come from one of the integrations we use (Falcon or SQLAlchemy). Maybe because they set a `trace_id` as UUID that is not converted? (see `self.trace_id = trace_id or uuid.uuid4().hex` in tracing.py#L351)
