### ISSUE TITLE
python 3.9/flask 1.1.2 doesn't work with sentry-sdk[flask]

### ISSUE THREAD

**Issue by nirradi** [getsentry/sentry-python#1348]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.0

### Steps to Reproduce

```
docker run -it python:3.9-buster bash

pip install flask==1.1.2 sentry-sdk[flask]==1.5.0

python -c "from sentry_sdk.integrations.flask import FlaskIntegration"
```

### Expected Result

it works

### Actual Result

error is 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/flask.py", line 29, in <module>
    from flask import (  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.9/site-packages/itsdangerous/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/flask.py", line 41, in <module>
    raise DidNotEnable("Flask is not installed")
sentry_sdk.integrations.DidNotEnable: Flask is not installed
```

work around, explicitly install itsdangerous==2.0.1 or up grade to flask 2.0.x

**Comment by antonpirker** [comment]
Hey @nirradi 
Thanks for writing in!
This is because a new version of a requirement of Flask was released and Flask did not pin the version of the requirement so it is breaking.

Have a look here to see how you can fix this:
https://github.com/pallets/flask/issues/4455

**Comment by antonpirker** [comment]
So the solution is to pin these two packages, if you pin `flask` to a version a version lower than 2.0:
```
itsdangerous>=0.24,<2.0
markupsafe<2.0.0
```
