### ISSUE TITLE
Exception `Flask is not installed`

### ISSUE THREAD

**Issue by yellowmamba** [getsentry/sentry-python#1351]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.6

### Steps to Reproduce

1. installed `flask 1.1.2` and `sentry-sdk 1.5.6` in python3.7 runtime
2. Run code
```
from sentry_sdk.integrations.flask import FlaskIntegration
```

### Expected Result

No errors

### Actual Result

```
File "/<my_path>/sentry_sdk/integrations/flask.py", line 41, in <module>
    raise DidNotEnable("Flask is not installed")
```
exception thrown here 
```
try:
    from flask import (  # type: ignore
        Markup,
        Request,
        Flask,
        _request_ctx_stack,
        _app_ctx_stack,
        __version__ as FLASK_VERSION,
    )
    from flask.signals import (
        before_render_template,
        got_request_exception,
        request_started,
    )
except ImportError:
    raise DidNotEnable("Flask is not installed")
```
 
However, if I jump into my python environment, trying to manually replicate the problem, all imports seem fine

```
Python 3.7.9 (default, Jan 12 2021, 16:13:14)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask import Markup
>>> from flask import Request
>>> from flask import Flask
>>> from flask import _request_ctx_stack
>>> from flask import _app_ctx_stack
>>> from flask import __version__ as FLASK_VERSION
>>> print(FLASK_VERSION)
1.1.2
>>> from flask.signals import before_render_template
>>> from flask.signals import got_request_exception
>>> from flask.signals import request_started
>>>
```

**Comment by bityob** [comment]
Seems like it's related to this issue 

https://github.com/pallets/itsdangerous/issues/289

This is the full stack trace

**ImportError: cannot import name 'json' from 'itsdangerous'**
```
>>> from sentry_sdk.integrations.flask import FlaskIntegration
Traceback (most recent call last):
  File "C:\sentry-sdk-issue-1351\venv\lib\site-packages\sentry_sdk\integrations\flask.py", line 29, in <module>
    from flask import (  # type: ignore
  File "C:\sentry-sdk-issue-1351\venv\lib\site-packages\flask\__init__.py", line 19, in <module>
    from . import json
  File "C:\sentry-sdk-issue-1351\venv\lib\site-packages\flask\json\__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (C:\sentry-sdk-issue-1351\venv\lib\site-packages\itsdangerous\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\sentry-sdk-issue-1351\venv\lib\site-packages\sentry_sdk\integrations\flask.py", line 43, in <module>
    raise DidNotEnable("Flask is not installed")
sentry_sdk.integrations.DidNotEnable: Flask is not installed
```

**Comment by antonpirker** [comment]
Hey @bityob !
Thanks for reporting this. The problem is with Flask not pinning a requirement, and so a wrong version of a package is installed. 

Please have a look here for a solution: https://github.com/getsentry/sentry-python/issues/1348
