### ISSUE TITLE
Sentry can't catch exception inside celery/kombu/redis code

### ISSUE THREAD

**Issue by Alexander3** [getsentry/sentry-python#1353]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.4

### Steps to Reproduce

Sentry works perfectly for errors inside task body, but here something went wrong after task finished, and I don't see this exception in Sentry.

I'm sorry, but I don't know how to reproduce it. I'm still not sure what is causing this exception, but it may be related to sending big arguments, to celery task. 

This is how I initialize sentry in settings.py:
```
sentry_sdk.init(
    dsn=env.str("DJANGO_SENTRY_DSN", ""),
    environment=env.str("DJANGO_ENVIRONMENT", ""),
    integrations=[
        DjangoIntegration(),
        CeleryIntegration(),
        RedisIntegration(),
        # AioHttpIntegration(), TODO: uncomment after removing gevent
        LoggingIntegration(
            level=logging.INFO,  # Capture info and above as breadcrumbs
            event_level=logging.ERROR,  # Send error and above as event
        ),
    ],
    send_default_pii=True,
)
```

### Expected Result

Sentry should catch this exception

### Actual Result

```
celery_1          | [2022-02-24 04:15:00,697: INFO/ForkPoolWorker-7] Sync completed in 512.57s # This is end of first task
celery_1          | [2022-02-24 04:15:02,279: INFO/MainProcess] Received task: apps.metrics.tasks.execute_sql[0c0a3f89-3476-439e-beee-8a0866fa54f9]
celery_1          | [2022-02-24 04:15:05,238: INFO/MainProcess] Received task: apps.metrics.tasks.execute_sql[b124688a-1423-48e5-9992-706b2ebaed79]
celery_1          | [2022-02-24 04:15:06,488: INFO/MainProcess] Received task: apps.metrics.tasks.execute_sql[e8a62df8-6bba-467a-9786-52e54b015763]  #Looks like first task finished, and next tasks in chain are executed
celery_1          | [2022-02-24 04:16:19,941: WARNING/ForkPoolWorker-7] /usr/local/lib/python3.8/site-packages/celery/app/trace.py:622: RuntimeWarning: Exception raised outside body: OperationalError('Error 104 while writing to socket. Connection reset by peer.'):
celery_1          | Traceback (most recent call last):
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 777, in send_packed_command
celery_1          |     self._sock.sendall(item)
celery_1          | ConnectionResetError: [Errno 104] Connection reset by peer
celery_1          |
celery_1          | During handling of the above exception, another exception occurred:
celery_1          |
celery_1          | Traceback (most recent call last):
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 454, in _reraise_as_library_errors
celery_1          |     yield
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 533, in _ensured
celery_1          |     return fun(*args, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 200, in _publish
celery_1          |     return channel.basic_publish(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 608, in basic_publish
celery_1          |     return self._put(routing_key, message, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 789, in _put
celery_1          |     client.lpush(self._q_for_pri(queue, pri), dumps(message))
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/commands/core.py", line 1963, in lpush
celery_1          |     return self.execute_command("LPUSH", name, *values)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command
celery_1          |     return old_execute_command(self, name, *args, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1176, in execute_command
celery_1          |     return conn.retry.call_with_retry(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 48, in call_with_retry
celery_1          |     fail(error)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1180, in <lambda>
celery_1          |     lambda error: self._disconnect_raise(conn, error),
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1166, in _disconnect_raise
celery_1          |     raise error
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 45, in call_with_retry
celery_1          |     return do()
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1177, in <lambda>
celery_1          |     lambda: self._send_command_parse_response(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1152, in _send_command_parse_response
celery_1          |     conn.send_command(*args)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 795, in send_command
celery_1          |     self.send_packed_command(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 788, in send_packed_command
celery_1          |     raise ConnectionError(f"Error {errno} while writing to socket. {errmsg}.")
celery_1          | redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.
celery_1          |
celery_1          | During handling of the above exception, another exception occurred:
celery_1          |
celery_1          | Traceback (most recent call last):
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 474, in trace_task
celery_1          |     _chsig.apply_async(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 1371, in apply_async
celery_1          |     return self.run(tasks, body, args, task_id=task_id, **merged_options)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 1430, in run
celery_1          |     header_result = header(*partial_args, task_id=group_id, **options)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 1065, in __call__
celery_1          |     return self.apply_async(partial_args, **options)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 1090, in apply_async
celery_1          |     results = list(self._apply_tasks(tasks, producer, app, p,
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 1172, in _apply_tasks
celery_1          |     sig.apply_async(producer=producer, add_to_parent=False,
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 647, in apply_async
celery_1          |     return self.run(args, kwargs, app=app, **(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 675, in run
celery_1          |     first_task.apply_async(**options)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 235, in apply_async
celery_1          |     return _apply(args, kwargs, **options)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 120, in apply_async
celery_1          |     return f(*args, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 566, in apply_async
celery_1          |     return app.send_task(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/app/base.py", line 741, in send_task
celery_1          |     amqp.send_task_message(P, name, message, **options)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/app/amqp.py", line 552, in send_task_message
celery_1          |     ret = producer.publish(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 178, in publish
celery_1          |     return _publish(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 566, in _ensured
celery_1          |     errback and errback(exc, 0)
celery_1          |   File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
celery_1          |     self.gen.throw(type, value, traceback)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 458, in _reraise_as_library_errors
celery_1          |     reraise(ConnectionError, ConnectionError(text_t(exc)),
celery_1          |   File "/usr/local/lib/python3.8/site-packages/vine/five.py", line 194, in reraise
celery_1          |     raise value.with_traceback(tb)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 454, in _reraise_as_library_errors
celery_1          |     yield
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 533, in _ensured
celery_1          |     return fun(*args, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 200, in _publish
celery_1          |     return channel.basic_publish(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 608, in basic_publish
celery_1          |     return self._put(routing_key, message, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 789, in _put
celery_1          |     client.lpush(self._q_for_pri(queue, pri), dumps(message))
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/commands/core.py", line 1963, in lpush
celery_1          |     return self.execute_command("LPUSH", name, *values)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command
celery_1          |     return old_execute_command(self, name, *args, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1176, in execute_command
celery_1          |     return conn.retry.call_with_retry(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 48, in call_with_retry
celery_1          |     fail(error)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1180, in <lambda>
celery_1          |     lambda error: self._disconnect_raise(conn, error),
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1166, in _disconnect_raise
celery_1          |     raise error
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 45, in call_with_retry
celery_1          |     return do()
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1177, in <lambda>
celery_1          |     lambda: self._send_command_parse_response(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1152, in _send_command_parse_response
celery_1          |     conn.send_command(*args)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 795, in send_command
celery_1          |     self.send_packed_command(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 788, in send_packed_command
celery_1          |     raise ConnectionError(f"Error {errno} while writing to socket. {errmsg}.")
celery_1          | kombu.exceptions.OperationalError: Error 104 while writing to socket. Connection reset by peer.
celery_1          |
celery_1          |   warn(RuntimeWarning(
celery_1          | [2022-02-24 04:16:19,947: INFO/ForkPoolWorker-7] Mocked SMS: Night workflow failed to +48xxxx
celery_1          | [2022-02-24 04:16:20,247: ERROR/ForkPoolWorker-7] Task apps.external_sources.tasks.daily_data_sync[db7f6e01-3086-4a40-bab0-f68ada64e658] raised unexpected: OperationalError('Error 104 while writing to socket. Connection reset by peer.')
celery_1          | Traceback (most recent call last):
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 777, in send_packed_command
celery_1          |     self._sock.sendall(item)
celery_1          | ConnectionResetError: [Errno 104] Connection reset by peer
celery_1          |
celery_1          | During handling of the above exception, another exception occurred:
celery_1          |
celery_1          | Traceback (most recent call last):
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 454, in _reraise_as_library_errors
celery_1          |     yield
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 533, in _ensured
celery_1          |     return fun(*args, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 200, in _publish
celery_1          |     return channel.basic_publish(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 608, in basic_publish
celery_1          |     return self._put(routing_key, message, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 789, in _put
celery_1          |     client.lpush(self._q_for_pri(queue, pri), dumps(message))
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/commands/core.py", line 1963, in lpush
celery_1          |     return self.execute_command("LPUSH", name, *values)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command
celery_1          |     return old_execute_command(self, name, *args, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1176, in execute_command
celery_1          |     return conn.retry.call_with_retry(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 48, in call_with_retry
celery_1          |     fail(error)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1180, in <lambda>
celery_1          |     lambda error: self._disconnect_raise(conn, error),
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1166, in _disconnect_raise
celery_1          |     raise error
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 45, in call_with_retry
celery_1          |     return do()
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1177, in <lambda>
celery_1          |     lambda: self._send_command_parse_response(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1152, in _send_command_parse_response
celery_1          |     conn.send_command(*args)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 795, in send_command
celery_1          |     self.send_packed_command(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 788, in send_packed_command
celery_1          |     raise ConnectionError(f"Error {errno} while writing to socket. {errmsg}.")
celery_1          | redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.
celery_1          |
celery_1          | During handling of the above exception, another exception occurred:
celery_1          |
celery_1          | Traceback (most recent call last):
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 474, in trace_task
celery_1          |     _chsig.apply_async(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 1371, in apply_async
celery_1          |     return self.run(tasks, body, args, task_id=task_id, **merged_options)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 1430, in run
celery_1          |     header_result = header(*partial_args, task_id=group_id, **options)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 1065, in __call__
celery_1          |     return self.apply_async(partial_args, **options)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 1090, in apply_async
celery_1          |     results = list(self._apply_tasks(tasks, producer, app, p,
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 1172, in _apply_tasks
celery_1          |     sig.apply_async(producer=producer, add_to_parent=False,
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 647, in apply_async
celery_1          |     return self.run(args, kwargs, app=app, **(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 675, in run
celery_1          |     first_task.apply_async(**options)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/canvas.py", line 235, in apply_async
celery_1          |     return _apply(args, kwargs, **options)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 120, in apply_async
celery_1          |     return f(*args, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 566, in apply_async
celery_1          |     return app.send_task(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/app/base.py", line 741, in send_task
celery_1          |     amqp.send_task_message(P, name, message, **options)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/celery/app/amqp.py", line 552, in send_task_message
celery_1          |     ret = producer.publish(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 178, in publish
celery_1          |     return _publish(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 566, in _ensured
celery_1          |     errback and errback(exc, 0)
celery_1          |   File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
celery_1          |     self.gen.throw(type, value, traceback)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 458, in _reraise_as_library_errors
celery_1          |     reraise(ConnectionError, ConnectionError(text_t(exc)),
celery_1          |   File "/usr/local/lib/python3.8/site-packages/vine/five.py", line 194, in reraise
celery_1          |     raise value.with_traceback(tb)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 454, in _reraise_as_library_errors
celery_1          |     yield
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/connection.py", line 533, in _ensured
celery_1          |     return fun(*args, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/messaging.py", line 200, in _publish
celery_1          |     return channel.basic_publish(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 608, in basic_publish
celery_1          |     return self._put(routing_key, message, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/kombu/transport/redis.py", line 789, in _put
celery_1          |     client.lpush(self._q_for_pri(queue, pri), dumps(message))
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/commands/core.py", line 1963, in lpush
celery_1          |     return self.execute_command("LPUSH", name, *values)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command
celery_1          |     return old_execute_command(self, name, *args, **kwargs)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1176, in execute_command
celery_1          |     return conn.retry.call_with_retry(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 48, in call_with_retry
celery_1          |     fail(error)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1180, in <lambda>
celery_1          |     lambda error: self._disconnect_raise(conn, error),
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1166, in _disconnect_raise
celery_1          |     raise error
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 45, in call_with_retry
celery_1          |     return do()
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1177, in <lambda>
celery_1          |     lambda: self._send_command_parse_response(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1152, in _send_command_parse_response
celery_1          |     conn.send_command(*args)
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 795, in send_command
celery_1          |     self.send_packed_command(
celery_1          |   File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 788, in send_packed_command
celery_1          |     raise ConnectionError(f"Error {errno} while writing to socket. {errmsg}.")
celery_1          | kombu.exceptions.OperationalError: Error 104 while writing to socket. Connection reset by peer.
```

**Comment by antonpirker** [comment]
Hey @Alexander3 !
After researching a little I found out that the problem is not in Celery but either in Redis (or RabbitMQ): https://github.com/celery/celery/issues/4867

Can you provide by any chance a simple project where I can reproduce this error?
Maybe having a redis that is configured in a way that it is soon overwhelmed by celery connections and starts raising errors?

With this I could then investigate on how to catch those errors in Sentry!

**Comment by cguinard-fbx** [comment]
Hello, 

same issue here, with **sentry-sdk 1.32.0**, errors in kombu code are not caught by Sentry, although errors in task body are well tracked.

## Exception	

EncodeError(TypeError('Object of type AsyncResult is not JSON serializable'))

## Traceback

```
Traceback (most recent call last):
  File "/home/fbox/env/lib/python3.10/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/home/fbox/env/lib/python3.10/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/home/fbox/env/lib/python3.10/site-packages/kombu/utils/json.py", line 57, in dumps
    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/fbox/env/lib/python3.10/site-packages/kombu/utils/json.py", line 45, in default
    return super().default(o)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AsyncResult is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fbox/env/lib/python3.10/site-packages/celery/app/trace.py", line 544, in trace_task
    task.backend.mark_as_done(
  File "/home/fbox/env/lib/python3.10/site-packages/celery/backends/base.py", line 157, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "/home/fbox/env/lib/python3.10/site-packages/celery/backends/base.py", line 526, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/home/fbox/env/lib/python3.10/site-packages/django_celery_results/backends/database.py", line 122, in _store_result
    content_type, content_encoding, result = self.encode_content(result)
  File "/home/fbox/env/lib/python3.10/site-packages/django_celery_results/backends/database.py", line 178, in encode_content
    content_type, content_encoding, content = self._encode(data)
  File "/home/fbox/env/lib/python3.10/site-packages/celery/backends/base.py", line 417, in _encode
    return dumps(data, serializer=self.serializer)
  File "/home/fbox/env/lib/python3.10/site-packages/kombu/serialization.py", line 219, in dumps
    with _reraise_errors(EncodeError):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/fbox/env/lib/python3.10/site-packages/kombu/serialization.py", line 45, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/home/fbox/env/lib/python3.10/site-packages/kombu/exceptions.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/home/fbox/env/lib/python3.10/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/home/fbox/env/lib/python3.10/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/home/fbox/env/lib/python3.10/site-packages/kombu/utils/json.py", line 57, in dumps
    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/fbox/env/lib/python3.10/site-packages/kombu/utils/json.py", line 45, in default
    return super().default(o)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type AsyncResult is not JSON serializable
```
