### ISSUE TITLE
Error when using FlaskIntegration and Eventlet

### ISSUE THREAD

**Issue by omardlhz** [getsentry/sentry-python#137]
I'm using [Flask-SocketIO](https://github.com/miguelgrinberg/Flask-SocketIO) in my implementation.

When using `sentry_sdk.init(integrations=[FlaskIntegration()])` and a socket disconnects, I get the following error:

```bash
Traceback (most recent call last):
  File ".../env/lib/python3.4/site-packages/eventlet/wsgi.py", line 578, in handle_one_response
    write(b'')
  File ".../env/lib/python3.4/site-packages/eventlet/wsgi.py", line 470, in write
    raise AssertionError("write() before start_response()")
AssertionError: write() before start_response()
```

If I get rid of the FlaskIntegration, the error doesn't show up on socket disconnect. What could be causing this issue?

**Comment by untitaker** [comment]
If you switch away from eventlet to the regular devserver (flask-socketio claims to work with this), do you still have this issue?

**Comment by omardlhz** [comment]
Using the regular devserver in flask-socketio doesnt support WebSocket transport, only long-polling transport. From the docs:

> The Flask development server based on Werkzeug can be used as well, with the caveat that it lacks the performance of the other two options, so it should only be used to simplify the development workflow. This option only supports the long-polling transport.

**Comment by untitaker** [comment]
Thanks, I will try to reproduce this

**Comment by untitaker** [comment]
@omardlhz I can't reproduce this with eventlet. Here is the code I am using:

```python
from flask import Flask, render_template
from flask_socketio import SocketIO

import sentry_sdk
from sentry_sdk.integrations.flask import FlaskIntegration
sentry_sdk.init(integrations=[FlaskIntegration()], debug=True)

app = Flask(__name__)
app.config['SECRET_KEY'] = 'testbar'
socketio = SocketIO(app)

@app.route('/')
def index():
    return render_template("index.html")

@socketio.on('my event')
def handle_message(message):
    print('received message: ' + str(message))

@socketio.on('disconnect')
def test_disconnect():
    print('Client disconnected')

if __name__ == '__main__':
    socketio.run(app)
```

The `index.html` is just from Flask-SocketIO's website.

**Comment by untitaker** [comment]
If you can reproduce the issue with the above app, I would like to have the usual:

* OS
* output of `pip freeze`
* whatever else you can think of

**Comment by untitaker** [comment]
Closing due to inactivity, please ping if you have more information about this

**Comment by Divide-By-0** [comment]
I get this other error on local machine without gunicorn or nginx.

These are the relevant subset of my requirements:
```
sentry_sdk == 0.14.3
Flask_SocketIO == 4.2.1
eventlet == 0.25.1
```

This is my flask-socketio code on the server side:
```
socketio = SocketIO(engineio_logger=True, logger=True, debug=True, cors_allowed_origins="*", path='/socket.io')
...
socketio.init_app(app, async_mode="eventlet")
```

And this is my React socket io code on the client side:
```
          this.socket = io.connect(`http://localhost:5000?info=${someInfo}`, {
            transports: ['websocket', 'polling'] // an attempt to keep polling as a fallback but start on websockets
          });
```
Let me know if this helps. On Ubuntu the error looks like the above one, and locally on Windows it looks like this, when I refresh the react page. Notably the leave method on 
```Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 599, in handle_one_response
    write(b'')
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 491, in write
    raise AssertionError("write() before start_response()")
AssertionError: write() before start_response()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 357, in __init__
    self.handle()
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 390, in handle
    self.handle_one_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 466, in handle_one_request
    self.handle_one_response()
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 609, in handle_one_response
    write(err_body)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 538, in write
    wfile.flush()
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 607, in write
    return self._sock.send(b)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\greenio\base.py", line 397, in send
    return self._send_loop(self.fd.send, data, flags)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\greenio\base.py", line 384, in _send_loop
    return send_method(data, *args)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\hubs\hub.py", line 461, in fire_timers
    timer()
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\hubs\timer.py", line 59, in __call__
    cb(*args, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\semaphore.py", line 147, in _do_acquire
    waiter.switch()
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 818, in process_request
    proto.__init__(conn_state, self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 359, in __init__
    self.finish()
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\wsgi.py", line 732, in finish
    BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "C:\ProgramData\Anaconda3\lib\socketserver.py", line 784, in finish
    self.wfile.close()
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 607, in write
    return self._sock.send(b)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\greenio\base.py", line 397, in send
    return self._send_loop(self.fd.send, data, flags)
  File "C:\ProgramData\Anaconda3\lib\site-packages\eventlet\greenio\base.py", line 384, in _send_loop
    return send_method(data, *args)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine```

**Comment by Divide-By-0** [comment]
Can confirm this is a sentry error, don't get this error when I disable sentry. @untitaker

**Comment by untitaker** [comment]
I tried to create a minimal reproducible example already and failed, could you try to create one?

**Comment by Divide-By-0** [comment]
Enable eventlet.monkey_patch, run the socketio client with flask, and enable sentry with your sentry key. That should reproduce the error.

**Comment by Divide-By-0** [comment]
@untitaker what was the minimal example you tested, did it have those 3 components? It occurs when a socket is connected on the front-end then disconnects so you may need a minimal frontend implementation as well that connects the sockets

**Comment by untitaker** [comment]
@Divide-By-0 I can't remember if I used eventlet but I definetly used flask-socketio. I would apprechiate it if you could give me a repo I can check out to try and reproduce this
