### ISSUE TITLE
Sentry + Django 4.0 Admin Breaking

### ISSUE THREAD

**Issue by dan1229** [getsentry/sentry-python#1392]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.9

### Steps to Reproduce

1. Go to Django admin
2. Click any model 'section' - i.e., the list of objects not a specific object details

### Expected Result

Should be able to view list of objects for that specific model.

### Actual Result

Breaks for every model I have, I'm not even convinced this is fully a Sentry error but the Django Admin modules and Sentry seem to be the only one's the stacktrace touches.

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/management/blog/collection/

Django Version: 4.0.3
Python Version: 3.9.9
Installed Applications:
['core',
 'api',
 'blog',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'whitenoise.runserver_nostatic',
 'django.contrib.staticfiles',
 'rest_framework',
 'rest_framework.authtoken',
 'drf_yasg',
 'django_filters',
 'drf_api_logger',
 'django_extensions',
 'safedelete',
 'corsheaders',
 'storages']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware']



Traceback (most recent call last):
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/contrib/admin/options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/contrib/admin/options.py", line 831, in get_changelist_instance
    return ChangeList(
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 123, in __init__
    self.get_results(request)
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 279, in get_results
    result_count = paginator.count
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/core/paginator.py", line 96, in count
    return c()
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/db/models/query.py", line 470, in count
    return self.query.get_count(using=self.db)
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/db/models/sql/query.py", line 543, in get_count
    number = obj.get_aggregation(using, ["__count"])["__count"]
  File "/Users/daniel/.local/share/virtualenvs/Dans-Backend-iL6tWd89/lib/python3.9/site-packages/django/db/models/sql/query.py", line 527, in get_aggregation
    compiler = outer_query.get_compiler(using, elide_empty=elide_empty)

Exception Type: TypeError at /management/blog/collection/
Exception Value: get_compiler() got an unexpected keyword argument 'elide_empty'
```

**Comment by sl0thentr0py** [comment]
@dan1229 we haven't officially looked into Django 4 yet and we're aware it's already been a while. We'll hopefully update all our major integrations to work with new major releases in the next couple of months.

**Comment by dan1229** [comment]
So I wasn't fully convinced this was actually an issue with Sentry but rather with Sentry wrapping the actual issue.

I dug in a bit more and TLDR the issue seems to be due to another library - maybe worth looking into how Sentry silenced this but all to say false alarm :)

**Comment by attract** [comment]
I had the some problem.
The Solution - install latest version **django-safedelete** package. In my case:

```
Django = "4.0.6"
django-safedelete = "1.2.2"
```
