### ISSUE TITLE
Multiple errors on apache restart from the sdk. 

### ISSUE THREAD

**Issue by anilshanbhag** [getsentry/sentry-python#1455]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.12

### Steps to Reproduce

I have an apache server running Django 3.2.8 using mod_wsgi. Every time I restart the server as

```
sudo apachectl -k graceful
```

There are many errors in the apache logs that seem to be coming from sentry SDK (attached below). The errors go away if I disable sentry and restart the server. This is not impacting operations but felt it is good to report as its a bug. 

### Expected Result

No errors

### Actual Result

```
[Sat Jun 04 21:44:18.240137 2022] [mpm_prefork:notice] [pid 1929371] AH00171: Graceful restart requested, doing restart
Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(raven-sentry.BackgroundWorker, stopped daemon 140210030446336)>>
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/ubuntu/webapps/venv/lib/python3.7/site-packages/sentry_sdk/integrations/excepthook.py", line 49, in sentry_sdk_excepthook
  File "/home/ubuntu/webapps/venv/lib/python3.7/site-packages/sentry_sdk/hub.py", line 270, in get_integration
NameError: name 'isinstance' is not defined

Original exception was:
Traceback (most recent call last):
  File "/home/ubuntu/webapps/venv/lib/python3.7/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
  File "/usr/lib/python3.7/threading.py", line 870, in run
  File "/home/ubuntu/webapps/venv/lib/python3.7/site-packages/sentry_sdk/worker.py", line 123, in _target
  File "/home/ubuntu/webapps/venv/lib/python3.7/site-packages/sentry_sdk/_queue.py", line 179, in get
  File "/home/ubuntu/webapps/venv/lib/python3.7/site-packages/sentry_sdk/_queue.py", line 219, in _qsize
NameError: name 'len' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
  File "/home/ubuntu/webapps/venv/lib/python3.7/site-packages/sentry_sdk/integrations/threading.py", line 68, in run
NameError: name 'Exception' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 890, in _bootstrap
  File "/usr/lib/python3.7/threading.py", line 927, in _bootstrap_inner
NameError: name 'SystemExit' is not defined
Exception ignored in: <function Transport.__del__ at 0x7f854065a7a0>
Traceback (most recent call last):
  File "/home/ubuntu/webapps/venv/lib/python3.7/site-packages/sentry_sdk/transport.py", line 114, in __del__
NameError: name 'Exception' is not defined
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f85414e67a0>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 625, in __del__
NameError: name 'ResourceWarning' is not defined
```

**Comment by sl0thentr0py** [comment]
@anilshanbhag I don't really know how `mod_wsgi` works but the exceptions are really strange. `isinstance` and `len` not being defined points to an issue with some weird python interpreter setup. I found [this](https://github.com/GrahamDumpleton/mod_wsgi/issues/206) but also not sure if it's related.

**Comment by egyptexan** [comment]
We're also experiencing this issue.  

sentry-sdk: 1.15.0
apache: 2.4.6-98.el7.centos.6
mod_wsgi: 3.4-18.el7
python: 3.8
