### ISSUE TITLE
FastAPI Integration - TypeError: 'coroutine' object is not callable

### ISSUE THREAD

**Issue by danilogco** [getsentry/sentry-python#1514]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.8.0

### Steps to Reproduce

1. Install the lib v1.8.0;
2. Our Sentry server is self-hosted;
3. Configure the sentry inicialization as described in the release documentation:
```python
from fastapi import FastAPI
from sentry_sdk.integrations.starlette import StarletteIntegration
from sentry_sdk.integrations.fastapi import FastApiIntegration
sentry_sdk.init(
dsn="...",
integrations=[StarletteIntegration(), FastApiIntegration()],
)
app = FastAPI()
```
4. So I did purposefully a request that would give me a 404/500 to activate the sentry warning.

Thanks in advance.

### Expected Result

Sentry 404 log sent successfully.

### Actual Result

web-1        | /usr/local/lib/python3.10/site-packages/sentry_sdk/serializer.py:216: RuntimeWarning: coroutine 'request_validation_exception_handler' was never awaited
web-1        |   with memo.memoize(obj) as result:
web-1        | RuntimeWarning: Enable tracemalloc to get the object allocation traceback
web-1        | ERROR:    Exception in ASGI application
web-1        | Traceback (most recent call last):
web-1        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
web-1        |     result = await app(self.scope, self.receive, self.send)
web-1        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
web-1        |     return await self.app(scope, receive, send)
web-1        |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
web-1        |     await super().__call__(scope, receive, send)
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 268, in _sentry_patched_asgi_app
web-1        |     return await middleware(scope, receive, send)
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 126, in _run_asgi3
web-1        |     return await self._run_app(scope, lambda: self.app(scope, receive, send))
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 176, in _run_app
web-1        |     raise exc from None
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 171, in _run_app
web-1        |     return await callback()
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 268, in _sentry_patched_asgi_app
web-1        |     return await middleware(scope, receive, send)
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 126, in _run_asgi3
web-1        |     return await self._run_app(scope, lambda: self.app(scope, receive, send))
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 137, in _run_app
web-1        |     raise exc from None
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 134, in _run_app
web-1        |     return await callback()
web-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
web-1        |     await self.middleware_stack(scope, receive, send)
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/fastapi.py", line 122, in __call__
web-1        |     await self.app(scope, receive, send)
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 461, in __call__
web-1        |     await self.app(scope, receive, send)
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 86, in _create_span_call
web-1        |     await old_call(*args, **kwargs)
web-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
web-1        |     raise exc
web-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
web-1        |     await self.app(scope, receive, _send)
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 86, in _create_span_call
web-1        |     await old_call(*args, **kwargs)
web-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
web-1        |     await self.app(scope, receive, send)
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 160, in _sentry_exceptionmiddleware_call
web-1        |     await old_call(self, scope, receive, send)
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 160, in _sentry_exceptionmiddleware_call
web-1        |     await old_call(self, scope, receive, send)
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 160, in _sentry_exceptionmiddleware_call
web-1        |     await old_call(self, scope, receive, send)
web-1        |   [Previous line repeated 1 more time]
web-1        |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 86, in _create_span_call
web-1        |     await old_call(*args, **kwargs)
web-1        |   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 104, in __call__
web-1        |     await response(scope, receive, sender)
web-1        | TypeError: 'coroutine' object is not callable

**Comment by u-iandono** [comment]
Got the same error,

I'm using Sentry SaaS (sentry.io)

```
Traceback (most recent call last):
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asg
i
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__     
    return await self.app(scope, receive, send)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\starlette.py", line 268, in _sentry_pat
ched_asgi_app
    return await middleware(scope, receive, send)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\asgi.py", line 126, in _run_asgi3      
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\asgi.py", line 176, in _run_app        
    raise exc from None
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\asgi.py", line 171, in _run_app        
    return await callback()
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\starlette.py", line 268, in _sentry_pat
ched_asgi_app
    return await middleware(scope, receive, send)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\asgi.py", line 126, in _run_asgi3      
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\asgi.py", line 137, in _run_app        
    raise exc from None
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\asgi.py", line 134, in _run_app        
    return await callback()
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\fastapi.py", line 122, in __call__     
    await self.app(scope, receive, send)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\starlette.py", line 461, in __call__   
    await self.app(scope, receive, send)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\starlette.py", line 86, in _create_span
_call
    await old_call(*args, **kwargs)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\starlette.py", line 86, in _create_span
_call
    await old_call(*args, **kwargs)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\starlette.py", line 86, in _create_span
_call
    await old_call(*args, **kwargs)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\starlette\middleware\sessions.py", line 80, in __call__        
    await self.app(scope, receive, send_wrapper)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\starlette.py", line 160, in _sentry_exc
eptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\starlette.py", line 160, in _sentry_exc
eptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\starlette.py", line 160, in _sentry_exc
eptionmiddleware_call
    await old_call(self, scope, receive, send)
  [Previous line repeated 3 more times]
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\sentry_sdk\integrations\starlette.py", line 86, in _create_span
_call
    await old_call(*args, **kwargs)
  File "C:\Users\x\.virtualenvs\x-M0aUaMTg\lib\site-packages\starlette\exceptions.py", line 104, in __call__
    await response(scope, receive, sender)
TypeError: 'coroutine' object is not callable
```

**Comment by ybinnenwegin2ip** [comment]
+1 I was able to get the same error when trying to do a POST. I'll see if I can get a minimal piece of code with which this can be reproduced.

**Comment by ybinnenwegin2ip** [comment]
Alright with this code you can see the issues:

```python
from fastapi import FastAPI, Form

import sentry_sdk
from sentry_sdk.integrations.starlette import StarletteIntegration
from sentry_sdk.integrations.fastapi import FastApiIntegration

SENTRY_ENABLED = True
SENTRY_URI = ''

if SENTRY_ENABLED:
    sentry_sdk.init(
        SENTRY_URI,
        integrations=[StarletteIntegration(), FastApiIntegration()],
    )

app = FastAPI()

# works fine
@app.get("/")
async def root():
    return {"message": "Hello World"}

# broken
@app.post("/my-post")
async def my_post(name: str = Form(...)):
    return {"message": f"Your name is {name}"}
```

Run it with: `uvicorn main:app`

A couple of observations:
- POST requests seem to be broken. They never finish. When running the code above, open http://127.0.0.1/docs and do a POST to the my-post endpoint. Swagger will show an endlessly looping loading animation.
- When going to a page that does not exist (e.g. http://127.0.0.1:8000/ohno) you get the exception that @danilogco posted.
- When one of the aforementioned exceptions has occured, the following gets printed when doing CTRL + C:
```
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1589034]
sys:1: RuntimeWarning: coroutine 'request_validation_exception_handler' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by antonpirker** [comment]
Hey everyone! Thanks for reporting this! I will have a look at this in the afternoon!

**Comment by danilogco** [comment]
@antonpirker thanks!

**Comment by antonpirker** [comment]
@ybinnenwegin2ip Thanks for the project to reproduce this!

So there are two issues:
* When going to a non existent route the `coroutine` error is raised
* When posting a form we end up in an infinite loop.

I have reproduced both problems but will not be able to fix them before the weekend. Will fix this beginning of next week.

**Comment by twogood** [comment]
Any progress on this?
