### ISSUE TITLE
Typo in setup.py for 1.9.1 release breaks `conda export`

### ISSUE THREAD

**Issue by timstaley** [getsentry/sentry-python#1544]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.9.1

### Steps to Reproduce

This line 
https://github.com/getsentry/sentry-python/commit/b7c0dc412a1505fff382732f567952c8a9572b60#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R43

`'urllib3>=1.26.11"; python_version >="3.6"',`

Has a stray `"` after the urllib3 version number.

This passes by pipi but confuses conda, causing a very opaque error message when you try to run `conda export`:
```
InvalidVersionSpec: Invalid version '(>=1.26.11': unable to convert to expression tree: ['(']
```

Steps to reproduce:
```
conda create -n test-sentry-sdk python=3.8
conda activate test-sentry-sdk
pip install sentry-sdk==1.9.1
conda export
```

### Expected Result

Expect to get a conda environment yaml spec.

### Actual Result

```
InvalidVersionSpec: Invalid version '(>=1.26.11': unable to convert to expression tree: ['(']
```

**Comment by vladanpaunovic** [comment]
@timstaley, thanks for a good reproduction case!

We fixed this in our latest [release v1.9.2](https://github.com/getsentry/sentry-python/releases/tag/1.9.2).
Please, give it a try.

**Comment by timstaley** [comment]
Many thanks for the speedy resolution 👍

**Comment by deronnax** [comment]
I am getting the same and it crashes PDM dependencies resolution. I tried a straight pip install and it crashed just the same. So the package is basically not installable. Could please yank it from PyPI?

```
$ pip install sentry_sdk==1.9.1


Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/packaging/_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/packaging/_parser.py", line 206, in _parse_specifier
    with tokenizer.enclosing_tokens("LEFT_PARENTHESIS", "RIGHT_PARENTHESIS"):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/packaging/_tokenizer.py", line 183, in enclosing_tokens
    self.raise_syntax_error(
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/packaging/_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
packaging._tokenizer.ParserSyntaxError: Expected closing RIGHT_PARENTHESIS
    urllib3 (>=1.26.11") ; python_version >= "3.6"
            ~~~~~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/bin/pipx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/main.py", line 863, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/main.py", line 214, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/commands/install.py", line 60, in install
    venv.install_package(
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/venv.py", line 257, in install_package
    self._update_package_metadata(
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/venv.py", line 331, in _update_package_metadata
    venv_package_metadata = self.get_venv_metadata_for_package(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/venv.py", line 313, in get_venv_metadata_for_package
    venv_metadata = inspect_venv(
                    ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/venv_inspect.py", line 251, in inspect_venv
    app_paths_of_dependencies = _dfs_package_apps(
                                ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/venv_inspect.py", line 121, in _dfs_package_apps
    dependencies = get_package_dependencies(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/pipx/venv_inspect.py", line 54, in get_package_dependencies
    for req in map(Requirement, dist.requires or []):
  File "/opt/homebrew/Cellar/pipx/1.2.0/libexec/lib/python3.11/site-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    urllib3 (>=1.26.11") ; python_version >= "3.6"
            ~~~~~~~~~~^
 ```
