### ISSUE TITLE
pycharm ModuleNotFoundError: No module named 'sentry_sdk'

### ISSUE THREAD

**Issue by jen-soft** [getsentry/sentry-python#1579]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.9.5

### Steps to Reproduce

1) start environment 
python 3.7 
django 3.1
pycharm
1) install sentry-sdk==1.9.5
2) add DjangoIntegration to django-settings
https://docs.sentry.io/platforms/python/guides/logging/
3) run django server by pycharm in debug mode.

### Expected Result

  File "/home/user/CODE/projects/ai-chat-api/src/ai_chat_api/ai_chat_api/settings/development.py", line 21, in <module>
    from .base import *
  File "/home/user/CODE/projects/ai-chat-api/src/ai_chat_api/ai_chat_api/settings/base.py", line 434, in <module>
    import sentry_sdk
ModuleNotFoundError: No module named 'sentry_sdk'

### Actual Result

/home/user/CODE/venv/ai-chat-api/bin/python /home/user/CODE/projects/ai-chat-api/src/ai_chat_api/manage.py runserver localhost:8000 --noreload --force-color
IS DEBUG False
ALLOWED_HOSTS []
WARING: set default DJANGO_SETTINGS_MODULE = settings/development.py !
IS DEBUG False
ALLOWED_HOSTS []
IS DEBUG False
ALLOWED_HOSTS []
IS DEBUG False
ALLOWED_HOSTS []
Traceback (most recent call last):
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/CODE/projects/ai-chat-api/src/ai_chat_api/ai_chat_api/settings/local.py", line 35, in <module>
    from .development import *
  File "/home/user/CODE/projects/ai-chat-api/src/ai_chat_api/ai_chat_api/settings/development.py", line 21, in <module>
    from .base import *
  File "/home/user/CODE/projects/ai-chat-api/src/ai_chat_api/ai_chat_api/settings/base.py", line 434, in <module>
    import sentry_sdk
ModuleNotFoundError: No module named 'sentry_sdk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CODE/projects/ai-chat-api/src/ai_chat_api/manage.py", line 56, in <module>
    main()
  File "/home/user/CODE/projects/ai-chat-api/src/ai_chat_api/manage.py", line 52, in main
    execute_from_command_line(sys.argv)
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/core/management/base.py", line 343, in run_from_argv
    connections.close_all()
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/db/utils.py", line 232, in close_all
    for alias in self:
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/db/utils.py", line 226, in __iter__
    return iter(self.databases)
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/CODE/projects/ai-chat-api/src/ai_chat_api/ai_chat_api/settings/local.py", line 35, in <module>
    from .development import *
  File "/home/user/CODE/projects/ai-chat-api/src/ai_chat_api/ai_chat_api/settings/development.py", line 21, in <module>
    from .base import *
  File "/home/user/CODE/projects/ai-chat-api/src/ai_chat_api/ai_chat_api/settings/base.py", line 434, in <module>
    import sentry_sdk
ModuleNotFoundError: No module named 'sentry_sdk'

Process finished with exit code 1

**Comment by sl0thentr0py** [comment]
this seems like a problem with your `venv/pip` setup, please make sure `sentry-sdk` is installed correctly under 
`/home/user/CODE/venv/ai-chat-api/lib/python3.7/site-packages/`.
