### ISSUE TITLE
IndexError in get_integration

### ISSUE THREAD

**Issue by iMerica** [getsentry/sentry-python#172]
I run Sentry on my Celery tasks and when the task raises an error, I see this in the Sentry SDK.
```
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1342, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1336, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1443, in _log
    self.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1453, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/logging.py", line 61, in sentry_patched_callhandlers
    integration = Hub.current.get_integration(LoggingIntegration)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/hub.py", line 153, in get_integration
    client = self._stack[-1][0]
IndexError: list index out of range

```

**Comment by untitaker** [comment]
Hi, we use celery in production already so this bug is quite surprising to us. Could you answer the following questions:

* which version of the SDK do you use?
* I believe there's a chunk missing from that stacktrace (at the beginning)
* do you have the celery integration enabled?
* do you use celery with eventlet?

**Comment by iMerica** [comment]
### Sentry SDK Version: 
`sentry-sdk==0.5.3`

### Complete Stack Trace

```
[2018-11-19 18:04:54,400: ERROR/MainProcess] Task handler raised error: IndexError('list index out of range',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/billiard/pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 549, in _fast_trace_task
    uuid, args, kwargs, request,
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 492, in trace_task
    I, _, _, _ = on_error(task_request, exc, uuid)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 338, in on_error
    task, request, eager=eager, call_errbacks=call_errbacks,
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 172, in handle_error_state
    call_errbacks=call_errbacks)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 225, in handle_failure
    einfo=einfo)
  File "/usr/local/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 293, in send
    'Signal handler %r raised: %r', receiver, exc)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1342, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1336, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1443, in _log
    self.handle(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1453, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/logging.py", line 61, in sentry_patched_callhandlers
    integration = Hub.current.get_integration(LoggingIntegration)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/hub.py", line 153, in get_integration
    client = self._stack[-1][0]
IndexError: list index out of range

```

### Celery Integration Status

Not enabled

### Celery Eventlet Status

Not using Eventlet

**Comment by untitaker** [comment]
Okay. We didn't test running celery without the integration so that might as well be it. Check out https://docs.sentry.io/platforms/python/celery/ to get started, you'll get nicer errors in Sentry with this anyway (just add `CeleryIntegration()` to the integrations array)

**Comment by iMerica** [comment]
Whoops, it looks like I am indeed using Celery integration:

Snippet at the top of the relevant Python module
```
logger = logging.getLogger('xxxxxxxxx')
logger.setLevel(logging.INFO)

sentry_logging = LoggingIntegration(
    level=logging.INFO,        # Capture info and above as breadcrumbs
    event_level=logging.ERROR  # Send errors as events
)
sentry_sdk.init(os.getenv('SENTRY_URL'), integrations=[CeleryIntegration(), sentry_logging])
```

**Comment by iMerica** [comment]
I see the print statement once a task gets triggered, not when I start the worker.

**Comment by untitaker** [comment]
Could you try to init celery sooner than that? In case you don't have all configuration data earlier than where you initialize it now, you can init the sdk twice:

    # when celery starts, without DSN
    init(integrations=[CeleryIntegration()])

    # when you have your config
    init(DSN, integrations=[CeleryIntegration()])

if this doesn't fix it I'll try to reproduce

**Comment by untitaker** [comment]
A probably good place would be your `celeryconfig.py`: http://docs.celeryproject.org/en/latest/userguide/configuration.html#example-configuration-file

at least in our setup this one is not lazy-loaded

**Comment by iMerica** [comment]
Update: I wasn't able to work around this issue so I just disabled Sentry in Celery.

**Comment by untitaker** [comment]
@iMerica did you try what I suggested?
