### ISSUE TITLE
Sentry does not send events

### ISSUE THREAD

**Issue by gabrielfgularte** [getsentry/sentry-python#1843]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.13.0

### Steps to Reproduce

1. Follow the installation Python/Django tutorial - my project has Django Channels and Uvicorn, but I've worked before with another projects and they used to work well.
2. Add a path to test the error sending
3. Nothing was sent to my sentry.io issues panel

### Expected Result

Bunches of `ZeroDivisionError at /sentry-debug/` on issues panel at sentry.io

### Actual Result

Nothing shows up on issues panel at sentry.io. Turning on the `debug` option on the `sentry_sdk.init()` function, I was able to see an `ERROR: Internal error in sentry_sdk`. Here's the log when I access the admin home page:

```
[sentry] DEBUG: [Tracing] Starting <http.server> transaction <generic ASGI request>
reload-backend-django-1  | INFO:     172.21.0.1:50232 - "GET /admin/ HTTP/1.1" 200 OK
reload-backend-django-1  |  [sentry] ERROR: Internal error in sentry_sdk
reload-backend-django-1  | Traceback (most recent call last):
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 441, in event_processor
reload-backend-django-1  |     DjangoRequestExtractor(request).extract_into_event(event)
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/sentry_sdk/integrations/_wsgi_common.py", line 72, in extract_into_event
reload-backend-django-1  |     elif self.raw_data():
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 484, in raw_data
reload-backend-django-1  |     return self.request.body
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/http/request.py", line 340, in body
reload-backend-django-1  |     self._body = self.read()
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/http/request.py", line 404, in read
reload-backend-django-1  |     return self._stream.read(*args, **kwargs)
reload-backend-django-1  |   File "/usr/local/lib/python3.8/tempfile.py", line 728, in read
reload-backend-django-1  |     return self._file.read(*args)
reload-backend-django-1  | ValueError: I/O operation on closed file.
reload-backend-django-1  |  [sentry] DEBUG: Sending envelope [envelope with 1 items (transaction)] project:4504521306406912 host:o4504408550998016.ingest.sentry.io
reload-backend-django-1  |  [sentry] DEBUG: [Tracing] Adding `sentry-trace` header 657f4ff9d1224574b2d3507f2ff9bf6c-8040eea479b5717f- to outgoing request to https://o4504408550998016.ingest.sentry.io/api/4504521306406912/envelope/.
```

**Comment by gabrielfgularte** [comment]
More logs from different pages. Here's the log when I access some 404 page:

```
reload-backend-django-1  |  [sentry] DEBUG: [Tracing] Starting <http.server> transaction <generic ASGI request>
reload-backend-django-1  | Not Found: /
reload-backend-django-1  | INFO:     172.21.0.1:52852 - "GET / HTTP/1.1" 404 Not Found
reload-backend-django-1  |  [sentry] ERROR: Internal error in sentry_sdk
reload-backend-django-1  | Traceback (most recent call last):
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 441, in event_processor
reload-backend-django-1  |     DjangoRequestExtractor(request).extract_into_event(event)
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/sentry_sdk/integrations/_wsgi_common.py", line 72, in extract_into_event
reload-backend-django-1  |     elif self.raw_data():
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 484, in raw_data
reload-backend-django-1  |     return self.request.body
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/http/request.py", line 340, in body
reload-backend-django-1  |     self._body = self.read()
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/http/request.py", line 404, in read
reload-backend-django-1  |     return self._stream.read(*args, **kwargs)
reload-backend-django-1  |   File "/usr/local/lib/python3.8/tempfile.py", line 728, in read
reload-backend-django-1  |     return self._file.read(*args)
reload-backend-django-1  | ValueError: I/O operation on closed file.
reload-backend-django-1  |  [sentry] ERROR: Internal error in sentry_sdk
reload-backend-django-1  | Traceback (most recent call last):
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 187, in _get_session
reload-backend-django-1  |     return self._session_cache
reload-backend-django-1  | AttributeError: 'SessionStore' object has no attribute '_session_cache'
reload-backend-django-1  | 
reload-backend-django-1  | During handling of the above exception, another exception occurred:
reload-backend-django-1  | 
reload-backend-django-1  | Traceback (most recent call last):
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 445, in event_processor
reload-backend-django-1  |     _set_user_info(request, event)
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 512, in _set_user_info
reload-backend-django-1  |     if user is None or not is_authenticated(user):
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 79, in is_authenticated
reload-backend-django-1  |     return request_user.is_authenticated
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/utils/functional.py", line 266, in inner
reload-backend-django-1  |     self._setup()
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/utils/functional.py", line 419, in _setup
reload-backend-django-1  |     self._wrapped = self._setupfunc()
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 25, in <lambda>
reload-backend-django-1  |     request.user = SimpleLazyObject(lambda: get_user(request))
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
reload-backend-django-1  |     request._cached_user = auth.get_user(request)
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 191, in get_user
reload-backend-django-1  |     user_id = _get_user_session_key(request)
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 60, in _get_user_session_key
reload-backend-django-1  |     return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 53, in __getitem__
reload-backend-django-1  |     return self._session[key]
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 192, in _get_session
reload-backend-django-1  |     self._session_cache = self.load()
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 42, in load
reload-backend-django-1  |     s = self._get_session_from_db()
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
reload-backend-django-1  |     return self.model.objects.get(
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
reload-backend-django-1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/db/models/query.py", line 646, in get
reload-backend-django-1  |     num = len(clone)
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/db/models/query.py", line 376, in __len__
reload-backend-django-1  |     self._fetch_all()
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/db/models/query.py", line 1867, in _fetch_all
reload-backend-django-1  |     self._result_cache = list(self._iterable_class(self))
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/db/models/query.py", line 87, in __iter__
reload-backend-django-1  |     results = compiler.execute_sql(
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
reload-backend-django-1  |     cursor = self.connection.cursor()
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/utils/asyncio.py", line 24, in inner
reload-backend-django-1  |     raise SynchronousOnlyOperation(message)
reload-backend-django-1  | django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
reload-backend-django-1  |  [sentry] DEBUG: Sending envelope [envelope with 1 items (transaction)] project:4504521306406912 host:o4504408550998016.ingest.sentry.io
reload-backend-django-1  |  [sentry] DEBUG: [Tracing] Adding `sentry-trace` header be102b4a7870413e9bbd8a8f432e3ade-93e388b45326ca99- to outgoing request to https://o4504408550998016.ingest.sentry.io/api/4504521306406912/envelope/.
```

**Comment by gabrielfgularte** [comment]
And a log from the `sentry-debug/` (the one that should log the `ZeroDivisionError` on sentry.io):

```
reload-backend-django-1  |  [sentry] DEBUG: [Tracing] Starting <http.server> transaction <generic ASGI request>
reload-backend-django-1  |  [sentry] DEBUG: Sending event, type:null level:error event_id:c5d7c162e75346caa2badfb9ad46745d project:4504521306406912 host:o4504408550998016.ingest.sentry.io
reload-backend-django-1  |  [sentry] DEBUG: [Tracing] Adding `sentry-trace` header cc274ca2d2cf473db60129906323cbd5-99b745e74f4b5ddf-1 to outgoing request to https://o4504408550998016.ingest.sentry.io/api/4504521306406912/store/.
reload-backend-django-1  |  [sentry] DEBUG: [Tracing] Adding `baggage` header sentry-trace_id=cc274ca2d2cf473db60129906323cbd5,sentry-environment=local,sentry-release=7ae0bd10ef7eeb6675e64186f6685ec137fd6c00,sentry-public_key=14ca142749174fffbbb2d6aa4083c121,sentry-transaction=/sentry-debug/,sentry-sample_rate=1.0 to outgoing request to https://o4504408550998016.ingest.sentry.io/api/4504521306406912/store/.
reload-backend-django-1  | Internal Server Error: /sentry-debug/
reload-backend-django-1  | Traceback (most recent call last):
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/asgiref/sync.py", line 486, in thread_handler
reload-backend-django-1  |     raise exc_info[1]
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/core/handlers/exception.py", line 42, in inner
reload-backend-django-1  |     response = await get_response(request)
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
reload-backend-django-1  |     response = await wrapped_callback(
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/asgiref/sync.py", line 448, in __call__
reload-backend-django-1  |     ret = await asyncio.wait_for(future, timeout=None)
reload-backend-django-1  |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
reload-backend-django-1  |     return await fut
reload-backend-django-1  |   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
reload-backend-django-1  |     result = self.fn(*self.args, **self.kwargs)
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/asgiref/sync.py", line 490, in thread_handler
reload-backend-django-1  |     return func(*args, **kwargs)
reload-backend-django-1  |   File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 79, in sentry_wrapped_callback
reload-backend-django-1  |     return callback(request, *args, **kwargs)
reload-backend-django-1  |   File "/app/./core/urls.py", line 14, in trigger_error
reload-backend-django-1  |     division_by_zero = 1 / 0
reload-backend-django-1  | ZeroDivisionError: division by zero
reload-backend-django-1  | INFO:     172.21.0.1:36108 - "GET /sentry-debug/ HTTP/1.1" 500 Internal Server Error
reload-backend-django-1  |  [sentry] DEBUG: Sending envelope [envelope with 1 items (transaction)] project:4504521306406912 host:o4504408550998016.ingest.sentry.io
reload-backend-django-1  |  [sentry] DEBUG: [Tracing] Adding `sentry-trace` header 5f47086be226463e87e8a2e89611a74f-a256ea31bfc84bf8- to outgoing request to https://o4504408550998016.ingest.sentry.io/api/4504521306406912/envelope/.
```

I can't see an `Internal error in sentry_sdk` on that one, but the log isn't on sentry.io panel anyway.

**Comment by gabrielfgularte** [comment]
The event seems to be captured, as shown on the performance panel:
![image](https://user-images.githubusercontent.com/1307137/212989549-3d34d71b-126e-464f-b467-0ee202bd96e8.png)

But they don't show as an error on the issues panel:
![image](https://user-images.githubusercontent.com/1307137/212989742-3b352855-6a77-4f1b-bb93-2c8f0c9f5757.png)

**Comment by gabrielfgularte** [comment]
The event seems to be captured, as shown on the performance panel:
![image](https://user-images.githubusercontent.com/1307137/212990382-1f7d8157-e08f-4f52-ad8f-e615ba4b925a.png)

But they don't show as an error on the issues panel:
![image](https://user-images.githubusercontent.com/1307137/212989742-3b352855-6a77-4f1b-bb93-2c8f0c9f5757.png)

**Comment by gabrielfgularte** [comment]
The event seems captured on the perfomance tab:
![image](https://user-images.githubusercontent.com/1307137/212990810-320e4969-b4ba-4a42-8aac-ac4ea470390e.png)

But it doens't show on the issues tab:
![image](https://user-images.githubusercontent.com/1307137/212991218-40172150-9604-4914-a8a9-3d596b2c7966.png)

**Comment by gabrielfgularte** [comment]
Sorry, it appears that was a "usage limit reached" thing that I was not aware of. Closing it.
