### ISSUE TITLE
Sentry crashes with trio/starlette/fastapi middleware

### ISSUE THREAD

**Issue by 8enmann** [getsentry/sentry-python#1992]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.13.0 

### Steps to Reproduce

Load test with > 100 QPS

### Expected Result

No crash

### Actual Result

Crash
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hypercorn/trio/task_group.py", line 22, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "/usr/local/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 325, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 139, in _run_asgi3
    return await self._run_app(scope, lambda: self.app(scope, receive, send))
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 188, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/asgi.py", line 183, in _run_app
    return await callback()
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/app/api_shared/middleware/websocket_error_handler.py", line 30, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/app/api/middleware/request_context.py", line 46, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/app/api/middleware/metrics_attributes.py", line 31, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 579, in __call__
    await self.app(scope, otel_receive, otel_send)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 130, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
  File "/app/api/middleware/access_logging.py", line 63, in __call__
    raise e
  File "/app/api/middleware/access_logging.py", line 59, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 223, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 223, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/starlette.py", line 223, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send) 
```

**Comment by antonpirker** [comment]
Hey @8enmann !

Thanks for writing in. Can you give more information?
- What Error is raised (you included the stack trace, but not the Exception name)
- Can you show what function is called that leads to this crash?
- Maybe a very simple demo project to reproduce this crash?

Thanks,
Anton
