### ISSUE TITLE
Testing sentry_sdk - `add_attachment` causes `transport` method not to be used (?)

### ISSUE THREAD

**Issue by kbakk** [getsentry/sentry-python#2006]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.19.1

### Steps to Reproduce

I'm attempting to upload attachments to Sentry. I have set up a test that verifies that exceptions are captured. However, it will not work if I use `scope.add_attachment(b"testing", filename="testing.log")`. 

The test (as suggested from [this SO answer](https://stackoverflow.com/a/61971765/2670584)) validates that the exceptins are appended (for simplicity in the reproducer it only validates the length). 

<details><summary>main.py</summary>

```py
import sentry_sdk
events = []
sentry_sdk.init(
    transport=events.append
)

with sentry_sdk.configure_scope() as scope:
    scope.set_tag("test", "yes")
    # scope.add_attachment(b"testing", filename="testing.log")

def main():
    print(non_existing_var)

if __name__ == '__main__':
    main()
```

</details> 

<details><summary>test_repro.py</summary>

```py
import pytest
import sentry_sdk
import main

def test_main():
    with pytest.raises(NameError) as exc_info:
        main.main()
    sentry_sdk.capture_exception(exc_info.value)
    sentry_sdk.Hub.current.flush()
    assert len(main.events) == 1

```

</details> 

When running `pytest test_repro.py` it will succeed, however by uncommenting `scope.add_attachment(b"testing", filename="testing.log")`, it will fail. 

### Expected Result

I would like to inspect that the attachment has been successfully added. Using `transport=events.append` may not be the corrrect approach (if a better one exists, please point me in that direction), but I wouldn't expect using `scope.add_attachment` to change the behavior. 

### Actual Result

Output from pytest with line uncommented::

```
>       assert len(main.events) == 1
E       assert 0 == 1
E        +  where 0 = len([])
E        +    where [] = main.events
```

**Comment by antonpirker** [comment]
Hey @kbakk 

This is how we test attachments in our SDKs test suite:
https://github.com/getsentry/sentry-python/blob/antonpirker/celery-beat-wo-restart/tests/test_basics.py#L370-L400

Could you set `debug=True` in your `sentry_sdk.init()` and paste the output here?

**Comment by kbakk** [comment]
Hi, sorry for the delay in the response here... Here's the output from Sentry:

```console
$ pytest test_repro.py -s
=================================================================== test session starts ===================================================================
platform darwin -- Python 3.9.16, pytest-7.3.0, pluggy-1.0.0
rootdir: /Users/krisb/Code/temp/repro-sentry-attachment
collecting ...  [sentry] DEBUG: Setting up integrations (with default = True)
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.django.DjangoIntegration: Django not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.flask.FlaskIntegration: Flask is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.starlette.StarletteIntegration: Starlette is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.fastapi.FastApiIntegration: Starlette is not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.bottle.BottleIntegration: Bottle not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.falcon.FalconIntegration: Falcon not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.sanic.SanicIntegration: Sanic not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.celery.CeleryIntegration: Celery not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.rq.RqIntegration: RQ not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.aiohttp.AioHttpIntegration: AIOHTTP not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.tornado.TornadoIntegration: Tornado not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.sqlalchemy.SqlalchemyIntegration: SQLAlchemy not installed.
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.pyramid.PyramidIntegration: Pyramid not installed
 [sentry] DEBUG: Did not import default integration sentry_sdk.integrations.boto3.Boto3Integration: botocore is not installed
 [sentry] DEBUG: Setting up previously not enabled integration logging
 [sentry] DEBUG: Setting up previously not enabled integration stdlib
 [sentry] DEBUG: Setting up previously not enabled integration excepthook
 [sentry] DEBUG: Setting up previously not enabled integration dedupe
 [sentry] DEBUG: Setting up previously not enabled integration atexit
 [sentry] DEBUG: Setting up previously not enabled integration modules
 [sentry] DEBUG: Setting up previously not enabled integration argv
 [sentry] DEBUG: Setting up previously not enabled integration threading
 [sentry] DEBUG: Setting up previously not enabled integration redis
 [sentry] DEBUG: Did not enable default integration redis: Redis client not installed
 [sentry] DEBUG: Enabling integration logging
 [sentry] DEBUG: Enabling integration stdlib
 [sentry] DEBUG: Enabling integration excepthook
 [sentry] DEBUG: Enabling integration dedupe
 [sentry] DEBUG: Enabling integration atexit
 [sentry] DEBUG: Enabling integration modules
 [sentry] DEBUG: Enabling integration argv
 [sentry] DEBUG: Enabling integration threading
 [sentry] DEBUG: Enabling integration redis
 [sentry] DEBUG: Setting SDK name to 'sentry.python'
collected 1 item                                                                                                                                          

test_repro.py  [sentry] ERROR: Internal error in sentry_sdk
Traceback (most recent call last):
  File "/Users/krisb/Library/Caches/pypoetry/virtualenvs/repro-sentry-attachment-ds1cNqQ8-py3.9/lib/python3.9/site-packages/sentry_sdk/hub.py", line 388, in capture_exception
    return self.capture_event(event, hint=hint, scope=scope, **scope_args)
  File "/Users/krisb/Library/Caches/pypoetry/virtualenvs/repro-sentry-attachment-ds1cNqQ8-py3.9/lib/python3.9/site-packages/sentry_sdk/hub.py", line 338, in capture_event
    rv = client.capture_event(event, hint, scope)
  File "/Users/krisb/Library/Caches/pypoetry/virtualenvs/repro-sentry-attachment-ds1cNqQ8-py3.9/lib/python3.9/site-packages/sentry_sdk/client.py", line 534, in capture_event
    self.transport.capture_envelope(envelope)
  File "/Users/krisb/Library/Caches/pypoetry/virtualenvs/repro-sentry-attachment-ds1cNqQ8-py3.9/lib/python3.9/site-packages/sentry_sdk/transport.py", line 82, in capture_envelope
    raise NotImplementedError()
NotImplementedError
F

======================================================================== FAILURES =========================================================================
________________________________________________________________________ test_main ________________________________________________________________________

    def test_main():
        with pytest.raises(NameError) as exc_info:
            main.main()
        sentry_sdk.capture_exception(exc_info.value)
        sentry_sdk.Hub.current.flush()
>       assert len(main.events) == 1
E       assert 0 == 1
E        +  where 0 = len([])
E        +    where [] = main.events

test_repro.py:10: AssertionError
-------------------------------------------------------------------- Captured log call --------------------------------------------------------------------
ERROR    sentry_sdk.errors:hub.py:404 Internal error in sentry_sdk
Traceback (most recent call last):
  File "/Users/krisb/Library/Caches/pypoetry/virtualenvs/repro-sentry-attachment-ds1cNqQ8-py3.9/lib/python3.9/site-packages/sentry_sdk/hub.py", line 388, in capture_exception
    return self.capture_event(event, hint=hint, scope=scope, **scope_args)
  File "/Users/krisb/Library/Caches/pypoetry/virtualenvs/repro-sentry-attachment-ds1cNqQ8-py3.9/lib/python3.9/site-packages/sentry_sdk/hub.py", line 338, in capture_event
    rv = client.capture_event(event, hint, scope)
  File "/Users/krisb/Library/Caches/pypoetry/virtualenvs/repro-sentry-attachment-ds1cNqQ8-py3.9/lib/python3.9/site-packages/sentry_sdk/client.py", line 534, in capture_event
    self.transport.capture_envelope(envelope)
  File "/Users/krisb/Library/Caches/pypoetry/virtualenvs/repro-sentry-attachment-ds1cNqQ8-py3.9/lib/python3.9/site-packages/sentry_sdk/transport.py", line 82, in capture_envelope
    raise NotImplementedError()
NotImplementedError
================================================================= short test summary info =================================================================
FAILED test_repro.py::test_main - assert 0 == 1
==================================================================== 1 failed in 0.35s ====================================================================
 [sentry] DEBUG: atexit: got shutdown signal
 [sentry] DEBUG: atexit: shutting down client
```

**Comment by antonpirker** [comment]
Hey @kbakk 
Thanks for the debug output. This tells me that it tries to send the envelope (that is the data structure that attachements are wrapped with) not with the default `HttpTransport` but with the base `Transaport` (that has the send_evnvelope function not implemented.)

Are you changing the transport when initializing the Sentry SDK in your test suite? (there is a `transport` option, see https://docs.sentry.io/platforms/python/configuration/options/#transport-options)

**Comment by antonpirker** [comment]
Hey!
Oh, sorry have not read the description again. 
Yes, this will not work with `events.append` I am afraid, you have to write a more sophisticated transport for checking your attachments.

**Comment by antonpirker** [comment]
As this is not a issue with the SDK, I will close this issue. All the best @kbakk
