### ISSUE TITLE
AioHttp integranion freezes under heavy load

### ISSUE THREAD

**Issue by tonal** [getsentry/sentry-python#204]
My service use [aiohttp](https://github.com/aio-libs/aiohttp) and [aiomysql](https://github.com/aio-libs/aiomysql) under heavy load.
After exclusion, the service freezes for 5-10 seconds.
What is unacceptable.
If I disable the library freezing disappear.

Os Ubuntu 18.04
Python 3.7.1
aiodns==1.1.1
aiohttp==3.4.4
aiomysql==0.0.19
asn1crypto==0.24.0        # via cryptography
async-timeout==3.0.1
attrs==18.2.0             # via aiohttp
cchardet==2.1.4
certifi==2018.11.29       # via sentry-sdk
cffi==1.11.5              # via cryptography
chardet==3.0.4            # via aiohttp
click==7.0
cryptography==2.4.2       # via pymysql
envparse==0.2.0
fastnumbers==2.1.1
idna==2.8                 # via cryptography, yarl
multidict==4.5.2          # via aiohttp, yarl
natsort==5.5.0
pycares==2.3.0            # via aiodns
pycparser==2.19           # via cffi
pyicu==2.2
pymysql==0.9.2            # via aiomysql
python-logstash==0.4.6
pyyaml==3.13
sentry-sdk==0.6.2
six==1.12.0               # via cryptography
urllib3==1.24.1           # via sentry-sdk
uvloop==0.11.3
yarl==1.3.0               # via aiohttp

**Comment by untitaker** [comment]
Thanks, yeah the sdk is not usable like this. Do you know if this is related to any of your dependencies other than aiohttp and sentry-sdk? I have a hard time reproducing this with the information you provided. Do you have a stacktrace of the thread that locks up, any warnings about unused futures, etc?

**Comment by untitaker** [comment]
bump @tonal, what's the status on this?

**Comment by tonal** [comment]
```
2018-12-20 16:44:13,151 INFO       aiohttp.access                 log                                   473: 192.168.0.200 0.020000 [20/дек/2018:09:44:13 +0000] "GET /cat_info/2/1238863?phpid=400200ov8gu7buediau60au6l7 HTTP/1.1" 200 4196 "-" "python-requests/2.20.0"
2018-12-20 16:44:13,212 INFO       aiohttp.access                 log                                   473: 192.168.0.200 0.043000 [20/дек/2018:09:44:13 +0000] "GET /cat_info/f/41405?phpid=e7mr3tckjn9fqea4t2a7gue0t3 HTTP/1.1" 200 1520 "-" "python-requests/2.20.0"
2018-12-20 16:44:13,299 INFO       data_props.data_props          _get_goods_iter                       273: try load good for catid 1238846 (42->42), is_silent: True, mysql_pool.size: 4
2018-12-20 16:44:13,302 INFO       aiohttp.access                 log                                   473: 192.168.0.200 0.088000 [20/дек/2018:09:44:13 +0000] "GET /cat_info/1/1238846?idwhs=113 HTTP/1.1" 200 1060 "-" "python-requests/2.20.0"
2018-12-20 16:44:13,396 WARNING    data_props.data_props          get_cat_info                          434: Для сайта "f" каталога 1261419 есть бренды отсутствующие в таблице фирм: (5275)
2018-12-20 16:44:13,412 INFO       data_props.data_props          _get_goods_iter                       273: try load good for catid 1261419 (473->473), is_silent: True, mysql_pool.size: 4
2018-12-20 16:44:13,414 INFO       aiohttp.access                 log                                   473: 192.168.0.200 0.066000 [20/дек/2018:09:44:13 +0000] "GET /cat_info/f/1261419 HTTP/1.1" 200 5363 "-" "python-requests/2.20.0"
2018-12-20 16:44:13,436 ERROR      root                           _get_goods_iter                       302: opa
Traceback (most recent call last):
  File "/opt/props_service/venv/lib/python3.7/site-packages/aiomysql/connection.py", line 503, in _connect
    await self._request_authentication()
  File "/opt/props_service/venv/lib/python3.7/site-packages/aiomysql/connection.py", line 785, in _request_authentication
    auth_packet = await self._read_packet()
  File "/opt/props_service/venv/lib/python3.7/site-packages/aiomysql/connection.py", line 561, in _read_packet
    packet_header = await self._read_bytes(4)
  File "/opt/props_service/venv/lib/python3.7/site-packages/aiomysql/connection.py", line 598, in _read_bytes
    data = await self._reader.readexactly(num_bytes)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/props_service/data_props/data_props.py", line 274, in _get_goods_iter
    async with self.mysql_pool as mysql:
  File "/opt/props_service/data_props/data_props.py", line 817, in __aenter__
    conn = await pool.acquire()
  File "/opt/props_service/venv/lib/python3.7/site-packages/aiomysql/pool.py", line 135, in _acquire
    await self._fill_free_pool(True)
  File "/opt/props_service/venv/lib/python3.7/site-packages/aiomysql/pool.py", line 181, in _fill_free_pool
    **self._conn_kwargs)
  File "/opt/props_service/venv/lib/python3.7/site-packages/aiomysql/connection.py", line 75, in _connect
    await conn._connect()
  File "/opt/props_service/venv/lib/python3.7/site-packages/aiomysql/connection.py", line 523, in _connect
    self._host) from e
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'pineapple'")
2018-12-20 16:44:51,058 INFO       data_props.data_props          _get_goods_iter                       316: done load 68126 goods: 7 (7)
2018-12-20 16:44:51,073 ERROR      props_service                  log_err                                91: Ошибка при обработке запроса: GET /cat_info/6/66853?phpid=40rpfpso8uanclruogvb7q5bg4&only=is_img
Traceback (most recent call last):
  File "/opt/props_service/data_props/data_props.py", line 817, in __aenter__
    conn = await pool.acquire()
  File "/opt/props_service/venv/lib/python3.7/site-packages/aiomysql/pool.py", line 133, in _acquire
    async with self._cond:
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/asyncio/locks.py", line 92, in __aenter__
    await self.acquire()
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/asyncio/locks.py", line 192, in acquire
    await fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/props_service/data_props/server.py", line 94, in handle_500
    response = await handler(request)
  File "/opt/props_service/data_props/server.py", line 135, in cat_info
    site, cat_id, idwhs=idwhs, only=only_args, is_raw=raw, no_cache=no_cache)
  File "/opt/props_service/data_props/data_props.py", line 415, in get_cat_info
    calc_res = await self._calc_cat_info_goods(site, catid, idwhs, only, {})
  File "/opt/props_service/data_props/data_props.py", line 597, in _calc_cat_info_goods
    site, idgoods, catid=cat_id, all_goods=True)]
  File "/opt/props_service/data_props/data_props.py", line 596, in <listcomp>
    gdescr async for _, gdescr in self._get_goods_iter(
  File "/opt/props_service/data_props/data_props.py", line 274, in _get_goods_iter
    async with self.mysql_pool as mysql:
  File "/opt/props_service/data_props/data_props.py", line 827, in __aenter__
    raise
  File "/opt/props_service/venv/lib/python3.7/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/opt/props_service/venv/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
2018-12-20 16:45:40,969 INFO       data_props.data_props          _get_goods_iter                       316: done load 70422 goods: 10575 (1)
2018-12-20 16:45:40,971 ERROR      aiohttp.server                 log_exception                         319: Error handling request
2018-12-20 16:45:40,972 INFO       aiohttp.access                 log                                   473: 192.168.0.200 88.653000 [20/дек/2018:09:44:12 +0000] "GET /cat_info/6/66853?phpid=40rpfpso8uanclruogvb7q5bg4&only=is_img HTTP/1.1" 504 166 "-" "python-requests/2.20.0"
2018-12-20 16:45:41,001 INFO       data_props.data_props          _get_goods_iter                       316: done load 38339 goods: 567 (9)
2018-12-20 16:45:41,032 INFO       data_props.data_props          _get_goods_iter                       273: try load good for catid 1017561 (140->140), is_silent: True, mysql_pool.size: 2
2018-12-20 16:45:41,034 INFO       aiohttp.access                 log                                   473: 192.168.0.200 0.072000 [20/дек/2018:09:45:40 +0000] "GET /cat_info/1/1017561 HTTP/1.1" 200 3190 "-" "python-requests/2.20.0"
```

**Comment by untitaker** [comment]
Ah yes! I saw this issue in Travis under Python 3.8-dev only, not Python 3.7. And I could not reproduce it locally, so I assumed it was an aiohttp issue with 3.8 specifically (as aiohttp does not have CI set up for Python 3.8)

**Comment by untitaker** [comment]
Could you test whether the testsuite works for you? This would be done by running `tox -e py3.7-sanic-0.8` or `tox -e     py3.7-aiohttp` in the repo root after installing `tox`

**Comment by tonal** [comment]
I ported transports from an old client, but this did not affect the delays.

**Comment by untitaker** [comment]
I have a Ubuntu 18.04 VM. Do you use the `python3.7` package or pyenv or...?

**Comment by tonal** [comment]
I use `pyenv` python 3.7.1

**Comment by tonal** [comment]
```
(sentry-python) tonal@hius2:~/lang/work/python/sentry-python$ venv/bin/tox -e py3.7-aiohttp
py3.7-aiohttp create: /home/tonal/lang/work/python/sentry-python/.tox/py3.7-aiohttp
py3.7-aiohttp installdeps: -rtest-requirements.txt, aiohttp>=3.4.0,<3.5.0, pytest-aiohttp
py3.7-aiohttp develop-inst: /home/tonal/lang/work/python/sentry-python
py3.7-aiohttp installed: aiohttp==3.4.4,apipkg==1.5,async-timeout==3.0.1,atomicwrites==1.2.1,attrs==18.2.0,certifi==2018.11.29,chardet==3.0.4,coverage==4.5.2,execnet==1.5.0,hypothesis==3.69.9,idna==2.8,more-itertools==4.3.0,multidict==4.5.2,pluggy==0.8.0,py==1.7.0,pytest==3.7.3,pytest-aiohttp==0.3.0,pytest-cov==2.6.0,pytest-forked==0.2,pytest-localserver==0.4.1,pytest-xdist==1.23.0,-e git+https://github.com/getsentry/sentry-python.git@b99890600279bad0cf91ee034452681531db67fe#egg=sentry_sdk,six==1.11.0,tox==3.2.1,urllib3==1.24.1,virtualenv==16.1.0,Werkzeug==0.14.1,yarl==1.3.0
py3.7-aiohttp runtests: PYTHONHASHSEED='3600987421'
py3.7-aiohttp runtests: commands[0] | py.test tests/integrations/aiohttp
=============================================== test session starts ===============================================
platform linux -- Python 3.7.1, pytest-3.7.3, py-1.7.0, pluggy-0.8.0
rootdir: /home/tonal/lang/work/python/sentry-python, inifile: pytest.ini
plugins: xdist-1.23.0, localserver-0.4.1, forked-0.2, cov-2.6.0, aiohttp-0.3.0, hypothesis-3.69.9
collected 2 items                                                                                                 

tests/integrations/aiohttp/test_aiohttp.py ..

============================================ 2 passed in 0.18 seconds =============================================
_____________________________________________________ summary _____________________________________________________
  py3.7-aiohttp: commands succeeded
  congratulations :)
```

**Comment by untitaker** [comment]
Hmm, I'm installing this stuff now. What about the sanic one?

**Comment by untitaker** [comment]
nvm I don't think that is related... I'm running out of options to reproduce... Could you try deleting code from your app until you have a small app that still has the same issue?
