### ISSUE TITLE
Incompatibility between `sentry-sdk` and `PyHive`

### ISSUE THREAD

**Issue by pedrorivotti** [getsentry/sentry-python#2071]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.21.0

### Steps to Reproduce

0. Go to temporary folder
1. Create a virtual environment: `python -m venv .venv  # Tested with python 3.9.12`  
2. Activate virtual environment: `source .venv/bin/activate`
3. Add a `requirements.txt` file with the following contents:
```
sentry-sdk==1.21.0
sqlalchemy==1.4.48  # Maximum version supported by PyHive
pyhive[hive,sqlalchemy]==0.6.5
```
4. Install requirements: `pip install -r requirements.txt`
5. Create a `reproduce.py` file with the following contents:
```python
import sentry_sdk
from unittest import mock
from sqlalchemy import create_engine

sentry_sdk.init()

engine = create_engine("hive://")
with mock.patch('pyhive.hive.connect'):
    engine.execute("dummy execution")
``` 
6. Run script: `python reproduce.py`

### Expected Result

The `reproduce.py` script is expected to have no effect. This is the behaviour with `sentry_sdk` `1.20.0`.

### Actual Result

The following exception is raised:
```bash
Traceback (most recent call last):
  File "/home/pm.mendesrivotti/scratch/sentry_hive_issues/test.py", line 9, in <module>
    engine.execute("dummy execution")
  File "<string>", line 2, in execute
  File "/home/pm.mendesrivotti/scratch/sentry_hive_issues/.venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 468, in warned
    return fn(*args, **kwargs)
  File "/home/pm.mendesrivotti/scratch/sentry_hive_issues/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3262, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/pm.mendesrivotti/scratch/sentry_hive_issues/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1370, in execute
    return self._exec_driver_sql(
  File "/home/pm.mendesrivotti/scratch/sentry_hive_issues/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1674, in _exec_driver_sql
    ret = self._execute_context(
  File "/home/pm.mendesrivotti/scratch/sentry_hive_issues/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1847, in _execute_context
    statement, parameters = fn(
  File "/home/pm.mendesrivotti/scratch/sentry_hive_issues/.venv/lib/python3.9/site-packages/sqlalchemy/engine/events.py", line 128, in wrap_before_cursor_execute
    orig_fn(
  File "/home/pm.mendesrivotti/scratch/sentry_hive_issues/.venv/lib/python3.9/site-packages/sentry_sdk/integrations/sqlalchemy.py", line 71, in _before_cursor_execute
    db_system = _get_db_system(conn.engine.name)
  File "/home/pm.mendesrivotti/scratch/sentry_hive_issues/.venv/lib/python3.9/site-packages/sentry_sdk/integrations/sqlalchemy.py", line 114, in _get_db_system
    if "sqlite" in name:
TypeError: a bytes-like object is required, not 'str'
```

# Explanation

SQLAlchemy dialects should include a name, which is normally a `str` (e.g. `sqlite`): https://docs.sqlalchemy.org/en/20/core/internals.html#sqlalchemy.engine.default.DefaultDialect.name
However, PyHive doesn't seem to follow this convention and instead defines its name as `bytes`: https://github.com/dropbox/PyHive/blob/3547bd6cccf963a033928b73c5ed498684335c39/pyhive/sqlalchemy_hive.py#L231

This results in an error when the following code, introduced in `sentry_sdk` `1.21.0` is reached (comparing `str` to `bytes`):
https://github.com/getsentry/sentry-python/blob/1aa5788e0bf7fc4ff0fd35233a860516a122f57d/sentry_sdk/integrations/sqlalchemy.py#L114-L129

While PyHive seems at fault here, that library seems to be currently unsupported (while still useful!). Would you consider adapting the Sentry SDK to protect against the scenario illustrated above?

**Comment by antonpirker** [comment]
Hey @pedrorivotti !

Thanks for reporting this! Should be an easy fix by just converting name with `text_type(name)` (internal helper type)

Do you want to give it a go and submit a PR?

**Comment by sentrivana** [comment]
Hey @pedrorivotti, thanks for the comprehensive issue description, it's much appreciated. I can take a look at this.

**Comment by pedrorivotti** [comment]
Thanks @sentrivana and @antonpirker for the quick fix! Could you give some estimate on when it will be released? It's not urgent; in the meantime my project can keep `sentry_sdk`  pinned to 1.20.0.

**Comment by sentrivana** [comment]
@pedrorivotti There will be a release soon -- likely tomorrow.
