### ISSUE TITLE
Adding user context for RQ doesn't seem to work when having multiple integrations

### ISSUE THREAD

**Issue by stianpr** [getsentry/sentry-python#219]
I assume that it should be possible to define multiple integrations like so?

```PYTHON
sentry_sdk.init(
        dsn='...',
        environment='...',
        integrations=[
            FlaskIntegration(), RqIntegration()
        ]
)
```
This do work when exceptions occur in RQ, but none of the data that we set through configure_scope() like this are sent:

```PYTHON
with configure_scope() as scope:
    scope.user = {'email': 'stian@e5r.no'}
```

We use gevent and Flask-RQ. I debugged the scope inside the RQ process before the exception occurr and the scope has `_name = 'flask'`...

The user context is sent if I don't specify multiple integrations during setup. The code is like this then, but this can't be the way it should be?

```PYTHON
sentry_sdk.init(
        dsn='...',
        environment='...',
        integrations=[
            FlaskIntegration() if 'rq' not in sys.argv else RqIntegration()
        ]
)
```

**Comment by untitaker** [comment]
Hi! I have a lot of questions, I'm sorry for putting it into a list like that:

* Yes, the first codeblock is how it's supposed to be initialized
* In which context are you using gevent? Do you use a special kind of worker with RQ? We only tested with the default forking one. We don't have support for using gunicorn with gevent/eventlet.
* rq does not set a scope name so `_name == 'flask'` is not necessarily unexpected. This was just a dirty hack I did to debug a different issue.
* Where do you call `configure_scope()`? Setting this inside the RQ job should work. But we don't transfer the scope from the request handler into the RQ job.
* What is your version of the SDK? Try upgrading to 0.6.3, it fixes a few concurrency issues with Flask.

**Comment by stianpr** [comment]
Thanks for quick reply!

> * In which context are you using gevent? Do you use a special kind of worker with RQ? We only tested with the default forking one. We don't have support for using gunicorn with gevent/eventlet.

gevent is used on stblibs and psycopg. We don't use gunicorn.

> * Where do you call `configure_scope()`? Setting this inside the RQ job should work. But we don't transfer the scope from the request handler into the RQ job.

Yeah we use `configure_scope()` inside the job.


> * What is your version of the SDK? Try upgrading to 0.6.3, it fixes a few concurrency issues with Flask.

We've tested 0.6.2. So I have to update to the latest version then and test it out. I'll try to do that in this week..

**Comment by untitaker** [comment]
@stianpr any update on this?

**Comment by stianpr** [comment]
@untitaker I will post an update on it this week. Sorry for the delay =/

**Comment by untitaker** [comment]
Closing due to inactivity.

**Comment by stianpr** [comment]
I finally got some time to look at this again (with 0.9.0) and I still don't get it to work. We still have the same setup of the sentry SDK with the two integrations: Flask and RQ. We still use Flask-RQ2 to boot up the server with `flask rq worker --sentry-dsn=""`. The initialization of sentry sdk is handled through flask when the app boots up.

So the issue is that: If I configure the scope inside the job to include the user context I don't get any of that data with the exception that is sent to Sentry. I also know that the `RqIntegration` is partially working because without it, no exception is sent at all (that is one of the things that it does). And the exception logged at sentry contains `rq-job` in additional data.

BUT I do get `RqIntegration` to fully work if I only specify one integration at the time like so: `integrations=[RqIntegration()]`. Is there any known issues with multiple integrations and the use of `configure_scope`?

**Comment by untitaker** [comment]
Do you know *when* `init` is called? Could you enable `debug=True` and tell me if all the additional output for "enabling integration" happens at worker startup or when the first job runs?

**Comment by stianpr** [comment]
I log right after the `init`  is called. You can see the line in the log:  `[INFO]	<root>:  Sentry init called!`.
So it seems that enabling integration is called on bootup and that is before the job is executed. I raise an exception inside the job to trigger sending the exception to Sentry.

```
[DEBUG]	<sentry_sdk.errors>:  Setting up integrations (with default = True)
[DEBUG]	<sentry_sdk.errors>:  Setting up previously not enabled integration argv
[DEBUG]	<sentry_sdk.errors>:  Setting up previously not enabled integration dedupe
[DEBUG]	<sentry_sdk.errors>:  Setting up previously not enabled integration rq
[DEBUG]	<sentry_sdk.errors>:  Setting up previously not enabled integration stdlib
[DEBUG]	<sentry_sdk.errors>:  Setting up previously not enabled integration excepthook
[DEBUG]	<sentry_sdk.errors>:  Setting up previously not enabled integration threading
[DEBUG]	<sentry_sdk.errors>:  Setting up previously not enabled integration modules
[DEBUG]	<sentry_sdk.errors>:  Setting up previously not enabled integration logging
[DEBUG]	<sentry_sdk.errors>:  Setting up previously not enabled integration flask
[DEBUG]	<sentry_sdk.errors>:  Setting up previously not enabled integration atexit
[DEBUG]	<sentry_sdk.errors>:  Enabling integration argv
[DEBUG]	<sentry_sdk.errors>:  Enabling integration dedupe
[DEBUG]	<sentry_sdk.errors>:  Enabling integration rq
[DEBUG]	<sentry_sdk.errors>:  Enabling integration stdlib
[DEBUG]	<sentry_sdk.errors>:  Enabling integration excepthook
[DEBUG]	<sentry_sdk.errors>:  Enabling integration threading
[DEBUG]	<sentry_sdk.errors>:  Enabling integration modules
[DEBUG]	<sentry_sdk.errors>:  Enabling integration logging
[DEBUG]	<sentry_sdk.errors>:  Enabling integration flask
[DEBUG]	<sentry_sdk.errors>:  Enabling integration atexit
[INFO]	<root>:  Sentry init called!
[WARNING]	<flask.app>:  Flask-SocketIO is Running under Werkzeug, WebSocket is not available.
[INFO]	<engineio.server>:  Server initialized for threading.
[DEBUG]	<rq.worker>:  Registering birth of worker 4679d4dc0ee9.1
[INFO]	<rq.worker>:  RQ worker 'rq:worker:4679d4dc0ee9.1' started, version 0.6.0
[INFO]	<rq.worker>:  Cleaning registries for queue: default
[INFO]	<rq.worker>:  
[INFO]	<rq.worker>:  *** Listening on default...
[DEBUG]	<rq.worker>:  Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.



[INFO]	<rq.worker>:  default: <removed function here> (72d0529f-9070-48ee-9f8b-76b8da500939)
[DEBUG]	<rq.worker>:  Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
[DEBUG]	<rq.worker>:  Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
[DEBUG]	<sqlalchemy.pool.QueuePool>:  Created new connection <connection object at 0x7f4fc18d5af8; dsn: '<removed>, closed: 0>
[INFO]	<sqlalchemy.engine.base.Engine>:  select version()
[INFO]	<sqlalchemy.engine.base.Engine>:  {}
[INFO]	<sqlalchemy.engine.base.Engine>:  select current_schema()
[INFO]	<sqlalchemy.engine.base.Engine>:  {}
[INFO]	<sqlalchemy.engine.base.Engine>:  SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
[INFO]	<sqlalchemy.engine.base.Engine>:  {}
[INFO]	<sqlalchemy.engine.base.Engine>:  SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
[INFO]	<sqlalchemy.engine.base.Engine>:  {}
[INFO]	<sqlalchemy.engine.base.Engine>:  show standard_conforming_strings
[INFO]	<sqlalchemy.engine.base.Engine>:  {}
[DEBUG]	<sqlalchemy.pool.QueuePool>:  Connection <connection object at 0x7f4fc18d5af8; dsn: '<removed>, closed: 0> checked out from pool
[INFO]	<sqlalchemy.engine.base.Engine>:  BEGIN (implicit)
[INFO]	<sqlalchemy.engine.base.Engine>: <lots of SQL code>
[DEBUG]	<sqlalchemy.pool.QueuePool>:  Connection <connection object at 0x7f4fc18d5af8; dsn: '<removed>, closed: 0> being returned to pool
[DEBUG]	<sqlalchemy.pool.QueuePool>:  Connection <connection object at 0x7f4fc18d5af8; dsn: '<removed>, closed: 0> rollback-on-return, via agent
[INFO]	<sqlalchemy.engine.base.Engine>:  ROLLBACK
[ERROR]	<rq.worker>:  Exception: Testing RQ jobs with new Sentry SDK
Traceback (most recent call last):
    <removed stack trace code>
    raise Exception("Testing RQ jobs with new Sentry SDK")
Exception: Testing RQ jobs with new Sentry SDK
Traceback (most recent call last):
    <removed stack trace code>
    raise Exception("Testing RQ jobs with new Sentry SDK")
Exception: Testing RQ jobs with new Sentry SDK
[DEBUG]	<sentry_sdk.errors>:  Sending error event [5a222d4ca13a4a49b758c0117b7b9a58] to app.getsentry.com project:<id removed>
[DEBUG]	<urllib3.connectionpool>:  Starting new HTTPS connection (1): app.getsentry.com:443
[INFO]	<sentry_sdk.errors>:  event processor (<function DedupeIntegration.setup_once.<locals>.processor at 0x7ff736a1d8c8>) dropped event ({'tags': {'app': 'v3'}, 'breadcrumbs': [], 'event_id': '34249bd965f54e9eae47dab2c8c595e4', 'extra': {'queue': 'default', 'arguments': ('<removed username>',), 'func': '<removed func name>', 'stack_info': None, 'sys.argv': ['/usr/local/bin/flask', 'rq', 'worker', '--sentry-dsn='], 'kwargs': {}}, 'timestamp': datetime.datetime(2019, 6, 14, 9, 10, 40, 276752), 'exception': {'values': [{'type': 'Exception', 'stacktrace': {'frames': [{'vars': {'queue': Queue('default'), 'self': <flask_rq2.app.RQ.init_backends.<locals>.AppWorker object at 0x7ff73672a668>, 'pipeline': StrictPipeline<ConnectionPool<Connection<host=redis,port=6379,db=0>>>, 'job': Job('9b8d6305-da51-4702-9868-7b3a72e44ad7', enqueued_at=datetime.datetime(2019, 6, 14, 9, 10, 40)), 'started_job_registry': <rq.registry.StartedJobRegistry object at 0x7ff73672abe0>}, 'post_context': ['', '                # Pickle the result in the same try-except block since we need', '                # to use the same exc handling when pickling fails', '                job._result = rv', ''], 'function': 'perform_job', 'context_line': '                    rv = job.perform()', 'abs_path': '/usr/local/lib/python3.4/site-packages/rq/worker.py', 'module': 'rq.worker', 'filename': 'rq/worker.py', 'pre_context': ['        with self.connection._pipeline() as pipeline:', '            started_job_registry = StartedJobRegistry(job.origin, self.connection)', '', '            try:', '                with self.death_penalty_class(job.timeout or self.queue_class.DEFAULT_TIMEOUT):'], 'lineno': 588}, 
{'vars': {'AppJob': <class 'flask_rq2.app.RQ.init_backends.<locals>.AppJob'>, 'self': Job('9b8d6305-da51-4702-9868-7b3a72e44ad7', enqueued_at=datetime.datetime(2019, 6, 14, 9, 10, 40)), 'app': <Flask '<removed path>'>, '__class__': <class 'flask_rq2.app.RQ.init_backends.<locals>.AppJob'>}, 'post_context': ['', '        class AppQueue(BaseQueue):', '            job_class = AppJob', '', '        class AppWorker(BaseWorker):'], 'function': 'perform', 'context_line': '                    return super(AppJob, self).perform()', 'abs_path': '/usr/local/lib/python3.4/site-packages/flask_rq2/app.py', 'module': 'flask_rq2.app', 'filename': 'flask_rq2/app.py', 'pre_context': ['        BaseWorker = import_attribute(self.worker_path)', '', '        class AppJob(BaseJob):', '            def perform(self):', '                with app.app_context():'], 'lineno': 175}, {'vars': {'self': Job('9b8d6305-da51-4702-9868-7b3a72e44ad7', enqueued_at=datetime.datetime(2019, 6, 14, 9, 10, 40))}, 'post_context': ['        finally:', '            assert self.id == _job_stack.pop()', '        return self._result', '', '    def get_ttl(self, default_ttl=None):'], 'function': 'perform', 'context_line': '            self._result = self.func(*self.args, **self.kwargs)', 'abs_path': '/usr/local/lib/python3.4/site-packages/rq/job.py', 'module': 'rq.job', 'filename': 'rq/job.py', 'pre_context': ['        """Invokes the job function with the job arguments."""', '        self.connection.persist(self.key)', '        self.ttl = -1', '        _job_stack.push(self.id)', '        try:'], 'lineno': 498}, {'vars': {'f': <function <removed func name> at 0x7ff73b20c9d8>, 'args': ('<removed username>',), 'kwargs': {}}, 'post_context': ['', '    return decorated_function', '', '', 'def consumes(*content_types):'], 'function': 'decorated_function', 'context_line': '        return f(*args, **kwargs)', 'abs_path': '<removed file path>', 'module': '<removed module>', 'filename': '<removed filename>', 'pre_context': ['', "        g.username = kwargs.get('username') or args[0]", '', '        set_sentry_context()', ''], 'lineno': 34}, 
{'vars': {'username': '<removed username>', 'scope': <Scope id=0x7ff736729f78 name=flask>}, 'post_context': ['    connection = db.session.connection()', '    connection.execute(', "        '<remved sql code>'", '    )', '    connection.execute('], 'function': '<removed func name>', 'context_line': '    raise Exception("Testing RQ jobs with new Sentry SDK")', 'abs_path': '<removed abs_path>', 'module': '<removed module>', 'filename': '<removed filename>', 'pre_context': ['    """', '', '    with configure_scope() as scope:', "        scope.user = {'email': 'stian@e5r.no'}", ''], 'lineno': 26}]}, 'module': None, 'mechanism': {'handled': True, 'type': 'logging'}, 'value': 'Testing RQ jobs with new Sentry SDK'}]}, 'logentry': {'params': (), 'message': 'Exception: Testing RQ jobs with new Sentry SDK\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.4/site-packages/rq/worker.py", line 588, in perform_job\n    rv = job.perform()\n  File "/usr/local/lib/python3.4/site-packages/flask_rq2/app.py", line 175, in perform\n    return super(AppJob, self).perform()\n  File "/usr/local/lib/python3.4/site-packages/rq/job.py", line 498, in perform\n    self._result = self.func(*self.args, **self.kwargs)\n  File "<remved file path>", line 34, in decorated_function\n    return f(*args, **kwargs)\n  File "<removed file path>", line 26, in <removed func name>\n    raise Exception("Testing RQ jobs with new Sentry SDK")\nException: Testing RQ jobs with new Sentry SDK\n'}, 'logger': 'rq.worker', 'level': 'error'})
[DEBUG]	<rq.worker>:  Invoking exception handler <bound method AppWorker.move_to_failed_queue of <flask_rq2.app.RQ.init_backends.<locals>.AppWorker object at 0x7f4fc16485f8>>
[WARNING]	<rq.worker>:  Moving job to 'failed' queue
[DEBUG]	<sentry_sdk.errors>:  Flushing HTTP transport
[DEBUG]	<sentry_sdk.errors>:  background worker got flush request
[DEBUG]	<sentry_sdk.errors>:  0 event(s) pending on flush
[DEBUG]	<urllib3.connectionpool>:  https://app.getsentry.com:443 "POST /api/<id removed>/store/ HTTP/1.1" 200 41
[DEBUG]	<sentry_sdk.errors>:  background worker flushed
[DEBUG]	<rq.worker>:  Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
[INFO]	<rq.worker>:  
[INFO]	<rq.worker>:  *** Listening on default...
[DEBUG]	<rq.worker>:  Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
```

Does this give you anything?

**Comment by untitaker** [comment]
Sorry, I can't make anything out of this. Could you share an issue that is missing user context and also paste the code of that job?

**Comment by stianpr** [comment]
@untitaker I'll make a pull request instead. It might be easier for everyone that I use a fork and try to debug to find the issue. 

I think the issue might have something to do with how "shared" scope works between the different integrations. Hopefully I will find out by the end of this week. I'll let you know of any updates.

**Comment by stianpr** [comment]
Ok I managed to debug some more now and I added a `_name_` on the scope that the RqIntegration uses to see that I'm not accessing the correct scope when calling `configure_scope()`  inside the job.


This is a dump of the scope i get from within `configure_scope()` context inside the job:
``` 
<Scope id=0x7fbee96c1168 name=flask>
``` 

This is a dump of the scope stack within `configure_scope()` context inside the same job:
``` 
[
(<sentry_sdk.client._Client object at 0x7fbee9754c50>, <Scope id=0x7fbef4a11f78 name=None>),
(<sentry_sdk.client._Client object at 0x7fbee9754c50>, <Scope id=0x7fbef697a948 name=flask>),
(<sentry_sdk.client._Client object at 0x7fbee9754c50>, <Scope id=0x7fbee9707678 name=rq>),
(<sentry_sdk.client._Client object at 0x7fbee9754c50>, <Scope id=0x7fbee96c1168 name=flask>)
]
```

If I then set `scope.user = {'id': 'username'}` inside this context, I get this output from the scope class:

From line 98 in scope.py
```
SETTING USER <Scope id=0x7fbee96c1168 name=flask> {'id': 'username'}
```

When the job is executing and failing due to an exception I log accessing the scope to retrieve the user:

From line 200 in scope.py:
```
ACCESSING USER <Scope id=0x7fbee9707678 name=rq> None None
```
So it's clear that it doesn't find a user before it is sending the log to Sentry.


So my question to you @untitaker is:
1. How are multiple scopes suppose to work?
2. I see that RqIntegration uses `push_scope()` is that correct and how can I access that scope inside the job to be able to set the user? Isn't configure_scope suppose to work this out?

I'm willing to make a patch, but I need to understand how the scopes should work first.

**Comment by untitaker** [comment]
@stianpr it works exactly how you assumed it works before you started to investigate this :) `configure_scope` should use the last item in the scope list, but that list item seems to be completely wrong in your case.

Could you try upgrading to 0.9.1? I think this comment might be relevant: https://github.com/getsentry/sentry-python/commit/f2d563798eb002ca2d22ee6e44467b943298d223

But even then I have no idea why your (gunicorn web workers?) affects your RQ workers. Do your RQ workers use gevent as well?

**Comment by stianpr** [comment]
> Could you try upgrading to 0.9.1? I think this comment might be relevant: [f2d5637](https://github.com/getsentry/sentry-python/commit/f2d563798eb002ca2d22ee6e44467b943298d223)

I'm already on 0.9.2 now while testing.


> But even then I have no idea why your (gunicorn web workers?) affects your RQ workers. Do your RQ workers use gevent as well?

We use gevent there also yeah. Could that be the case? I can try to disable it and see.

**Comment by untitaker** [comment]
Are you using a different RQ worker class than the default one? We ran zero
tests with any other package that is out there.

**Comment by stianpr** [comment]
> Are you using a different RQ worker class than the default one? We ran zero tests with any other package that is out there.

We're using the default that  [Flask-RQ2](https://github.com/rq/Flask-RQ2/blob/17.0/src/flask_rq2/app.py#L49) is providing, and that is `rq.worker.Worker`.

**Comment by untitaker** [comment]
Okay, that worker class sounds fine. Could you still try to disable
gevent/eventlet *everywhere* and see if it fixes any of the issues?

**Comment by stianpr** [comment]
@untitaker sorry for the huge delay. I'm trying out the new version now 0.13.4. I'll report back with status on this issue.

**Comment by untitaker** [comment]
I'm closing this again as the investigation along this is going very slowly and we're on 0.19 by now.
