### ISSUE TITLE
Cannot send event to Sentry with serverless_sdk: send_envelope_wrapper internal error

### ISSUE THREAD

**Issue by fafrd** [getsentry/sentry-python#2216]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.26.0

### Steps to Reproduce

I'm running a basic aws lambda using Serverless framework and I can't seem to send any messages to Sentry. This code works just fine locally, but I get an internal error when running on AWS Lambda.

```python
import sentry_sdk
from sentry_sdk.integrations.aws_lambda import AwsLambdaIntegration

sentry_sdk.init(
    dsn="https://<my-dsn>",
    debug=True,
    integrations=[
        AwsLambdaIntegration(timeout_warning=True),
    ],
    traces_sample_rate=1.0,
)

def handler(event, context):
    from sentry_sdk import capture_message
    capture_message("testing sentry 123")
```

### Expected Result

Received event in sentry.

### Actual Result

```
2023-06-29 23:32:44,473 - sentry_sdk.errors - DEBUG - Sending envelope [envelope with 1 items (internal)] project:4505444184293376 host:o1112958.ingest.sentry.io
[sentry] ERROR: Internal error in sentry_sdk
Traceback (most recent call last):
File "/var/task/sentry_sdk/transport.py", line 492, in send_envelope_wrapper
self._send_envelope(envelope)
File "/var/task/sentry_sdk/transport.py", line 388, in _send_envelope
self._send_request(
File "/var/task/sentry_sdk/transport.py", line 231, in _send_request
response = self._pool.request(
File "/var/task/urllib3/request.py", line 78, in request
return self.request_encode_body(
File "/var/task/urllib3/request.py", line 170, in request_encode_body
return self.urlopen(method, url, **extra_kw)
File "/var/task/urllib3/poolmanager.py", line 376, in urlopen
response = conn.urlopen(method, u.request_uri, **kw)
File "/var/task/serverless_sdk/vendor/wrapt/wrappers.py", line 610, in __call__
return self._self_wrapper(self.__wrapped__, self._self_instance,
File "/var/task/serverless_sdk/__init__.py", line 568, in wrapper
raise e
File "/var/task/serverless_sdk/__init__.py", line 563, in wrapper
response = wrapped(*args, **kwargs)
File "/opt/python/sls_sdk/lib/instrumentation/wrapper.py", line 16, in _target_method
return self.target_method(
File "/opt/python/sls_sdk/lib/instrumentation/http.py", line 404, in _patched_call
self._capture_request_body(trace_span, body)
File "/opt/python/sls_sdk/lib/instrumentation/http.py", line 104, in _capture_request_body
length = len(decoded)
TypeError: object of type 'NoneType' has no len()
```

**Comment by fafrd** [comment]
Appears to be an issue on the Serverless side. Closing in favor of https://github.com/serverless/console/issues/828
