### ISSUE TITLE
Error when explicitly passing `trace_configs=None` to `aiohttp.ClientSession`

### ISSUE THREAD

**Issue by wookie184** [getsentry/sentry-python#2233]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.27.0

### Steps to Reproduce

With the `aiohttp` integration, use `aiohttp.ClientSession` with `trace_configs` explicitly passed as `None`
```
import asyncio
import sentry_sdk
import aiohttp

sentry_sdk.init()

async def main():
    async with aiohttp.ClientSession(trace_configs=None) as session:
        pass

asyncio.run(main())
```

### Expected Result

No error (as in 1.26.0)

### Actual Result

An error is raised:
```python
Traceback (most recent call last):
  File "C:\Users\wookie184\Documents\GitHub\bot\hello.py", line 11, in <module>
    asyncio.run(main())
  File "C:\Users\wookie184\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wookie184\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wookie184\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\wookie184\Documents\GitHub\bot\hello.py", line 8, in main
    async with aiohttp.ClientSession(trace_configs=None) as session:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wookie184\AppData\Local\pypoetry\Cache\virtualenvs\bot-hu2rt1Uv-py3.11\Lib\site-packages\sentry_sdk\integrations\aiohttp.py", line 186, in init        
    client_trace_configs = list(kwargs.get("trace_configs", ()))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

**Comment by sentrivana** [comment]
Hey @wookie184, thanks for reporting, this is already fixed on our main branch thanks to https://github.com/getsentry/sentry-python/pull/2230, we'll cut a release with the fix soon.

**Comment by sentrivana** [comment]
@wookie184 Out now in [1.27.1](https://github.com/getsentry/sentry-python/releases/tag/1.27.1) :)

**Comment by wookie184** [comment]
> @wookie184 Out now in [1.27.1](https://github.com/getsentry/sentry-python/releases/tag/1.27.1) :)

Nice, thanks!!
