### ISSUE TITLE
Event is dropped if Exception occurs during `object_to_json`

### ISSUE THREAD

**Issue by leotrubach** [getsentry/sentry-python#238]
This may happen if Sequence is Django queryset that has incorrect field in `filter()` expressions.

**Comment by untitaker** [comment]
Could you provide a stacktrace?

**Comment by leotrubach** [comment]
@untitaker I have to hide some significant information as I'm not allowed to disclose it, but it still should be informative and give the idea of what occurs:

```
Jan 18 02:09:16am app web.1 Traceback (most recent call last):
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
Jan 18 02:09:16am app web.1 response = handler(request, *args, **kwargs)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/mixins.py", line 42, in list
Jan 18 02:09:16am app web.1 page = self.paginate_queryset(queryset)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/generics.py", line 173, in paginate_queryset
Jan 18 02:09:16am app web.1 return self.paginator.paginate_queryset(queryset, self.request, view=self)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/pagination.py", line 216, in paginate_queryset
Jan 18 02:09:16am app web.1 return list(self.page)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/core/paginator.py", line 143, in __len__
Jan 18 02:09:16am app web.1 return len(self.object_list)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 250, in __len__
Jan 18 02:09:16am app web.1 self._fetch_all()
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _fetch_all
Jan 18 02:09:16am app web.1 self._result_cache = list(self._iterable_class(self))
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 54, in __iter__
Jan 18 02:09:16am app web.1 results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1052, in execute_sql
Jan 18 02:09:16am app web.1 sql, params = self.as_sql()
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 449, in as_sql
Jan 18 02:09:16am app web.1 extra_select, order_by, group_by = self.pre_sql_setup()
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 51, in pre_sql_setup
Jan 18 02:09:16am app web.1 order_by = self.get_order_by()
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 315, in get_order_by
Jan 18 02:09:16am app web.1 field, self.query.get_meta(), default_order=asc))
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 668, in find_ordering_name
Jan 18 02:09:16am app web.1 field, targets, alias, joins, path, opts, transform_function = self._setup_joins(pieces, opts, alias)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 698, in _setup_joins
Jan 18 02:09:16am app web.1 field, targets, opts, joins, path, transform_function = self.query.setup_joins(pieces, opts, alias)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1473, in setup_joins
Jan 18 02:09:16am app web.1 names[:pivot], opts, allow_many, fail_on_missing=True,
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1389, in names_to_path
Jan 18 02:09:16am app web.1 "Choices are: %s" % (name, ", ".join(available)))
Jan 18 02:09:16am app web.1 django.core.exceptions.FieldError: Cannot resolve keyword 'foo' into field. Choices are: bar1, bar2, ....


Jan 18 02:09:16am app web.1 58 <190>1 2019-01-17T20:09:16.692952+00:00 host app web.1 -
Jan 18 02:09:16am app web.1 During handling of the above exception, another exception occurred:
Jan 18 02:09:16am app web.1 58 <190>1 2019-01-17T20:09:16.692954+00:00 host app web.1 -
Jan 18 02:09:16am app web.1 Traceback (most recent call last):
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
Jan 18 02:09:16am app web.1 response = get_response(request)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
Jan 18 02:09:16am app web.1 response = self.process_exception_by_middleware(e, request)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
Jan 18 02:09:16am app web.1 response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
Jan 18 02:09:16am app web.1 return view_func(*args, **kwargs)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
Jan 18 02:09:16am app web.1 return self.dispatch(request, *args, **kwargs)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
Jan 18 02:09:16am app web.1 response = self.handle_exception(exc)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/rest_framework/views.py", line 452, in handle_exception
Jan 18 02:09:16am app web.1 response = exception_handler(exc, context)
Jan 18 02:09:16am app web.1 File "/app/apps/commons/exceptions.py", line 49, in api_exception_handler
Jan 18 02:09:16am app web.1 capture_exception(exc)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/api.py", line 47, in capture_exception
Jan 18 02:09:16am app web.1 return hub.capture_exception(error)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/hub.py", line 254, in capture_exception
Jan 18 02:09:16am app web.1 event, hint = event_from_exception(exc_info, client_options=client.options)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 520, in event_from_exception
Jan 18 02:09:16am app web.1 exc_info, client_options, mechanism
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 436, in exceptions_from_error_tuple
Jan 18 02:09:16am app web.1 exc_type, exc_value, tb, client_options, mechanism
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 426, in single_exception_from_error_tuple
Jan 18 02:09:16am app web.1 "stacktrace": stacktrace_from_traceback(tb, with_locals),
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 383, in stacktrace_from_traceback
Jan 18 02:09:16am app web.1 for tb in iter_stacks(tb)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 383, in <listcomp>
Jan 18 02:09:16am app web.1 for tb in iter_stacks(tb)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 373, in serialize_frame
Jan 18 02:09:16am app web.1 rv["vars"] = extract_locals(frame)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 323, in extract_locals
Jan 18 02:09:16am app web.1 rv[str(key)] = object_to_json(value)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 317, in object_to_json
Jan 18 02:09:16am app web.1 return _walk(obj, 0)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 312, in _walk
Jan 18 02:09:16am app web.1 return [_walk(x, depth + 1) for x in obj]
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 312, in <listcomp>
Jan 18 02:09:16am app web.1 return [_walk(x, depth + 1) for x in obj]
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/_collections_abc.py", line 883, in __iter__
Jan 18 02:09:16am app web.1 v = self[i]
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/core/paginator.py", line 151, in __getitem__
Jan 18 02:09:16am app web.1 self.object_list = list(self.object_list)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 268, in __iter__
Jan 18 02:09:16am app web.1 self._fetch_all()
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _fetch_all
Jan 18 02:09:16am app web.1 self._result_cache = list(self._iterable_class(self))
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 54, in __iter__
Jan 18 02:09:16am app web.1 results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1052, in execute_sql
Jan 18 02:09:16am app web.1 sql, params = self.as_sql()
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 449, in as_sql
Jan 18 02:09:16am app web.1 extra_select, order_by, group_by = self.pre_sql_setup()
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 51, in pre_sql_setup
Jan 18 02:09:16am app web.1 order_by = self.get_order_by()
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 315, in get_order_by
Jan 18 02:09:16am app web.1 field, self.query.get_meta(), default_order=asc))
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 668, in find_ordering_name
Jan 18 02:09:16am app web.1 field, targets, alias, joins, path, opts, transform_function = self._setup_joins(pieces, opts, alias)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 698, in _setup_joins
Jan 18 02:09:16am app web.1 field, targets, opts, joins, path, transform_function = self.query.setup_joins(pieces, opts, alias)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1473, in setup_joins
Jan 18 02:09:16am app web.1 names[:pivot], opts, allow_many, fail_on_missing=True,
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1389, in names_to_path
Jan 18 02:09:16am app web.1 "Choices are: %s" % (name, ", ".join(available)))
Jan 18 02:09:16am app web.1 django.core.exceptions.FieldError: Cannot resolve keyword 'foo' into field. Choices are: bar1, bar2, ....


Jan 18 02:09:16am app web.1 58 <190>1 2019-01-17T20:09:16.693070+00:00 host app web.1 -
Jan 18 02:09:16am app web.1 During handling of the above exception, another exception occurred:
Jan 18 02:09:16am app web.1 58 <190>1 2019-01-17T20:09:16.693073+00:00 host app web.1 -
Jan 18 02:09:16am app web.1 Traceback (most recent call last):
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
Jan 18 02:09:16am app web.1 response = get_response(request)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/utils/deprecation.py", line 91, in __call__
Jan 18 02:09:16am app web.1 response = response or self.get_response(request)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 36, in inner
Jan 18 02:09:16am app web.1 response = response_for_exception(request, exc)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 89, in response_for_exception
Jan 18 02:09:16am app web.1 signals.got_request_exception.send(sender=None, request=request)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
Jan 18 02:09:16am app web.1 for receiver in self._live_receivers(sender)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
Jan 18 02:09:16am app web.1 for receiver in self._live_receivers(sender)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 154, in _got_request_exception
Jan 18 02:09:16am app web.1 mechanism={"type": "django", "handled": False},
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 520, in event_from_exception
Jan 18 02:09:16am app web.1 exc_info, client_options, mechanism
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 436, in exceptions_from_error_tuple
Jan 18 02:09:16am app web.1 exc_type, exc_value, tb, client_options, mechanism
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 426, in single_exception_from_error_tuple
Jan 18 02:09:16am app web.1 "stacktrace": stacktrace_from_traceback(tb, with_locals),
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 383, in stacktrace_from_traceback
Jan 18 02:09:16am app web.1 for tb in iter_stacks(tb)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 383, in <listcomp>
Jan 18 02:09:16am app web.1 for tb in iter_stacks(tb)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 373, in serialize_frame
Jan 18 02:09:16am app web.1 rv["vars"] = extract_locals(frame)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 323, in extract_locals
Jan 18 02:09:16am app web.1 rv[str(key)] = object_to_json(value)
Jan 18 02:09:16am app web.1 File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/utils.py", line 317, in object_to_json
Jan 18 02:09:16am app web.1 return _walk(obj, 0)
```
