### ISSUE TITLE
Sentry doesn't report errors in the traces_sampler function

### ISSUE THREAD

**Issue by brettdh** [getsentry/sentry-python#2582]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.38.0

### Steps to Reproduce

1. Call `sentry_sdk.init` with a `traces_sampler=` kwarg of a function that raises an exception.
2. Perform a request (in my case: HTTP request to Django app running in AWS Lambda)

### Expected Result

Error in sampling function is reported to Sentry

### Actual Result

Unhandled error occurs (found in logs), but no Sentry issue is created.

```python
TypeError: expected string or bytes-like object

  File "/var/task/sentry_sdk/integrations/aws_lambda.py", line 151, in sentry_handler
    with hub.start_transaction(
  File "/var/task/sentry_sdk/hub.py", line 572, in start_transaction
    transaction._set_initial_sampling_decision(sampling_context=sampling_context)
  File "/var/task/sentry_sdk/tracing.py", line 841, in _set_initial_sampling_decision
    options["traces_sampler"](sampling_context)
  File "/var/task/myapp/config/settings/base.py", line 263, in my_traces_sampler
    if metrics_api_rx.search(path):
```

where `path` was `None`.

**Comment by antonpirker** [comment]
Hey @brettdh thanks for reporting this. 
We will have a look.

**Comment by sl0thentr0py** [comment]
by design, we do not report exceptions in SDK code, you should see it in logs if you add`debug=True`

**Comment by brettdh** [comment]
@sl0thentr0py can you elaborate on "by design"? It seems like an observability gap; i.e. an exception in the sampling function  can quietly cause all requests to fail. 

Further, the sampling function was a bit hard to write, due to the context object format being largely undocumented, and this makes me all the more nervous that I may have missed some corner case - which is why I wanted to make sure I still have error reporting for the sampling function (which is my code, not SDK code).

**Comment by sl0thentr0py** [comment]
for one - if we self-report, we can end up in a busy loop of reporting.
we can make the experience a bit better here and maybe use `logger.warn` or `logger.error` so that it's clear to users.

**Comment by sl0thentr0py** [comment]
ok actually nvm i just tried it out and I did get an issue in sentry 
```python
import sentry_sdk


def fail(_context):
    1 / 0


sentry_sdk.init(debug=True, traces_sampler=fail)

with sentry_sdk.start_transaction(name="traces sampler fail"):
    pass

sentry_sdk.flush()
```

<img width="1056" alt="image" src="https://github.com/getsentry/sentry-python/assets/6536764/953517d4-435b-4842-8644-8cc2fb34d1a1">

**Comment by brettdh** [comment]
Hmm. I got bit by this again today - due to a real `ZeroDivisionError`, coincidentally - and I didn't notice until I dug into logs.

Oddly, I did see a `ServerlessTimeoutWarning` in Sentry, and jumping to the logs in Cloudwatch linked from that error in Sentry, that's how I found the `ZeroDivisionError`:

```
  | 2023-12-14T19:30:49.641Z | START RequestId: d5d126c4-8cf3-4ae3-b931-14a7167dbea4 Version: $LATEST
  | 2023-12-14T19:30:49.645Z | Exception in thread Thread-4169:
  | 2023-12-14T19:30:49.645Z | Traceback (most recent call last):
  | 2023-12-14T19:30:49.645Z |   File "/var/lang/lib/python3.9/threading.py", line 980, in _bootstrap_inner
  | 2023-12-14T19:30:49.645Z |     self.run()
  | 2023-12-14T19:30:49.645Z |   File "/var/task/sentry_sdk/integrations/threading.py", line 72, in run
  | 2023-12-14T19:30:49.645Z |     reraise(*_capture_exception())
  | 2023-12-14T19:30:49.645Z |   File "/var/task/sentry_sdk/_compat.py", line 115, in reraise
  | 2023-12-14T19:30:49.645Z |     raise value
  | 2023-12-14T19:30:49.645Z |   File "/var/task/sentry_sdk/integrations/threading.py", line 70, in run
  | 2023-12-14T19:30:49.645Z |     return old_run_func(self, *a, **kw)
  | 2023-12-14T19:30:49.645Z |   File "/var/task/sentry_sdk/utils.py", line 1392, in run
  | 2023-12-14T19:30:49.645Z |     raise ServerlessTimeoutWarning(
  | 2023-12-14T19:30:49.646Z | sentry_sdk.utils.ServerlessTimeoutWarning: WARNING : Function is expected to get timed out. Configured timeout duration = 29 seconds.
  | 2023-12-14T19:30:49.649Z | [ERROR] ZeroDivisionError: float division by zero 
  Traceback (most recent call last):
   File "/var/task/sentry_sdk/integrations/aws_lambda.py", line 151, in sentry_handler
     with hub.start_transaction(
   File "/var/task/sentry_sdk/hub.py", line 572, in start_transaction
     transaction._set_initial_sampling_decision(sampling_context=sampling_context)
   File "/var/task/sentry_sdk/tracing.py", line 841, in _set_initial_sampling_decision
     options["traces_sampler"](sampling_context)
   File "/var/task/myproj/config/settings/base.py", line 340, in traces_sampler
     rate = 1.0 / Host.objects.filter(up=True).count()
  | 2023-12-14T19:30:49.677Z | END RequestId: d5d126c4-8cf3-4ae3-b931-14a7167dbea4
  | 2023-12-14T19:30:49.677Z | REPORT RequestId: d5d126c4-8cf3-4ae3-b931-14a7167dbea4 Duration: 35.35 ms Billed Duration: 36 ms Memory Size: 1024 MB Max Memory Used: 248 MB
```

**Comment by sentrivana** [comment]
We should properly define the expected behavior when a custom `traces_sampler` (or `before_send{_transaction}`, or `error_sampler`, or any other hook) throws an exception. Currently we usually log the error, but apparently in some cases the exception also gets intercepted by `excepthook` and makes it to Sentry. If that's how it should be, then this is a bug in the AWS Lambda integration since it apparently doesn't do that.

FWIW I do think we should make this sort of errors easier to discover, or at least make it clearer how to notice them. We've had some cases recently where folks were confused why there were no transactions appearing in Sentry and it took a long time to trace it back to a faulty `before_send_transaction`. Internal SDK exceptions should never affect the user's app, but these custom hooks are not SDK code.

**Comment by sentrivana** [comment]
Hey @brettdh, I know it's been some time, but if you're still up for some debugging, could you get us an example to reproduce? I also get the error from my `traces_sampler` sent to Sentry, so I'd like to understand what's different about your setup. Maybe the SDK doesn't have enough time to send the event? If you enable `debug=True` in your `init()`, the SDK should log what happens at shutdown and we could see if this is the case.

**Comment by brettdh** [comment]
@sentrivana I've actually changed jobs since I opened this, so I no longer have access to the environment where I originally observed this (AWS Lambda via Serverless Framework). If there's something specific to that environment that's causing this (maybe flush isn't happening in time, for instance), maybe @roanmh  can help.

**Comment by sentrivana** [comment]
Thanks @Roanmh! I can reproduce this. If you change the `traces_sampler` to be a standalone function instead of a lambda function, does the error get reported?

**Comment by szokeasaurusrex** [comment]
Hi all, after discussing with our wider SDK team, @cleptric pointed out that it is an intentional design decision that Sentry SDKs do not report errors in SDK callbacks such as the `traces_sampler` function.

Therefore, we are closing this issue as not planned. The current behavior is the expected behavior.

**Comment by brettdh** [comment]
@szokeasaurusrex That fact has been part of the discussion [since the start](https://github.com/getsentry/sentry-python/issues/2582#issuecomment-1851975435), and it's still not ideal behavior, for the reasons I already mentioned. I'm not sure why that means that the issue is being closed today.

I'd still like to see a better way to discover errors in the `trace_sampler` function, for [the reasons I already mentioned](https://github.com/getsentry/sentry-python/issues/2582#issuecomment-1851984740).

**Comment by szokeasaurusrex** [comment]
@brettdh Let me address the two points you brought up separately.

> That fact has been part of the discussion since the start [...] I'm not sure why that means that the issue is being closed today.

You are totally right here. As soon as we identified that it is expected behavior for the SDK not to report errors from the `traces_sampler` function to Sentry, we should have immediately closed this issue as "not planned." I am not sure why we did not close this issue at the time, but I would like to sincerely apologize to you for having kept this issue open for so long. We owe it to our users to maintain a transparent issue backlog, and an important aspect of that is to clearly communicate when we will not implement a change that our users have requested.

By closing this issue today, we are correcting our previous mistake and making it clear to all of our users that the Sentry SDK is not meant to capture issues occurring in the `traces_sampler` function.

> I'd still like to see a better way to discover errors in the trace_sampler function, for the reasons I already mentioned.

I think the actual underlying bug here, which we can and should quickly fix, is that an error in the `traces_sampler` function can  crash the app. We should instead handle these errors gracefully by logging them and then continuing as if no `traces_sampler` function had been provided. I'll open a new issue for this and prioritize fixing this.

Again, I am truly sorry that it took so long to get a resolution here. We will try our best to do better going forward.
