### ISSUE TITLE
error logging requests

### ISSUE THREAD

**Issue by ekimia** [getsentry/sentry-python#262]
We use the json log formatter https://github.com/madzak/python-json-logger and we are hitting this error when hitting an endpoint that returns a 404. Assuming the same will happen for other requests sentry is trying to get too.

```
txechart-7567fc46c4-k6stc txechart {"message": "i got this! b6f3a3dd-2fe9-40ca-98c3-eeefe1a4d968", "time": "2019-02-12T20:54:58.424967"}
txechart-7567fc46c4-k6stc txechart --- Logging error ---
txechart-7567fc46c4-k6stc txechart Traceback (most recent call last):
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
txechart-7567fc46c4-k6stc txechart     msg = self.format(record)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
txechart-7567fc46c4-k6stc txechart     return fmt.format(record)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/json_log_formatter/__init__.py", line 71, in format
txechart-7567fc46c4-k6stc txechart     return self.to_json(mutated_record)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/json_log_formatter/__init__.py", line 79, in to_json
txechart-7567fc46c4-k6stc txechart     return self.json_lib.dumps(record)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
txechart-7567fc46c4-k6stc txechart     return _default_encoder.encode(obj)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
txechart-7567fc46c4-k6stc txechart     chunks = self.iterencode(o, _one_shot=True)
txechart-7567fc46c4-k6stc txechart-7567fc46c4-k6stc cloudsql-proxy 2019/02/12 20:54:58 Client closed local connection on 127.0.0.1:5432
txechart   File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
txechart-7567fc46c4-k6stc txechart     return _iterencode(o, 0)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
txechart-7567fc46c4-k6stc txechart     o.__class__.__name__)
txechart-7567fc46c4-k6stc txechart TypeError: Object of type 'WSGIRequest' is not JSON serializable
txechart-7567fc46c4-k6stc txechart Call stack:
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
txechart-7567fc46c4-k6stc txechart     result = self._run(*self.args, **self.kwargs)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
txechart-7567fc46c4-k6stc txechart     return handle(*args_tuple)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/async.py", line 56, in handle
txechart-7567fc46c4-k6stc txechart     self.handle_request(listener_name, req, client, addr)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 152, in handle_request
txechart-7567fc46c4-k6stc txechart     super(GeventWorker, self).handle_request(*args)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/async.py", line 107, in handle_request
txechart-7567fc46c4-k6stc txechart     respiter = self.wsgi(environ, resp.start_response)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/django/__init__.py", line 95, in sentry_patched_wsgi_handler
txechart-7567fc46c4-k6stc txechart     environ, start_response
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/wsgi.py", line 69, in __call__
txechart-7567fc46c4-k6stc txechart     rv = self.app(environ, start_response)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/django/__init__.py", line 94, in <lambda>
txechart-7567fc46c4-k6stc txechart     return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
txechart-7567fc46c4-k6stc txechart     response = self.get_response(request)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/django/__init__.py", line 114, in sentry_patched_get_response
txechart-7567fc46c4-k6stc txechart     return old_get_response(self, request)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 152, in get_response
txechart-7567fc46c4-k6stc txechart     extra={'status_code': 404, 'request': request},
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/logging/__init__.py", line 1320, in warning
txechart-7567fc46c4-k6stc txechart     self._log(WARNING, msg, args, **kwargs)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/logging/__init__.py", line 1444, in _log
txechart-7567fc46c4-k6stc txechart     self.handle(record)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/logging/__init__.py", line 1454, in handle
txechart-7567fc46c4-k6stc txechart     self.callHandlers(record)
txechart-7567fc46c4-k6stc txechart   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/logging.py", line 58, in sentry_patched_callhandlers
txechart-7567fc46c4-k6stc txechart     return old_callhandlers(self, record)
txechart-7567fc46c4-k6stc txechart Message: 'Not Found: %s'
txechart-7567fc46c4-k6stc txechart Arguments: ('/internal/v1/merchants/b6f3a3dd-2fe9-40ca-98c3-eeefe1a4d968',)
txechart-7567fc46c4-k6stc txechart 10.7.0.32 - - [12/Feb/2019:20:54:58 +0000] "GET /internal/v1/merchants/b6f3a3dd-2fe9-40ca-98c3-eeefe1a4d968 HTTP/1.1" 404 47 "-" "Paw/3.1.8 (Macintosh; OS X/10.14.0) GCDHTTPRequest"
```

**Comment by untitaker** [comment]
Are you sure this has anything to do with the Python SDK? We don't modify any log records, and this particular log record seems to be created by Django and fails formatting in python-json-logger.

You also linked to the wrong library. Judging by the code in the stacktrace, you're using this: https://github.com/marselester/json-log-formatter

This doesn't seem to have any code set up to deal with non-JSON-serializable objects (such as a WSGI request), which IMO is a bug in that package.

**Comment by untitaker** [comment]
Closing due to inactivity, and likely because it's an invalid bug report.

**Comment by Crocmagnon** [comment]
For anybody stumbling upon this, I can confirm it's an issue with the json-log-formatter package.

Here's the formatter class we use to circumvent this:

```python
import json_log_formatter
from django.http import HttpRequest


class JSONFormatter(json_log_formatter.JSONFormatter):
    def to_json(self, record):
        try:
            return self.json_lib.dumps(record, default=_json_serializable)
        except TypeError:
            return self.json_lib.dumps(record)


def _json_serializable(obj):
    if isinstance(obj, HttpRequest):
        return str(obj)
    try:
        return obj.__dict__
    except AttributeError:
        return str(obj)
```
