### ISSUE TITLE
Support hosted/mounted sub applications on FastAPI

### ISSUE THREAD

**Issue by OleksandrRakovets** [getsentry/sentry-python#2631]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.39.1

### Steps to Reproduce

In order to handle different hostnames, FastAPI application can serve sub applications via `host` or `mount` options. [Methods signature in Starlette](https://github.com/encode/starlette/blob/c3c6314759b8356df185857c6001de6c8575708d/starlette/applications.py#L124)

For example:

```python
app = FastAPI()
sub_app_1 = FastAPI()
sub_app_2 = FastAPI()
# setup routes for each app

app.host(HOST_1, sub_app_1)
app.host(HOST_2, sub_app_2)
```

This leads to child `route`s being substituted with `Host` or `Mount` object respectively.

### Expected Result

FastAPI & Starlette integrations do not crash.

Ideally, it should capture the actual URL, if it is possible from additional objects.

### Actual Result

After adding `StarletteIntegration` with default arguments (`transaction_style="url"`) application crashes with the following logs:

```
2024-01-10 14:05:59,236 ERROR [httptools_impl.py] : Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 364, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 146, in _run_asgi3
    return await self._run_app(scope, receive, send, asgi_version=3)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 241, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 234, in _run_app
    return await self.app(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 157, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 157, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/webapp/app.py", line 297, in init_db_session
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 146, in _run_asgi3
    return await self._run_app(scope, receive, send, asgi_version=3)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 161, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 157, in _run_app
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 256, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 157, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 157, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 515, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 364, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 146, in _run_asgi3
    return await self._run_app(scope, receive, send, asgi_version=3)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 161, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 157, in _run_app
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 115, in _create_span_call
    name, source = _get_transaction_from_middleware(app, scope, integration)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 684, in _get_transaction_from_middleware
    name = _transaction_name_from_router(asgi_scope)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 647, in _transaction_name_from_router
    return route.path
           ^^^^^^^^^^
AttributeError: 'Host' object has no attribute 'path'
```

**Comment by sentrivana** [comment]
@OleksandrRakovets Thank you for reporting. We currently assume that all routes have a `path` attribute, but this is [not the case for Host](https://github.com/encode/starlette/blob/c3c6314759b8356df185857c6001de6c8575708d/starlette/routing.py#L500), so we'll need to fix that.

**Comment by szokeasaurusrex** [comment]
Hi @OleksandrRakovets, could you please provide more detail on how to reproduce this bug, including the exact steps you took?

**Comment by OleksandrRakovets** [comment]
Hi @szokeasaurusrex!

I cannot share the actual app code, tried to outline its setup in initial ticket.

The app purpose is to respond to different subdomains from a single container.

```python
app = FastAPI()
sub_app_1 = FastAPI()
sub_app_2 = FastAPI()
# setup routes for each app

app.host('app.company.local', sub_app_1)
app.host('api.company.local', sub_app_2)

# alternatively, for local development, it can serve API sub app with a path prefix with
# app.mount('/api', sub_app_2)
```

I have updated sentry-sdk (1.11.1 -> 1.39.1) and according to the latest docs updated the package to `sentry-sdk = {extras = ["fastapi"], version = "^1.39.1"}`

This immediately crashed the app with the log above before I even tried to add a deliberate error to see in Sentry.

Then I followed [the integration docs advice](https://docs.sentry.io/platforms/python/integrations/fastapi/#options) and changed `transaction_style` to `endpoint`. 
The app stopped crashing, but every error in Sentry had been labelled from `fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware` instead of actual function.

So I have pointed the issue to Starlette integration, managed to disable it from autoloading, and opened this ticket :)

**Comment by szokeasaurusrex** [comment]
Hi @OleksandrRakovets, are you also experiencing the same error when you use `app.mount` instead of `app.host`?

The part I was having difficulty with was accessing the `app.host` routes in my local development environment after starting the dev server. But, if you also observe the error with `app.mount`, I can try reproducing with `app.mount`, instead.

**Comment by frankie567** [comment]
Allow me to ping this. I admit Host-based routing is probably not the most widely used option of Starlette/FastAPI, but I think Sentry should at the very least ignore it to not completely preventing from using it.
