### ISSUE TITLE
Cannot trigger Celery task when I add sentry in settings.py (django)

### ISSUE THREAD

**Issue by amzar96** [getsentry/sentry-python#2723]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.40.3

### Steps to Reproduce

1. Create celery task in the django
2. Trigger the endpoint that containt the celery task
3. Error show up

### Expected Result

No error

### Actual Result

```
[2024-02-09 18:46:15,606: ERROR/MainProcess] Process 'ForkPoolWorker-4' pid:3944 exited with 'signal 11 (SIGSEGV)'
[2024-02-09 18:46:15,766: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 11 (SIGSEGV) Job: 0.')
Traceback (most recent call last):
  File "/Users/amzar/Documents/python_env/xxx/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.einfo.ExceptionWithTraceback:
"""
Traceback (most recent call last):
  File "/Users/amzar/Documents/python_env/xxx/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV) Job: 0.
"""
```

**Comment by sentrivana** [comment]
Hey @amzar96, thanks for the report.

Does this still happen when you downgrade the SDK to version 1.39.2? Does it happen if you leave the SDK out of the mix completely, i.e., when you do not call `sentry_sdk.init` at all?

**Comment by amzar96** [comment]
@sentrivana 

I realized the error only occurred after hitting the Celery task for the first time the celery worker ran. After I made the next hit to the Celery task, it worked as expected. 

Till now not sure what is caused

**Comment by amzar96** [comment]
@sentrivana 

Not yet try to downgrade the SDK. I will try it later.
