### ISSUE TITLE
Error while running flask with eventlet

### ISSUE THREAD

**Issue by ericman93** [getsentry/sentry-python#273]
I'm running flask with eventlet and I have the following error
```
AttributeError: 'Response' object has no attribute 'status_code'
```
In raven I could change transport to `EventletHttpTransport` but I can't see this class in the current SDK

**Comment by untitaker** [comment]
@ericman93 I need more information.

* do you have a stacktrace for this? I don't know where this error occurs, which code is trying to access the `Response`, what the `Response`'s full type is (is it even a Flask response?)
* Which version of Flask, Python and the SDK are you using?

**Comment by ericman93** [comment]
python version: 3.6.1
flask vesrion: 0.12.2
sdk version: 0.7.3
gunicorn version: 19.9.0

```
[2019-02-26 23:37:55 +0200] [80579] [ERROR] Error handling request /socket.io/?EIO=3&transport=websocket
Traceback (most recent call last):
  File "/Users/eric/.pyenv/versions/3.6.1/envs/romee/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/Users/eric/.pyenv/versions/3.6.1/envs/romee/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 116, in handle_request
    resp.close()
  File "/Users/eric/.pyenv/versions/3.6.1/envs/romee/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 409, in close
    self.send_headers()
  File "/Users/eric/.pyenv/versions/3.6.1/envs/romee/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 325, in send_headers
    tosend = self.default_headers()
  File "/Users/eric/.pyenv/versions/3.6.1/envs/romee/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 306, in default_headers
    elif self.should_close():
  File "/Users/eric/.pyenv/versions/3.6.1/envs/romee/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 229, in should_close
    if self.status_code < 200 or self.status_code in (204, 304):
AttributeError: 'Response' object has no attribute 'status_code' 
```
running gunicron with 1 worker (instead of 4) every thing seems to work fine

killing gunicron procsses raise this exception
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/eric/.pyenv/versions/3.6.1/envs/romee/lib/python3.6/site-packages/sentry_sdk/worker.py", line 66, in flush
    self._wait_flush(timeout, callback)
  File "/Users/eric/.pyenv/versions/3.6.1/envs/romee/lib/python3.6/site-packages/sentry_sdk/worker.py", line 71, in _wait_flush
    if not self._timed_queue_join(initial_timeout):
  File "/Users/eric/.pyenv/versions/3.6.1/envs/romee/lib/python3.6/site-packages/sentry_sdk/worker.py", line 33, in _timed_queue_join
    queue.all_tasks_done.acquire()
AttributeError: 'Queue' object has no attribute 'all_tasks_done'
```

**Comment by untitaker** [comment]
So there are two seemingly unrelated crashes:

* The first one seems entirely unrelated to the Sentry SDK. https://github.com/benoitc/gunicorn/issues/1852 Do you not get this error with raven?
* The other one I understand, and I'll fix it.

**Comment by ericman93** [comment]
I don't get this while using raven

**Comment by daviskirk** [comment]
I also get the 

```
AttributeError: 'Queue' object has no attribute 'all_tasks_done'.
```

Minimal code to reproduce:

```python
import eventlet
eventlet.monkey_patch()

import sentry_sdk
sentry_sdk.init("https://xxxxxxxx")
raise ValueError('Test error to test sentry integration')
```

results in 

```
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    raise ValueError('Test error to test sentry integration')
ValueError: Test error to test sentry integration
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/location/lib/python3.6/site-packages/sentry_sdk/worker.py", line 81, in flush
    self._wait_flush(timeout, callback)
  File "/location/lib/python3.6/site-packages/sentry_sdk/worker.py", line 87, in _wait_flush
    if not self._timed_queue_join(initial_timeout):
  File "/location/lib/python3.6/site-packages/sentry_sdk/worker.py", line 45, in _timed_queue_join
    queue.all_tasks_done.acquire()  # type: ignore
AttributeError: 'Queue' object has no attribute 'all_tasks_done'
```

### Versions:

```
Python 3.6.8
eventlet==0.24.1
sentry-sdk==0.7.10
```

**Comment by daviskirk** [comment]
@untitaker I'd be happy to try and add a patch for this (for the attribute error) if needed.
Currently we work around this by (badly) monkey patching the queue join method that causes the problem:

```python
def _timed_queue_join(self, timeout):
    """Monkeypatched version of `Queue._timed_queue_join` to work around sentry bug.

    https://github.com/getsentry/sentry-python/issues/273#issuecomment-481198203.

    TODO: Remove as soon as mentioned bug is fixed.
    """
    try:
        with eventlet.Timeout(timeout) as timeout_error:
            self._queue.join()
    except eventlet.Timeout as e:
        if e is not timeout_error:
            raise


_original_timed_queue_join = sentry_sdk.worker.BackgroundWorker._timed_queue_join
sentry_sdk.worker.BackgroundWorker._timed_queue_join = _timed_queue_join
```

**Comment by untitaker** [comment]
Ah, sorry for dropping the ball on this. I would highly apprechiate a patch for the queue problem.

**Comment by daviskirk** [comment]
@untitaker  is there any good place in the code to start understand how sentry handles these implicit concurrency libs like eventlet or gevent?  I can't really tell if the code attempts to handle them or they are not explicitely supported (the old raven clients hat specific transports and code for these but that doesn't exist here).

**Comment by untitaker** [comment]
@daviskirk there exists no precedent in this codebase. I think the best thing you can do is to check if the attribute exists and fall back to a custom impl

**Comment by NotSoShaby** [comment]
Any news on this issue? I get the same error

**Comment by sagydr** [comment]
any fix coming out soon?

**Comment by untitaker** [comment]
@sagydr @NotSoShaby I will look into this next week

**Comment by sagydr** [comment]
@untitaker  any news regarding this issue? Thanks

**Comment by danielkrich** [comment]
I'm experiencing the same thing 😞 
Is there a fix available?

**Comment by untitaker** [comment]
I looked into this and I would recommend to either switch to greenlet workers for gunicorn or to disable eventlet monkeypatching for the queue module for now. What eventlet does to the queue module seems to be done very carelessly and breaks the stdlib's API in other places already. The fix I have right now would mean copying half of the queue implementation from the stdlib into the SDK.
