### ISSUE TITLE
Cron monitor check-in fails due to backend errors in event flushing 

### ISSUE THREAD

**Issue by hxyannay** [getsentry/sentry-python#2757]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.40.5

### Steps to Reproduce

Hello.

I have multiple crons in my project, and sometimes some crons get stuck as "in progress" despite finishing, and after the max duration passes they move to error due to duration.
I have initially checked that the crons actually work, and finish properly in time (they run in K8s CronJobs, and the underlying pods finish well with exit code 0 in the expected duration, way lower than the threshold).
Since we got multiple alerts of the crons I enabled sentry debug mode using `sentry_sdk.init(..., debug=True)`, and I saw that the runs that stay stuck as in progress show the following error:
```
 [sentry] DEBUG: Sending envelope [envelope with 1 items (monitor)] project:<PROJECT_ID> host:o4504236632113152.ingest.sentry.io
 [sentry] DEBUG: atexit: got shutdown signal
 [sentry] DEBUG: atexit: shutting down client
 [sentry] DEBUG: Flushing HTTP transport
 [sentry] ERROR: Internal error in sentry_sdk
Traceback (most recent call last):
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/sentry_sdk/integrations/stdlib.py", line 126, in getresponse
    return real_getresponse(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1390, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/sentry_sdk/transport.py", line 535, in send_envelope_wrapper
    self._send_envelope(envelope)
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/sentry_sdk/transport.py", line 434, in _send_envelope
    self._send_request(
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/sentry_sdk/transport.py", line 245, in _send_request
    response = self._pool.request(
               ^^^^^^^^^^^^^^^^^^^
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/urllib3/_request_methods.py", line 118, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/urllib3/_request_methods.py", line 217, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/poetry_virtualenvs/venv-py3.11/lib/python3.11/site-packages/sentry_sdk/integrations/stdlib.py", line 126, in getresponse
    return real_getresponse(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1390, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 294, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
 [sentry] DEBUG: background worker got flush request
 [sentry] DEBUG: Sending envelope [envelope with 1 items (internal)] project:<PROJECT_ID> host:o4504236632113152.ingest.sentry.io
 [sentry] DEBUG: 1 event(s) pending on flush
Sentry is attempting to send 1 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
 [sentry] DEBUG: background worker flushed
 [sentry] DEBUG: Killing HTTP transport
 [sentry] DEBUG: background worker got kill request
```
I assume that this is an error in Sentry's SaaS backend, because my application has no other issues besides that one.
It happens quite frequently, few dozens times per day, making the cron monitor feature unreliable and unusable.

I think a simple solution outside of fixing the backend issues would be to introduce retry mechanism in the HTTPTransport to handle with those cases.

Thanks in advance, Yannay

### Expected Result

I would expect my cronjob runs to send the correct events, and update sentry accordingly so that if the cron succeeds in a short time it would not fail due to duration expiry.

### Actual Result

Logs attached in Steps to Reproduce

**Comment by sentrivana** [comment]
Hey @hxyannay, thanks for writing in. Can you give [this custom transport](https://github.com/getsentry/sentry-python/issues/1198#issuecomment-1802638463) with exposed socket options a try and see if it changes anything?

**Comment by hxyannay** [comment]
Hi.
I will try that and update but even if this works it is a very sub-optimal solution because I will need to patch sentry_sdk in each of my crons instead of that being fixed at the library level.

**Comment by sentrivana** [comment]
Thanks @hxyannay -- I'm not saying patching the transport is necessarily the solution, but it helps identify the underlying problem. If it fixes the issue for you, then the solution might just be exposing the socket options properly, which we're planning to do soon. If it doesn't fix the issue for you, then we need to look into alternatives, maybe optional retries, etc.

**Comment by hxyannay** [comment]
Hey @sentrivana 
It seems that since applying this change the amount of errors dropped significantly (by around 85%), but I am still get some missing events.

**Comment by antonpirker** [comment]
Just a quick update: @sentrivana is working to make the tcp parameters available to be set without a custom transport. This will make changing those parameters way easier!

**Comment by hxyannay** [comment]
Good to know, it seems that in the last few days it works even better :)
It will be great if you update me when it is released, and if you can send a code snippet describing how to use it, and I will close this issue.

Thanks!

**Comment by sentrivana** [comment]
Will do that @hxyannay. Good to hear that the drop rate has decreased even more in the meantime.

**Comment by hxyannay** [comment]
Looking good, thanks!
