### ISSUE TITLE
Task was destroyed but it is pending: _coro_creating_hub_and_span

### ISSUE THREAD

**Issue by cnicodeme** [getsentry/sentry-python#2908]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.34.0

### Steps to Reproduce

Hey team,

I'm having a lot of "Task was destroyed but it is pending!" issues reported at Sentry.

I'm running Sanic (v23.6.0) and here's a sample of the errors:

Task was destroyed but it is pending!
task: <Task pending name='Task-532' coro=<patch_asyncio.<locals>._sentry_task_factory.<locals>._coro_creating_hub_and_span() running at /var/www/fernand/env/lib/python3.9/site-packages/sentry_sdk/integrations/asyncio.py:52> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f7af084d2b0>()]>>

Here's a sample:
https://cyril-nicodeme.sentry.io/issues/5081979263/events/6a88812f7d1d4c269d792b5f4b010541/

(Hopefully, you can also access more details about the issue via the UUID internally).

### Expected Result

Should not have a "Task was destroyed but it is pending!" issue but properly send any issues

### Actual Result

Fails with "Task was destroyed but it is pending"

**Comment by sentrivana** [comment]
Hey @cnicodeme, thank you for reporting this!

Are the errors thrown when something specific happens (worker restarting, app shutdown, etc.) or just at random?

**Comment by cnicodeme** [comment]
Yes! When I restart the app, I get a ton of these

**Comment by sentrivana** [comment]
Thanks for confirming, I expected as much. The SDK being responsible for the errors being created is one thing, but we're even reporting them to Sentry, which is doubly wrong.

If you want to get rid of them before we fix this, one workaround would be to filter them out in a custom `before_send` (see [docs](https://docs.sentry.io/platforms/python/configuration/options/#before-send)).

**Comment by cnicodeme** [comment]
Thank you!

I can implement a `before_send` filter, but what should I filter?

**Comment by sentrivana** [comment]
You could do something like this:

```python
my_before_send(event, hint):
    if "_coro_creating_hub_and_span()" in event["message"]:
        return None  # this event will be dropped

    return event  # send everything else


sentry_sdk.init(
    # your usual stuff
    before_send=my_before_send,
)
```

To see what you can filter on, you can click on the `{}` button in the event in Sentry to see the raw JSON and the fields that you can use.

**Comment by sentrivana** [comment]
No target release yet, but I'll try to remember to come back to update this issue once I know. In general, as soon as an issue gets closed, the fix is scheduled for the upcoming release, which usually takes at most a couple weeks from then.

**Comment by cnicodeme** [comment]
Thank you :)

**Comment by cnicodeme** [comment]
Hi,

I'm re-opening this ticket because I realized a few things:

1. The current version of Sentry (v1.45.0) still sends the above error
2. Implementing the `if "_coro_creating_hub_and_span()" in event["message"]:` code suggestion caused all errors to stop being reported at Sentry.

I've removed the `before_send=my_before_send` line for now, but if you could let me know on what to do to avoid these, it would be nice :)

Thanks!

**Comment by sentrivana** [comment]
Hey @cnicodeme, this is still open, no fix for it yet. The `before_send` workaround should still work though -- unless there's an error in it, which might explain you not getting anything. The only thing I see that might be problematic is that `message` might not be there, if that's the case this should work:

```python
def my_before_send(event, hint):
    if "_coro_creating_hub_and_span()" in (event.get("message") or ""):
        return None  # this event will be dropped

    return event  # send everything else
```

If it still doesn't work, please try initializing the SDK with `debug=True` in the `init`, it should tell you more about what's going wrong.

**Comment by knksmith57** [comment]
FWIW we're seeing the same/similar thing, and it looks like the asyncio extension is the culprit (in our case):

```
INFO:     Application shutdown complete.
INFO:     Finished server process [223]
Exception ignored in: <coroutine object patch_asyncio.<locals>._sentry_task_factory.<locals>._coro_creating_hub_and_span at 0xffff876de890>
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/sentry_sdk/integrations/asyncio.py", line 46, in _coro_creating_hub_and_span
    with sentry_sdk.isolation_scope():
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/app/.venv/lib/python3.12/site-packages/sentry_sdk/scope.py", line 1638, in isolation_scope
    _current_scope.reset(current_token)
ValueError: <Token var=<ContextVar name='current_scope' default=None at 0xffffa2f49760> at 0xffff91567c80> was created in a different Context
Task was destroyed but it is pending!
task: <Task pending name='Task-16' coro=<patch_asyncio.<locals>._sentry_task_factory.<locals>._coro_creating_hub_and_span() done, defined at /app/.venv/lib/python3.12/site-packages/sentry_sdk/integrations/asyncio.py:42> wait_for=<Future pending cb=[Protocol._on_waiter_completed(), Task.task_wakeup()]>>
INFO:     Stopping reloader process [211]
```

**Comment by szokeasaurusrex** [comment]
@knksmith57 does [the workaround](https://github.com/getsentry/sentry-python/issues/2908#issuecomment-2071671636) work for you?

**Comment by antonpirker** [comment]
I have now tested this using this project: 
https://github.com/antonpirker/testing-sentry/tree/main/test-plain-python-asyncio-shutdown

When asyncio tasks are shut down mid execution, the `Task was destroyed but it is pending!` message is emitted. This is happening if Sentry is added to project or not. There is not much we can do about this. 

If Sentry is enabled there is another message emitted, because we wrap the users coroutine and use a ContextVar in the wrapper. And this triggers a similar message during shut down. 

What we can improve is how present the errors during shutdown and make it clear to the user what is happening and why. This is done in this PR: https://github.com/getsentry/sentry-python/pull/4129
