### ISSUE TITLE
AWS Lambda using serverless doesn't report to sentry

### ISSUE THREAD

**Issue by caulagi** [getsentry/sentry-python#294]
The following code doesn't report to sentry, but I expected the message to show up -

```python
import os

import sentry_sdk
from sentry_sdk.integrations.aws_lambda import AwsLambdaIntegration

# my script 
import cleanup


def run(event, context):
    with sentry_sdk.init(dsn=os.getenv("SENTRY_DSN"), debug=True, integrations=[AwsLambdaIntegration()]):
        sentry_sdk.capture_message("foo")
        cleanup.run()
```

These are my logs -

```bash
START RequestId: f4d62f9e-2c8a-4b2c-8357-c3ac39871c29 Version: $LATEST
 [sentry] DEBUG: Setting up integrations (with default = True)
2019-03-17 11:35:25.444 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Setting up integrations (with default = True)
2019-03-17 11:35:25.444 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Enabling integration aws_lambda
2019-03-17 11:35:25.444 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Enabling integration logging
2019-03-17 11:35:25.444 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Enabling integration stdlib
2019-03-17 11:35:25.445 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Enabling integration excepthook
2019-03-17 11:35:25.445 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Enabling integration dedupe
2019-03-17 11:35:25.445 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Enabling integration atexit
2019-03-17 11:35:25.445 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Enabling integration modules
2019-03-17 11:35:25.445 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Enabling integration argv
2019-03-17 11:35:25.445 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Enabling integration threading
 [sentry] DEBUG: Enabling integration aws_lambda
 [sentry] DEBUG: Enabling integration logging
 [sentry] DEBUG: Enabling integration stdlib
 [sentry] DEBUG: Enabling integration excepthook
 [sentry] DEBUG: Enabling integration dedupe
 [sentry] DEBUG: Enabling integration atexit
 [sentry] DEBUG: Enabling integration modules
 [sentry] DEBUG: Enabling integration argv
 [sentry] DEBUG: Enabling integration threading
 [sentry] DEBUG: Flushing HTTP transport
 [sentry] DEBUG: background worker got flush request
2019-03-17 11:35:25.454 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Flushing HTTP transport
2019-03-17 11:35:25.454 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	background worker got flush request
 [sentry] DEBUG: Sending info event [01098f8116294a5f8dffa2ff8b9fdf3e] to sentry.io project:1301031
2019-03-17 11:35:25.454 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Sending info event [01098f8116294a5f8dffa2ff8b9fdf3e] to sentry.io project:1301031
2019-03-17 11:35:25.454 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Starting new HTTPS connection (1): sentry.io:443
 [sentry] DEBUG: 0 event(s) pending on flush
2019-03-17 11:35:25.554 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	0 event(s) pending on flush
 [sentry] DEBUG: background worker flushed
2019-03-17 11:35:27.454 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	background worker flushed
 [sentry] DEBUG: Killing HTTP transport
2019-03-17 11:35:27.455 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	Killing HTTP transport
 [sentry] DEBUG: background worker got kill request
2019-03-17 11:35:27.455 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[DEBUG]	background worker got kill request
 [sentry] WARNING: init() called inside of pushed scope. This might be entirely legitimate but usually occurs when initializing the SDK inside a request handler or task/job function. Try to initialize the SDK as early as possible instead.
2019-03-17 11:35:27.455 (+01:00)	f4d62f9e-2c8a-4b2c-8357-c3ac39871c29	[WARNING]	init() called inside of pushed scope. This might be entirely legitimate but usually occurs when initializing the SDK inside a request handler or task/job function. Try to initialize the SDK as early as possible instead.
local variable 'logger' referenced before assignment: UnboundLocalError
Traceback (most recent call last):
  File "/var/task/sentry_sdk/integrations/aws_lambda.py", line 37, in sentry_handler
    reraise(*exc_info)
  File "/var/task/sentry_sdk/_compat.py", line 52, in reraise
    raise value
  File "/var/task/sentry_sdk/integrations/aws_lambda.py", line 28, in sentry_handler
    return handler(event, context, *args, **kwargs)
  File "/var/task/handler.py", line 16, in run
    cleanup.run()
  File "/var/task/cleanup.py", line 43, in run
    logger.info("Starting cleanup for registrations older than: %s", before_date)
UnboundLocalError: local variable 'logger' referenced before assignment

END RequestId: f4d62f9e-2c8a-4b2c-8357-c3ac39871c29
```

I am using `sentry-sdk==0.7.6` with `https://github.com/UnitedIncome/serverless-python-requirements`.

**Comment by untitaker** [comment]
Call the `init` outside of your handler, at import.

**Comment by untitaker** [comment]
To clarify, you have two options:

## A

```python
# install integration early without setting up the SDK
sentry_sdk.init(integrations=[AwsLambdaIntegration()])

def run(event, context):
    sentry_sdk.init(dsn=os.getenv("SENTRY_DSN"), debug=True, integrations=[AwsLambdaIntegration()])
    sentry_sdk.capture_message("foo")
    cleanup.run()
```

## B

```python
# install and setup everything asap
sentry_sdk.init(dsn=os.getenv("SENTRY_DSN"), debug=True, integrations=[AwsLambdaIntegration()])

def run(event, context):
    sentry_sdk.capture_message("foo")
    cleanup.run()
```

The reason the context manager doesn't work is:

* We need to initialize the AWS Lambda integration before a handler is called, because we do a lot of monkeypatching of the AWS Lambda runtime to make things work.
* The context manager doesn't capture exceptions but just enables and disables Sentry. Maybe it should capture exceptions, I don't see the harm in it doing so.

**Comment by caulagi** [comment]
Thanks! It actually seems like my lambda doesn't have access to internet, due to https://aws.amazon.com/premiumsupport/knowledge-center/internet-access-lambda-function/ - 

I had previously seen these errors in my logs (for a different code), but assumed there was  a problem with my setup. Also, there is no error in the logs for `capture_message` when it is not able to reach sentry. 

```
2019-03-17 11:16:47.906 (+01:00)	8b5ce240-a262-4836-af53-49342a8fcf75	[WARNING]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0e00375898>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /api/1301031/store/
2019-03-17 11:16:47.906 (+01:00)	8b5ce240-a262-4836-af53-49342a8fcf75	[DEBUG]	Starting new HTTPS connection (2): sentry.io:443
2019-03-17 11:16:47.907 (+01:00)	8b5ce240-a262-4836-af53-49342a8fcf75	[DEBUG]	Incremented Retry for (url='/api/1301031/store/'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2019-03-17 11:16:47.907 (+01:00)	8b5ce240-a262-4836-af53-49342a8fcf75	[WARNING]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0e00386550>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /api/1301031/store/
```

**Comment by untitaker** [comment]
Ah, so you're saying that the `capture_message("foo")` also doesn't make it to Sentry? That is odd. I assumed you were only talking about the `UnboundLocalError`.

I'm afraid I don't have enough experience with AWS to assist you in configuring the network of your setup. However, the lack of error when sending events is likely because we have a [shutdown timeout of 2 seconds](https://docs.sentry.io/error-reporting/configuration/?platform=python#shutdown-timeout), which you are likely exceeding when the connection times out. If you increase this using `init(shutdown_timeout=999999)` you will likely see the error.

We should improve those shutdown/flush debug messages.

**Comment by caulagi** [comment]
Yes, `capture_message` is not reported as having failed in the logs, when the lambda was not able to connect to internet. 

However, this works after I fixed my network issue. Thanks for the help :)

```python
sentry_sdk.init(dsn=os.getenv("SENTRY_DSN"), debug=True, integrations=[AwsLambdaIntegration()])

def run(event, context):
    sentry_sdk.capture_message("foo")
    cleanup.run()
```
