### ISSUE TITLE
2.2.0: documentation build fails `most likely due to a circular import`

### ISSUE THREAD

**Issue by kloczek** [getsentry/sentry-python#3076]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

2.2.0

### Steps to Reproduce

Just run `/usr/bin/sphinx-build -n -T -b man docs build/sphinx/man` in source tree.

### Expected Result

Documentation build should not fail.

### Actual Result

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.3.7

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/registry.py", line 453, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/sphinx/domains/c/__init__.py", line 13, in <module>
    from sphinx.domains.c._ast import (
  File "/usr/lib/python3.10/site-packages/sphinx/domains/c/_ast.py", line 22, in <module>
    from sphinx.domains.c._symbol import Symbol
  File "/usr/lib/python3.10/site-packages/sphinx/domains/c/_symbol.py", line 5, in <module>
    from sphinx.domains.c._ast import (
ImportError: cannot import name 'ASTDeclaration' from partially initialized module 'sphinx.domains.c._ast' (most likely due to a circular import) (/usr/lib/python3.10/site-packages/sphinx/d
omains/c/_ast.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 225, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.10/site-packages/sphinx/registry.py", line 456, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinx.domains.c (exception: cannot import name 'ASTDeclaration' from partially initialized module 'sphinx.domains.c._ast' (most likely due to a circular import) (/usr/lib/python3.10/site-packages/sphinx/domains/c/_ast.py))

Extension error:
Could not import extension sphinx.domains.c (exception: cannot import name 'ASTDeclaration' from partially initialized module 'sphinx.domains.c._ast' (most likely due to a circular import)
(/usr/lib/python3.10/site-packages/sphinx/domains/c/_ast.py))
```

**Comment by antonpirker** [comment]
Hey @kloczek ! Thanks for letting us know, I will take a look!

**Comment by antonpirker** [comment]
Can you try running sphinx in Python 3.11? (we used the `NotRequired` type, which was introduced in Python 3.11)

**Comment by kloczek** [comment]
Just tested https://github.com/getsentry/sentry-python/pull/3077 and it does not fixes reported issue 😞

**Comment by kloczek** [comment]
Just retested 2.5.1 and documentation build still fails.
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.3.7

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/registry.py", line 453, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/sphinx/domains/c/__init__.py", line 13, in <module>
    from sphinx.domains.c._ast import (
  File "/usr/lib/python3.10/site-packages/sphinx/domains/c/_ast.py", line 22, in <module>
    from sphinx.domains.c._symbol import Symbol
  File "/usr/lib/python3.10/site-packages/sphinx/domains/c/_symbol.py", line 5, in <module>
    from sphinx.domains.c._ast import (
ImportError: cannot import name 'ASTDeclaration' from partially initialized module 'sphinx.domains.c._ast' (most likely due to a circular import) (/usr/lib/python3.10/site-packages/sphinx/domains/c/_ast.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 225, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.10/site-packages/sphinx/registry.py", line 456, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinx.domains.c (exception: cannot import name 'ASTDeclaration' from partially initialized module 'sphinx.domains.c._ast' (most likely due to a circular import) (/usr/lib/python3.10/site-packages/sphinx/domains/c/_ast.py))

Extension error:
Could not import extension sphinx.domains.c (exception: cannot import name 'ASTDeclaration' from partially initialized module 'sphinx.domains.c._ast' (most likely due to a circular import) (/usr/lib/python3.10/site-packages/sphinx/domains/c/_ast.py))
```
