### ISSUE TITLE
last_event_id() crash: AttributeError: 'Scope' object has no attribute '_last_event_id'.

### ISSUE THREAD

**Issue by adamchainz** [getsentry/sentry-python#3113]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

master

### Steps to Reproduce

Run this file:

```python
import sentry_sdk

sentry_sdk.init()

with sentry_sdk.push_scope() as scope:
    sentry_sdk.last_event_id()
```

### Expected Result

No crash.

### Actual Result

Crash:

```
$ python example.py
Traceback (most recent call last):
  File "/.../example.py", line 6, in <module>
    sentry_sdk.last_event_id()
  File "/.../sentry_sdk/api.py", line 343, in last_event_id
    return Scope.last_event_id()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/.../sentry_sdk/scope.py", line 330, in last_event_id
    return cls.get_isolation_scope()._last_event_id
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scope' object has no attribute '_last_event_id'. Did you mean: 'last_event_id'?
```

#3064 added `last_event_id()` and `_last_event_id` but I think it missed copying `_last_event_id` in `Scope.__copy__`.

**Comment by szokeasaurusrex** [comment]
I reviewed your PR, please address the requested changes 🙂
