### ISSUE TITLE
Sentry SDK excephook throwing an exception

### ISSUE THREAD

**Issue by nvgoldin** [getsentry/sentry-python#334]
Getting the following error with `sentry-sdk[flask]==0.7.7`

```log
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/excepthook.py", line 23, in sentry_sdk_excepthook
   hub = Hub.current
AttributeError: 'NoneType' object has no attribute 'current'
```
Any ideas?

**Comment by untitaker** [comment]
I know how to fix this, but I want to understand why this happens. From what I can tell `Hub` is `None` because the interpreter is shutting down, but in my mind the excepthook should run directly before that happens.

Just so my assumptions are correct, this is happening when your process stops, right?

**Comment by nvgoldin** [comment]
Thanks for your reply. Actually, I am not sure, will check.

**Comment by lukeburden** [comment]
Here's another example of Hub being unexpectedly None - it's happening during a cron-job run. It does look like the SDK is stumbling trying to get traceback details, so there may be an underlying application exception, however I can find no corresponding event in Sentry despite the error stating that there are "0 pending" error messages to send suggesting that it would have been sent.

python 2.7
sentry-sdk==0.10.2

```
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(raven-sentry.BackgroundWorker, stopped daemon 140454837487360)>>
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry_sdk/integrations/excepthook.py", line 38, in sentry_sdk_excepthook
    hub = Hub.current
AttributeError: 'NoneType' object has no attribute 'current'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 823, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/lib/python2.7/traceback.py", line 242, in format_exc
    return ''.join(format_exception(etype, value, tb, limit))
  File "/usr/lib/python2.7/traceback.py", line 141, in format_exception
    list = list + format_tb(tb, limit)
  File "/usr/lib/python2.7/traceback.py", line 76, in format_tb
    return format_list(extract_tb(tb, limit))
  File "/usr/lib/python2.7/traceback.py", line 100, in extract_tb
    linecache.checkcache(filename)
AttributeError: 'NoneType' object has no attribute 'checkcache'
```

**Comment by antonpirker** [comment]
As the OP never responded I will close this issue. 

@lukeburden your request is something unrelated. If it this persists in the newest SDK version and a Python 3 version, than please create another issue. Thanks!
