### ISSUE TITLE
Fix `datetime` serialization for non-UTC timestamps

### ISSUE THREAD

**Issue by StabbarN** [getsentry/sentry-python#3453]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

2.13.0

### Steps to Reproduce

The events at https://xyz.sentry.io/issues/123/events/abc/ lose datetimes' timezone.

### Expected Result

The following code with `.isoformat()`
```
from zoneinfo import ZoneInfo
sthlm = datetime.datetime(2024, 3, 1, tzinfo=ZoneInfo("Europe/Stockholm"))
new_york = datetime.datetime(2024, 3, 1, tzinfo=ZoneInfo("America/New_York"))
sentry_sdk.set_context(
    "extra_context",
    {
        "sthlm": sthlm.isoformat(),
        "new_york": new_york.isoformat(),
    },
)
Hub.current.capture_event(...)
```
results in the screenshot below

![Image](https://github.com/user-attachments/assets/625f11b7-bd67-4cfa-babf-c3a88f6fe108)

### Actual Result

The following code
```
from zoneinfo import ZoneInfo
sthlm = datetime.datetime(2024, 3, 1, tzinfo=ZoneInfo("Europe/Stockholm"))
new_york = datetime.datetime(2024, 3, 1, tzinfo=ZoneInfo("America/New_York"))
sentry_sdk.set_context(
    "extra_context",
    {
        "sthlm": sthlm,
        "new_york": new_york,
    },
)
Hub.current.capture_event(...)
```
will lose timezone. See screenshot below

![Image](https://github.com/user-attachments/assets/e3f39d50-ba23-4bae-87c2-3caec2f358dd)

**Comment by StabbarN** [comment]
> Is there any reason preventing you from simply using .isoformat()?

It's not a problem for us anymore, but it may be for other users tho. Stripping timezone is a bit nasty.

We recursively parse `extra_context` and use `.isoformat()` if the value is a datetime.

**Comment by szokeasaurusrex** [comment]
> Stripping timezone is a bit nasty.

@StabberN agree with your point here. I discussed this issue with the rest of the team, and we noticed that the way we serialize non-UTC timestamps is incorrect, since we simply take the timestamp and append a "Z" to indicate UTC time without first converting the timestamp to UTC. This is fine if all timestamps are in UTC, but of course, your issue demonstrates that this is not always the case.

So, we will keep this issue open for now.

We will fix this issue in one of two ways, depending on what timestamp values Relay can accept:

  - If Relay accepts a timezone offset, we format UTC times the same way as we have until now, and non-UTC times will have the timezone offset appended.
  - If Relay can only take UTC times, we will convert all timestamps to UTC and send them in the same format we currently use. For example, `2024-03-01T00:00:00-05:00` (your New York time) would be sent as `2024-03-01T05:00:00.000000Z`

**Comment by szokeasaurusrex** [comment]
@StabbarN, I opened a PR to fix this issue.

However, if you want full control over the timestamp format, I still recommend formatting the timezone manually yourself. Although my PR will include timezone offsets in the timestamp, it will also include fractional seconds, which are not included in the `.isoformat()` you mentioned in your "Expected Result." If you are okay with having the fractional seconds, you can remove your custom formatting logic once my PR is merged an released, but if you don't want fractional seconds, you will need to continue using your custom parsing logic.

Thanks for reporting the issue, hope this information helps!

**Comment by StabbarN** [comment]
Thanks! 

We will rely on your fix once it has been released. 

I like inclusion of fractional seconds. It might be a deal breaker when debugging some issue.

**Comment by szokeasaurusrex** [comment]
@StabbarN small update to my previous comment: Due to some edge-case differences between how Python formats timezone offsets and how our backend expects to receive them, we have decided instead to convert all `datetime` objects to UTC, and only send these converted UTC timestamps to the server.

So, if you want to preserve the timezone information, you will have to continue formatting the timestamps manually as you have been doing.

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Same patch produced the same failure twice.

Relevant files:
- sentry_sdk/utils.py: seeded from gold changed files (offline eval)
- tests/test_utils.py: seeded from gold changed files (offline eval)

Attempts:
Attempt 1: success=False
File: sentry_sdk/utils.py
Result: {"command": "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/bin/python -m pytest tests/test_utils.py", "returncode": 1, "success": false}
Error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pytest/__main__.py", line 9, in <module>
    raise SystemExit(_console_main())
                     ^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 253, in _console_main
    code = _main(prog=_get_prog_name(sys.argv))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 223, in _main
    config = _prepareconfig(new_args, plugins, prog=prog)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 410, in _prepareconfig
    config: Config = pluginmanager.hook.pytest_cmdline_parse(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mo

Attempt 2: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Attempt 3: success=False
File: sentry_sdk/utils.py
Result: {"command": "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/bin/python -m pytest tests/test_utils.py", "returncode": 1, "success": false}
Error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pytest/__main__.py", line 9, in <module>
    raise SystemExit(_console_main())
                     ^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 253, in _console_main
    code = _main(prog=_get_prog_name(sys.argv))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 223, in _main
    config = _prepareconfig(new_args, plugins, prog=prog)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 410, in _prepareconfig
    config: Config = pluginmanager.hook.pytest_cmdline_parse(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mo

Attempt 4: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Token usage: 29975/80000
