### ISSUE TITLE
Fix AWS Lambda test suite

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#3464]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

current

### Steps to Reproduce

Just run AWS Lambda tests in CI.

### Expected Result

The AWS Lambda test suite is failing (see e.g. this [empty PR against master](https://github.com/getsentry/sentry-python/pull/3451)).

### Actual Result

Fix it.

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Phase plan_fix crashed: 1 validation error for PlanDecision
decision_frame.stage
  Input should be 'diagnose', 'plan' or 'reflect' [type=literal_error, input_value='execute', input_type=str]
    For further information visit https://errors.pydantic.dev/2.13/v/literal_error

Relevant files:
- sentry_sdk/integrations/aws_lambda.py: seeded from gold changed files (offline eval); bm25 rerank score=12.719; matched issue terms: aws, lambda, empty, https, github, com
- tests/integrations/aws_lambda/test_aws_lambda.py: requested by planner next_checks; bm25 rerank score=11.425; matched issue terms: aws, lambda, test, empty, https, com
- scripts/aws/aws-attach-layer-to-lambda-function.sh: path components match issue terms; bm25 rerank score=5.714; matched issue terms: aws, lambda, sentry, please, if
- tests/integrations/django/test_tasks.py: test file; bm25 rerank score=6.046; matched issue terms: test, failing, sentry, when, if
- scripts/aws/aws-deploy-local-layer.sh: path components match issue terms; bm25 rerank score=3.285; matched issue terms: aws, lambda, test, sentry
- tests/integrations/django/utils.py: test file; bm25 rerank score=3.653; matched issue terms: test, failing, if

Attempts:
Attempt 1: success=False
File: sentry_sdk/integrations/aws_lambda.py
Result: {"command": "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/bin/python -m pytest tests/integrations/aws_lambda", "returncode": 1, "success": false}
Error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pytest/__main__.py", line 9, in <module>
    raise SystemExit(_console_main())
                     ^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 253, in _console_main
    code = _main(prog=_get_prog_name(sys.argv))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 223, in _main
    config = _prepareconfig(new_args, plugins, prog=prog)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 410, in _prepareconfig
    config: Config = pluginmanager.hook.pytest_cmdline_parse(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mo

Attempt 2: success=False
File: sentry_sdk/integrations/aws_lambda.py
Result: {"command": "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/bin/python -m pytest tests/integrations/aws_lambda", "returncode": 1, "success": false}
Error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pytest/__main__.py", line 9, in <module>
    raise SystemExit(_console_main())
                     ^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 253, in _console_main
    code = _main(prog=_get_prog_name(sys.argv))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 223, in _main
    config = _prepareconfig(new_args, plugins, prog=prog)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 410, in _prepareconfig
    config: Config = pluginmanager.hook.pytest_cmdline_parse(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mo

Attempt 3: success=False
File: tests/integrations/aws_lambda/test_aws_lambda.py
Result: {"command": "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/bin/python -m pytest tests/integrations/aws_lambda", "returncode": 1, "success": false}
Error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pytest/__main__.py", line 9, in <module>
    raise SystemExit(_console_main())
                     ^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 253, in _console_main
    code = _main(prog=_get_prog_name(sys.argv))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 223, in _main
    config = _prepareconfig(new_args, plugins, prog=prog)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 410, in _prepareconfig
    config: Config = pluginmanager.hook.pytest_cmdline_parse(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mo

Token usage: 25964/80000
