### ISSUE TITLE
Sentry SDK does not properly adapt async Django middleware

### ISSUE THREAD

**Issue by Archmonger** [getsentry/sentry-python#3506]
### How do you use Sentry?

Self-hosted/on-premise

### Version

2.13

### Steps to Reproduce

Original issue raised in my repository
- https://github.com/Archmonger/ServeStatic/issues/25
 
1. Use any standard Django distribution that supports Async (Django >=3.2+)
2. Install Sentry SDK Middleware
3. Install [ServeStatic](https://github.com/Archmonger/ServeStatic) Middleware

### Expected Result

Sentry SDK should wrap async middleware and forward an **async** `get_response` function.

### Actual Result

Sentry SDK wraps async middleware but forwards a **synchronous** `get_response` function. This breaks any async-only middleware that is being wrapped, including ServeStatic.

The exception output can be seen on the original issue raised by @kefonseca: https://github.com/Archmonger/ServeStatic/issues/25#issue-2503886975

**Comment by szokeasaurusrex** [comment]
Hi @Archmonger, I tried to reproduce this issue today, but everything was working as expected. Could you please clarify which Sentry SDK version was being used when this error was observed? And, could you please provide a reproduction so we can figure out what is wrong?

**Comment by Archmonger** [comment]
I will defer a response to @kefonseca since I personally have no environments where I utilize sentry.

If he doesn't respond in a few days I'll go ahead and close this.

**Comment by szokeasaurusrex** [comment]
@Archmonger, feel free to leave the issue open until @kefonseca replies; I have applied the "Waiting for: Community" label which will automatically close the issue if there is no response after a few weeks

**Comment by kefonseca** [comment]
Hi, I was able to reproduce a minimal example but I noticed is a combination of 3 things

1. django-otp installed and middleware enable in settings
2. sentry-sdk installed and enabled
3. servestatic installed and middleware enabled.

If I remove any of those everything works. 

This is a repository with a minimal example of the settings that trigger the issue https://github.com/kefonseca/django-sentry-example

**Comment by kefonseca** [comment]
The problem is with django-otp following this documentation and extending OTPMiddleware to support async fixes the issue.

https://docs.djangoproject.com/en/5.1/topics/http/middleware/#asynchronous-support

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Same patch produced the same failure twice.

Relevant files:
- sentry_sdk/integrations/django/middleware.py: seeded from gold changed files (offline eval)
- tests/integrations/django/test_middleware.py: seeded from gold changed files (offline eval)

Attempts:
Attempt 1: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Attempt 2: success=False
File: sentry_sdk/integrations/django/middleware.py
Result: {"command": "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/bin/python -m pytest tests/integrations/django/test_middleware.py", "returncode": 1, "success": false}
Error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pytest/__main__.py", line 9, in <module>
    raise SystemExit(_console_main())
                     ^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 253, in _console_main
    code = _main(prog=_get_prog_name(sys.argv))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 223, in _main
    config = _prepareconfig(new_args, plugins, prog=prog)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 410, in _prepareconfig
    config: Config = pluginmanager.hook.pytest_cmdline_parse(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mo

Attempt 3: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Token usage: 16727/80000
