### ISSUE TITLE
Some of the errors are failling to be sent to gitlab's sentry error monitoring due to brotli

### ISSUE THREAD

**Issue by narekvslife** [getsentry/sentry-python#3750]
### How do you use Sentry?

Self-hosted/on-premise

### Version

2.18.0

### Steps to Reproduce

`python help.py`

`help.py`:

```python
import sentry_sdk

sentry_sdk.init(dsn=<GITLAB_SENTRY_DSN>, debug=True)

division_by_zero = 1 / 0
```

- pip freeze (Python 3.11.7, pip 23.2.1)

```
Brotli==1.1.0
certifi==2024.8.30
sentry-sdk==2.18.0
urllib3==2.2.3
```

### Expected Result

Error is being sucessfully sent to gitlab (this is the log after `pip uninstall brotli`):

```
Traceback (most recent call last):
  File "/Users/narekalvandan/planeto/tessa/kek.py", line 5, in <module>
    division_by_zero = 1 / 0
                       ~~^~~
ZeroDivisionError: division by zero
 [sentry] DEBUG: atexit: got shutdown signal
 [sentry] DEBUG: Sending envelope [envelope with 1 items (error)] project:43180570 host:observe.gitlab.com
 [sentry] DEBUG: atexit: shutting down client
 [sentry] DEBUG: Flushing HTTP transport
 [sentry] DEBUG: background worker got flush request
 [sentry] DEBUG: 2 event(s) pending on flush
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
 [sentry] DEBUG: background worker flushed
 [sentry] DEBUG: Killing HTTP transport
 [sentry] DEBUG: background worker got kill reques
```

i.e. pip freeze:

```
certifi==2024.8.30
sentry-sdk==2.18.0
urllib3==2.2.3
```

### Actual Result

Note the `Unexpected status code: 400 (body: b'')` at the end:

```
...

Traceback (most recent call last):
  File "/Users/narekalvandan/planeto/tessa/kek.py", line 5, in <module>
    division_by_zero = 1 / 0
                       ~~^~~
ZeroDivisionError: division by zero
 [sentry] DEBUG: atexit: got shutdown signal
 [sentry] DEBUG: atexit: shutting down client
 [sentry] DEBUG: Flushing HTTP transport
 [sentry] DEBUG: background worker got flush request
 [sentry] DEBUG: Sending envelope [envelope with 1 items (error)] project:43180570 host:observe.gitlab.com
 [sentry] DEBUG: 2 event(s) pending on flush
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
 [sentry] ERROR: Unexpected status code: 400 (body: b'')
 [sentry] DEBUG: Sending envelope [envelope with 1 items (internal)] project:43180570 host:observe.gitlab.com
 [sentry] ERROR: Unexpected status code: 400 (body: b'')**
 [sentry] DEBUG: background worker flushed
 [sentry] DEBUG: Killing HTTP transport
 [sentry] DEBUG: background worker got kill request
```

**Comment by BYK** [comment]
@narekvslife the Brotli decoding is done inside relay and it wasn't a recent addition. How old is this GitLab instance?

**Comment by narekvslife** [comment]
GitLab Enterprise Edition 17.6.0-pre [483fb0ca117](https://gitlab.com/gitlab-org/gitlab/-/commits/483fb0ca117)

**Comment by BYK** [comment]
@narekvslife sorry for not being clear, I'm interested in the Sentry version.

**Comment by narekvslife** [comment]
Sentry that I'm using is **2.18.0**. I am not sure I have access to Gitlab's sentry.. So our version is the one set in gitlab by default. 

To be clear, we're using the [Gitlab Integrated error tracking](https://docs.gitlab.com/ee/operations/integrated_error_tracking.html), not Sentry's [gitlab integration](https://docs.sentry.io/organization/integrations/source-code-mgmt/gitlab/).

**Comment by narekvslife** [comment]
As a side note, everything works with 1.21.0 which is the "tested version of the sdk" according to GitLab. Now that I think about it, maybe addressing this question to the GitLab's team is more appropriate?

**Comment by BYK** [comment]
@narekvslife that version is `sentry-sdk` version for the Python SDK. I am asking about the self-hosted Sentry version on GitLab side. If GitLab has something in-house that can ingest Sentry events than I'm afraid this repo is not the right place for that question.

You can force the new SDK by setting `_experiments={"transport_compression_algo":"gzip"}` to use `gzip` instead for now.
