### ISSUE TITLE
request.bounded_stream is consumed

### ISSUE THREAD

**Issue by sauravshanu1** [getsentry/sentry-python#3761]
Our firm recently adopted Sentry. We use the default Falcon Integration for request tracing etc. 

We are facing trouble while reading the `request.bounded_stream` data.

In https://github.com/getsentry/sentry-python/blob/f62c83d6363e515e23d9a5da20354771108642a9/sentry_sdk/integrations/falcon.py#L81, 
`request.bounded_stream` is already consumed before the request comes to request handler. 
So, this causes the variable `data` to be empty. See snippet below.
```
def on_post(self, request, response):
     data = request.bounded_stream.read()
```
It is true that the parsed data can be accessed by request.get_media(). However, I would like to access the raw data for purposes like signature verification etc.
Right now, we don't have any option other than disabling Sentry Falcon Integration altogether and writing our own integration to circumvent this problem. 

Can Sentry media not consume the media if it is not consumed yet? Or, if it does, reset the `bounded_stream` with the payload data.

**Comment by sentrivana** [comment]
Heya @sauravshanu1, thank you for the report. This shouldn't happen. We need to see how we can retrieve the data without exhausting the stream.

In the meantime, you could set [`max_request_body_size`](https://docs.sentry.io/platforms/python/configuration/options/#max-request-body-size) to `never` in your SDK `init()` -- this should prevent the SDK from accessing the stream altogether I believe. (You won't get the request body in Sentry this way.)

**Comment by sauravshanu1** [comment]
Thanks @sentrivana for the fast response and your solution. It does work and the raw data can now be read from the `bounded_stream` exactly. I can live with no `request.body` in Sentry until this is fixed.

**Comment by szokeasaurusrex** [comment]
Hi @sauravshanu1, could you please provide a minimal reproduction of the error? I tried to reproduce your bug, but I observed different behavior with the following code:

```python
# test.py

from wsgiref.simple_server import make_server
import falcon
import sentry_sdk

sentry_sdk.init(traces_sample_rate=1.0, debug=True)


class TestResource(object):
    def on_post(self, req: falcon.Request, resp: falcon.Response):
        print(req.bounded_stream.read())
        resp.status = falcon.HTTP_200
        resp.text = "Hello, World!\n"


app = falcon.App()
app.add_route("/", TestResource())


if __name__ == "__main__":
    with make_server("", 8000, app) as httpd:
        print("Serving on port 8000...")

        # Serve until process is killed
        httpd.serve_forever()
```

My `pip freeze` is:

```
# requirements.txt

certifi==2024.8.30
falcon==4.0.2
pip==24.3.1
sentry-sdk==2.18.0
urllib3==2.2.3
```

I am running the code as follows:

```sh
$ export SENTRY_DSN="my DSN here"
$ python test.py
```

And in a separate terminal:

```sh
$ curl -H "Content-Type: application/json" \
-X POST -d '{"value":"Hello"}' http://localhost:8000
```

The request data gets printed correctly to console:

```
b'{"value":"Hello"}'
```

The only strange behavior I observed is that on [this line that you linked](https://github.com/getsentry/sentry-python/blob/f62c83d6363e515e23d9a5da20354771108642a9/sentry_sdk/integrations/falcon.py#L81), we are not able to read the `request.media` in the Sentry SDK. However, if I comment out the `print(req.bounded_stream.read())`, the `request.media` is there.

**Comment by sauravshanu1** [comment]
@szokeasaurusrex thanks for trying to reproduce it.

Sorry I forgot to mention that it happens only when the `sentry_sdk.scope.Scope.run_event_processors` runs `sentry_sdk.integrations.falcon.SentryFalconMiddleware` 's event_processor which then reads the `bounded_stream` before the data reaches the request handler such as `on_post`. As soon as there is a logline in a middleware for a certain request, the stream is already read.

To reproduce, I added a custom middleware that logs the request with an error message, then the  `bounded_stream` is consumed.

```python3
# test.py

from wsgiref.simple_server import make_server
import falcon
import sentry_sdk
import logging

sentry_sdk.init(traces_sample_rate=1.0, debug=True)
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)


class TestResource(object):
    def on_post(self, req: falcon.Request, resp: falcon.Response):
        print(req.bounded_stream.read())
        resp.status = falcon.HTTP_200
        resp.text = "Hello, World!\n"


class ExampleMiddleWare:
    def process_request(self, req, resp):
        sentry_sdk.capture_event({"message": "Processing request"})
        # logger.error('Processing request')


app = falcon.App(middleware=[ExampleMiddleWare()])
app.add_route("/", TestResource())


if __name__ == "__main__":
    with make_server("", 8000, app) as httpd:

        print("Serving on port 8000...")

        # Serve until process is killed
        httpd.serve_forever()

```

If you try to remove the log line, you should be able to read the stream.

> The only strange behavior I observed is that on [this line that you linked](https://github.com/getsentry/sentry-python/blob/f62c83d6363e515e23d9a5da20354771108642a9/sentry_sdk/integrations/falcon.py#L81), we are not able to read the request.media in the Sentry SDK. However, if I comment out the print(req.bounded_stream.read()), the request.media is there.

I guess that's probably because `request.get_media` or `request.media` [caches the data that it reads from `bounded_stream`](https://github.com/falconry/falcon/blob/master/falcon/request.py#L1083). If some other code reads the stream already, there's nothing to read or cache.

Thanks!

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Failed to generate fix plan: TimeoutError

Relevant files:
- sentry_sdk/integrations/falcon.py: seeded from gold changed files (offline eval)
- tests/integrations/falcon/test_falcon.py: seeded from gold changed files (offline eval)

Attempts:
Attempt 1: success=False
File: sentry_sdk/integrations/falcon.py
Result: {"command": "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/bin/python -m pytest tests/integrations/falcon/test_falcon.py", "returncode": 1, "success": false}
Error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pytest/__main__.py", line 9, in <module>
    raise SystemExit(_console_main())
                     ^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 253, in _console_main
    code = _main(prog=_get_prog_name(sys.argv))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 223, in _main
    config = _prepareconfig(new_args, plugins, prog=prog)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/_pytest/config/__init__.py", line 410, in _prepareconfig
    config: Config = pluginmanager.hook.pytest_cmdline_parse(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morganbest/.repopilot/repos/getsentry-sentry-python-work-venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mo

Token usage: 11561/80000
