### ISSUE TITLE
Remove Extraneous AWS serverless timeout warning log data unless in debug mode

### ISSUE THREAD

**Issue by DM1145** [getsentry/sentry-python#3872]
### Problem Statement

Note: _Updated request #2318_

When using the python sdk, we output detailed logging when debug=True, but when running sentry in an AWS Lambda function using Python, if AWSLambdaIntegration() is enabled and timeout warnings are enabled, then content is logged that should only be present when debug is set to True.

As an example, when a timeout warning is triggered per the above conditions, records much like the following are sent to CloudWatch, _regardless of whether the debug flag is set to True or not set_.

> Exception in thread Thread-1:
> Traceback (most recent call last):
> File "/var/lang/lib/python3.9/threading.py", line 980, in _bootstrap_inner
> self.run()
> File "/opt/python/sentry_sdk/integrations/threading.py", line 100, in run
> return _run_old_run_func()
> File "/opt/python/sentry_sdk/integrations/threading.py", line 95, in _run_old_run_func
> reraise(*_capture_exception())
> File "/opt/python/sentry_sdk/utils.py", line 1690, in reraise
> raise value
> File "/opt/python/sentry_sdk/integrations/threading.py", line 93, in _run_old_run_func
> return old_run_func(self, *a, **kw)
> File "/opt/python/sentry_sdk/utils.py", line 1449, in run
> raise ServerlessTimeoutWarning(
> sentry_sdk.utils.ServerlessTimeoutWarning: WARNING : Function is expected to get timed out. Configured timeout duration = 5 seconds.

I'd think, for the sake of clarity and usability, when timeout_warnings are enabled and debug mode is not enabled, the log message should simply be the last text entry:
> sentry_sdk.utils.ServerlessTimeoutWarning: WARNING : Function is expected to get timed out. Configured timeout duration = 5 seconds.

### Solution Brainstorm

When debug mode is enabled, we should keep functionality consistent and ensure the all above logs are written.

**Comment by szokeasaurusrex** [comment]
Hi, the traceback is part of the warning. You can choose either to have the entire warning (including the traceback), or none of it by setting the [`timeout_warning` option](https://docs.sentry.io/platforms/python/integrations/aws-lambda/manual-instrumentation/#options) that @antonpirker referenced in https://github.com/getsentry/sentry-python/issues/2318#issuecomment-2535331689.

The `debug` option controls whether debug logs are emitted to console. In this case, the traceback is part of the warning message, and so this is completely separate from a debug log.
