### ISSUE TITLE
Celery - Queue object has no attribute  'all_tasks_done'

### ISSUE THREAD

**Issue by oji** [getsentry/sentry-python#471]
Hi all, 

I'm integrating Sentry on a project in python that uses Celery. I'm getting this error when shutting down the worker: 

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/jibanez/API/.conda/envs/cimrender/lib/python3.6/site-packages/sentry_sdk/worker.py", line 84, in flush
    self._wait_flush(timeout, callback)
  File "/Users/jibanez/API/.conda/envs/cimrender/lib/python3.6/site-packages/sentry_sdk/worker.py", line 90, in _wait_flush
    if not self._timed_queue_join(initial_timeout):
  File "/Users/jibanez/API/.conda/envs/cimrender/lib/python3.6/site-packages/sentry_sdk/worker.py", line 48, in _timed_queue_join
    queue.all_tasks_done.acquire()  # type: ignore
AttributeError: 'Queue' object has no attribute 'all_tasks_done'
```

I'm using: 
- Python 3.6
- Celery 4.3.0
- OSX Mojave

Any thoughts?

**Comment by untitaker** [comment]
Hi, are you using eventlet?

**Comment by oji** [comment]
Yes, I'm using eventlet

**Comment by untitaker** [comment]
Ok, there's a workaround here: https://github.com/getsentry/sentry-python/issues/273#issuecomment-485670456

I hadn't considered the case of using eventlet within Celery, and it seems that switching to greenlet is not an option there. I'll take a look next week. Thanks!
