### ISSUE TITLE
RuntimeError and SystemError generated by DjangoIntegration 

### ISSUE THREAD

**Issue by claudiu-olteanu-hs** [getsentry/sentry-python#492]
Hi there,

After we migrated from raven to sentry-sdk, we started noticing some new errors logged by `uwsgi` server. Most of the time, they are usually generated when the server is under load, so it could be a race condition.

Below you can find some information about our infrastructure:
```
Python 2.7.16
[GCC 4.8.4] on linux2 (ubuntu:trusty)

Python packages:
- Django==1.6.11
- django-tastypie==0.11.1
- uWSGI==2.0.11.2
- sentry-sdk==0.11.1
```

The generated errors:
```
[sentry] ERROR: Internal error in sentry_sdk
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/utils.py", line 50, in capture_internal_exceptions
    yield
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/serializer.py", line 208, in _serialize_node
    obj, max_depth=max_depth, max_breadth=max_breadth
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/serializer.py", line 268, in _serialize_node_impl
    for i, v in enumerate(obj):
RuntimeError: deque mutated during iteration
 [sentry] DEBUG: Sending event, type:null level:error event_id:1264a29db33f45c1ae18487a66795325 project:42340 host:sentry.io
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 102, in sentry_patched_wsgi_handler
    environ, start_response
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/wsgi.py", line 86, in __call__
    hub = Hub(Hub.current)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/hub.py", line 205, in __init__
    scope = copy.copy(other_scope)
  File "/usr/local/lib/python2.7/copy.py", line 80, in copy
    return copier(x)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/scope.py", line 302, in __copy__
    rv._breadcrumbs = copy(self._breadcrumbs)
  File "/usr/local/lib/python2.7/copy.py", line 80, in copy
    return copier(x)
SystemError: Objects/tupleobject.c:142: bad argument to internal function
```

Some data from Sentry event:
```
- mechanism: excepthook 
- handled: no 
- Variables from copy.py:80 stack:
cls: <type 'collections.deque'>
copier: <method '__copy__' of 'collections.deque' objects>
x : [{category: 'httplib', data: {httplib_response: <httplib.HTTPResponse instance at 0x7f873e71eea8>, method: 'POST', reason: 'OK', status_code: 200, url: 'https://sentry.io/api/42340/store/'}, timestamp: datetime.datetime(2019, 8, 29, 15, 49, 16, 626857), type: 'http'}, {category: 'httplib', data: {httplib_response: <httplib.HTTPResponse instance at 0x7f873e7945a8>, method: 'POST', reason: 'OK', status_code: 200, url:'https://sentry.io/api/42340/store/'}, timestamp: datetime.datetime(2019, 8, 29, 15, 49, 27, 11508), type: 'http'
}, (...)]

```

Code that initialized sentry:
```
sentry_sdk.init(
        dsn=DSN,
        integrations=[DjangoIntegration(transaction_style='function_name')],
        attach_stacktrace=True,
        debug=True,
    )
with sentry_sdk.configure_scope() as scope:
        scope.set_tag('tag_label1', 'tag_value1')
        scope.set_tag('tag_label2', 'tag_value2')
```

Let me know if I can share with you other information that can give you more insights.

Cheers,
Claudiu

**Comment by untitaker** [comment]
I believe I understand the issue although I am surprised that we haven't found it in our own production use. Does this cause problems such as downtimes or performance impact for you?

**Comment by claudiu-olteanu-hs** [comment]
Yes, the problem generates some 50X errors for us and we had to rollback to raven.

**Comment by untitaker** [comment]
Thank you, we will investigate this ASAP

**Comment by untitaker** [comment]
@claudiu-olteanu-hs could you post your uWSGI config? I have reason to believe that uWSGI is the culprit here.

**Comment by claudiu-olteanu-hs** [comment]
You can find below the configuration:
```
uwsgi --chdir=$APP_DIR \
            --pythonpath=$APP_DIR/app \
            --module=app.wsgi:application \
            --env DJANGO_SETTINGS_MODULE=app.settings \
            --uid $UID --gid $GID \
            --master --pidfile=$PID_FILE \
            --listen=128 \
            --http-socket=0.0.0.0:8000 \
            --processes=8 \
            --harakiri=60 \
            --buffer-size=8192 \
            --max-requests=500 \
            --enable-threads \
            --vacuum &> /mnt/logs/uwsgi.log
```

The `app.wsgy.py` file:
```
import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")

from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()
```

The django settings file doesn't contain anything special.

**Comment by untitaker** [comment]
Before we proceed further, could you try updating uwsgi to at least 2.0.18?

**Comment by claudiu-olteanu-hs** [comment]
Sure, next week I will try to do an update and I will let you know how it goes (if the problem persists).

**Comment by claudiu-olteanu-hs** [comment]
I wanted to let you know that we upgraded uwsgi to 2.0.18 and we couldn't reproduce the problem so far.

The only new errors that we noticed are:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/threading.py", line 56, in run
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/hub.py", line 229, in __exit__
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'set'
```

But these are caused by a different problem when something fails on the initialization.

**Comment by untitaker** [comment]
Ah great, we can fix that bug easily at least. From what I understand this is just causing an exception when you're already shutting down/crashing, right?

**Comment by claudiu-olteanu-hs** [comment]
Yes, the exceptions are raised when we are shutting down/crashing, or when an error occurs on the initialization. But these don't have any impact on our uptime.
