### ISSUE TITLE
flask with eventlet - ThreadingIntegration bug

### ISSUE THREAD

**Issue by sagydr** [getsentry/sentry-python#615]
I'm running flask with gunicorn eventlet.
I get the following exception from **ThreadingIntegration**
it does NOT reproduce when i disable all system integrations using 

> default_integrations=False (in sentry_sdk.init)

however I would like to have other system integrations.

> `Exception in thread raven-sentry.BackgroundWorker:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 863, in run
    if self._target:
AttributeError: '_MainThread' object has no attribute '_target'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/root/.local/share/virtualenvs/code-788z9T0p/lib/python3.6/site-packages/sentry_sdk/integrations/threading.py", line 69, in run
    reraise(*_capture_exception())
  File "/root/.local/share/virtualenvs/code-788z9T0p/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/root/.local/share/virtualenvs/code-788z9T0p/lib/python3.6/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/local/lib/python3.6/threading.py", line 868, in run
    del self._target, self._args, self._kwargs
AttributeError: _target
Exception in thread raven-sentry.BackgroundWorker:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 863, in run
    if self._target:
AttributeError: '_MainThread' object has no attribute '_target'`

versions:
Flask = "==0.12.2"
sentry-sdk = "==0.14.1"
eventlet = "==0.22.1"
gunicorn = "==19.9.0"

**Comment by sagydr** [comment]
here's the error

Exception in thread raven-sentry.BackgroundWorker:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 863, in run
    if self._target:
AttributeError: '_MainThread' object has no attribute '_target'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/root/.local/share/virtualenvs/code-788z9T0p/lib/python3.6/site-packages/sentry_sdk/integrations/threading.py", line 69, in run
    reraise(*_capture_exception())
  File "/root/.local/share/virtualenvs/code-788z9T0p/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/root/.local/share/virtualenvs/code-788z9T0p/lib/python3.6/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/local/lib/python3.6/threading.py", line 868, in run
    del self._target, self._args, self._kwargs
AttributeError: _target

Exception in thread raven-sentry.BackgroundWorker:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 863, in run
    if self._target:
AttributeError: '_MainThread' object has no attribute '_target'

**Comment by untitaker** [comment]
Are you sure that the exception does not occur when ThreadingIntegration is disabled, or that just the reporting to Sentry does not occur?

**Comment by sagydr** [comment]
When ThreadingIntegration is **enabled**:
 - The exception happens
 - reporting to Sentry didn't occur
When ThreadingIntegration is **disabled**:
 - no exception
 - reporting works

**Comment by Glitsch3n** [comment]
Hi !

I had the same problem than you  (i was using gunicorn & eventlet together) and it seems that updating eventlet to it's latest version did the trick (`0.29.1`)

Hope it helps :)

**Comment by untitaker** [comment]
We have some known problems outlined here: https://docs.sentry.io/platforms/python/troubleshooting/

@sagydr can you report if updating eventlet helps?

**Comment by antonpirker** [comment]
As the original poster did not reply and another user fixed this issue by updating eventlet (to a version that is now almost 2 years old) I think we can close this issue.
