### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by RDIL** [getsentry/sentry-python#665]
Sentry has reported this error to me, but I think this error is the result of sentry-sdk itself failing to report another error!

Stack (yes sorry its cut off):
```python
    return self.request_encode_body(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 102, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2020-04-03 06:15:06,961: Sending event, type:null level:error event_id:1e1b73402bf5435dbb9270782cd9c753 project:1799955 host:sentry.io
2020-04-03 06:25:06,340: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1108)'))': /api/1799955/store/
2020-04-03 06:25:07,140: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1108)'))': /api/1799955/store/
2020-04-03 06:30:07,103: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1108)'))': /api/1799955/store/
2020-04-03 06:39:52,314: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1108)'))': /api/1799955/store/
2020-04-03 06:44:51,994: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1108)'))': /api/1799955/store/
2020-04-03 07:04:52,103: Internal error in sentry_sdk
Traceback (most recent call last):
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connection.py", line 386, in connect
    self.sock = ssl_wrap_socket(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1108)
**NO MATCH**
During handling of the above exception, another exception occurred:
**NO MATCH**
Traceback (most recent call last):
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/transport.py", line 296, in send_event_wrapper
    self._send_event(event)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/transport.py", line 215, in _send_event
    self._send_request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/transport.py", line 163, in _send_request
    response = self._pool.request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sentry.io', port=443): Max retries exceeded with url: /api/1799955/store/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1108)')))
2020-04-03 07:10:05,243: Sending event, type:null level:error event_id:10c7f22e0ee24002a41a4876fcff2c91 project:1799955 host:sentry.io
2020-04-03 07:19:52,067: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1108)'))': /api/1799955/store/
2020-04-03 07:24:51,071: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1108)'))': /api/1799955/store/
2020-04-03 07:34:51,204: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1108)'))': /api/1799955/store/
2020-04-03 07:59:51,108: Internal error in sentry_sdk
Traceback (most recent call last):
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connection.py", line 386, in connect
    self.sock = ssl_wrap_socket(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1108)
**NO MATCH**
During handling of the above exception, another exception occurred:
**NO MATCH**
Traceback (most recent call last):
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/transport.py", line 296, in send_event_wrapper
    self._send_event(event)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/transport.py", line 215, in _send_event
    self._send_request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/transport.py", line 163, in _send_request
    response = self._pool.request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sentry.io', port=443): Max retries exceeded with url: /api/1799955/store/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1108)')))
2020-04-03 07:59:51,131: Sending event, type:null level:error event_id:97a7e51264ed43848b3ee88a373211b9 project:1799955 host:sentry.io
2020-04-03 08:20:06,178: Internal error in sentry_sdk
Traceback (most recent call last):
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 102, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
**NO MATCH**
During handling of the above exception, another exception occurred:
**NO MATCH**
Traceback (most recent call last):
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/transport.py", line 296, in send_event_wrapper
    self._send_event(event)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/transport.py", line 215, in _send_event
    self._send_request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/transport.py", line 163, in _send_request
    response = self._pool.request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/integrations/stdlib.py", line 102, in getresponse
    rv = real_getresponse(self, *args, **kwargs)
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2020-04-03 08:25:06,138: Internal error in sentry_sdk
Traceback (most recent call last):
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connection.py", line 386, in connect
    self.sock = ssl_wrap_socket(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1108)
**NO MATCH**
During handling of the above exception, another exception occurred:
**NO MATCH**
Traceback (most recent call last):
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/transport.py", line 296, in send_event_wrapper
    self._send_event(event)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/transport.py", line 215, in _send_event
    self._send_request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/sentry_sdk/transport.py", line 163, in _send_request
    response = self._pool.request(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/home/jumbocakeyumyum/backend/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sentry.io', port=443): Max retries exceeded with url: /api/1799955/store/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1108)')))
```

**Comment by untitaker** [comment]
This just looks like a network failure. I don't think the SDK did anything wrong here?

**Comment by RDIL** [comment]
But the network error is connecting to sentry

**Comment by untitaker** [comment]
So I guess the only idea I have is: 1) network failure on your end 2) broken version of urllib3 or openssl.

Do you get events into sentry at all?

**Comment by RDIL** [comment]
I did

**Comment by untitaker** [comment]
Can you post the output of `pip freeze` in that environment? I wonder whether you use some async library like gevent etc

**Comment by RDIL** [comment]
Here you go:
```python
aiohttp==3.6.2
appdirs==1.4.3
area4==3.6.0
async-timeout==3.0.1
attrs==19.3.0
black==19.10b0
cchardet==2.1.6
certifi==2019.11.28
chardet==3.0.4
click==7.1.1
Deprecated==1.2.7
discord-sentry-reporting==2.0.3
discord.py==1.3.2
entrypoints==0.3
factdata==2.0.0
filehandlers==2.12.1
flake8==3.7.9
idna==2.9
isort==4.3.21
iss-api==1.1
jedi==0.16.0
mccabe==0.6.1
multidict==4.7.5
mypy==0.770
mypy-extensions==0.4.3
numpy==1.18.2
parso==0.6.2
pathspec==0.7.0
prompt-toolkit==3.0.5
ptpython==3.0.1
pycodestyle==2.5.0
pyflakes==2.1.1
PyGithub==1.47
Pygments==2.6.1
PyJWT==1.7.1
regex==2020.2.20
requests==2.23.0
reverse-geocoder==1.5.1
scipy==1.4.1
sentry-sdk==0.14.3
slots==1.3
SQLAlchemy==1.3.15
toml==0.10.0
typed-ast==1.4.1
typing-extensions==3.7.4.2
unittest-xml-reporting==3.0.2
urllib3==1.25.8
wcwidth==0.1.9
websockets==8.1
wrapt==1.12.1
yarl==1.4.2
```

**Comment by untitaker** [comment]
do you perhaps use a HTTP proxy of some sort? either configured via environment variables or explicitly

**Comment by RDIL** [comment]
cc @gpjt since this is on PA

**Comment by untitaker** [comment]
@RDIL hi, did you find anything out?

**Comment by RDIL** [comment]
I thought about what you said and realized I don't think its worth investigating.

**Comment by untitaker** [comment]
okay, do you have an estimated failure rate of some sort? like, how many events do you get fully saved into sentry and how often do you see this urllib3 error

**Comment by RDIL** [comment]
It usually happens on ~ 1/4 errors, but it makes it to sentry eventually

**Comment by gpjt** [comment]
In response to the question about the proxy earlier -- free accounts on PythonAnywhere need to go via a Squid proxy server, but the proxy settings are in the `http_proxy` and `https_proxy` environment variables, which I *think* `urllib3` will pick up...?  `requests` certainly does.

However, the account whose username is in @RDIL's stacktrace above is a paid account, which has direct unproxied Internet access, so that won't matter in this case.  The packets that the code is generating are just being sent out to the network unmodified.  Maybe it could be some kind of rate-limiting at sentry.io, or something like that?

**Comment by untitaker** [comment]
Our rate limiting is generally supposed to return proper 429 HTTP
responses, not just drop the TCP connection. We have load balancer rate
limits but you would have to send 100/s from a single IP and even there you
should get a 429

**Comment by timfeirg** [comment]
our sentry stopped working 3 days ago, and was reporting this exact error on all events

**Comment by kntiwary** [comment]
Did it get resolved
I am also getting similar error

gunicorn: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='3.6.46.217', port=9000): Max retries exceeded with url: /api/8/envelope/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7facc6f5dc88>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by yunzhihui** [comment]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sentry.iap.hh-d.cn', port=443): Max retries exceeded with url: /api/1/envelope/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc7ebf8f70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
06:55:42 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fdc7e7c8220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/transport.py", line 470, in send_envelope_wrapper
    self._send_envelope(envelope)
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/transport.py", line 387, in _send_envelope
    self._send_request(
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/sdk.py", line 268, in patched_send_request
    return _send_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/transport.py", line 230, in _send_request
    response = self._pool.request(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sentry.iap.hh-d.cn', port=443): Max retries exceeded with url: /api/1/envelope/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc7e7c8220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
06:56:59 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk

**Comment by banagale** [comment]
I was getting this error running `sentry-sdk` `1.25.1` but updated to `1.28.1` and it seemed to have corrected whatever was going wrong.

The error that made it into the log I was looking at was similar to:

```
2023-07-20 04:04:45,202 [raven-sentry] [WARNI] [urllib3.connectionpo]  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)'))': /api/[numbers]/envelope/
```
