### ISSUE TITLE
Python 3.8 threading is crashing: `TypeError: run() takes 1 positional argument`

### ISSUE THREAD

**Issue by yardensachs** [getsentry/sentry-python#688]
Hi all,

We upgraded to Python 3.8 and the new sentry, and we are seeing this error `TypeError: run() takes 1 positional argument but 3 were given`
We are also seeing it showing sometimes as `TypeError: run() takes 1 positional argument but 2 were given`

We are also using ddtrace.

```py
Exception ignored in thread started by: <bound method Thread._bootstrap of <Thread(AgentWriter, started daemon 140486491760384)>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 924, in _bootstrap_inner
Exception ignored in thread started by: <bound method Thread._bootstrap of <Thread(AgentWriter, started daemon 140486500153088)>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 924, in _bootstrap_inner
    del _limbo[self]
KeyError: <Thread(AgentWriter, started daemon 140486500153088)>
    del _limbo[self]
KeyError: <Thread(AgentWriter, started daemon 140486500153088)>
Exception in thread AgentWriter:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 69, in run
    reraise(*_capture_exception())
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 69, in run
    reraise(*_capture_exception())
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 69, in run
    reraise(*_capture_exception())
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
TypeError: run() takes 1 positional argument but 3 were given
```

Does anyone know why this issue is happening?

**Comment by untitaker** [comment]
Hey, I've never seen this issue before. Can you try downgrading Python to 3.7 or removing ddtrace to rule out inessential factors?

My first thoughts on that stacktrace are that somehow our instrumentation is initialized multiple times. The only way I can imagine this to be possible is if somehow our SDK was initialized while the process is forking.

**Comment by yardensachs** [comment]
@untitaker Thanks!
When using py 3.7, this is issue is not happning

**Comment by untitaker** [comment]
Have you tried removing datadog, and does this happen for other threads as well? I did not find anything suspicious in ddtrace that would explain this

**Comment by musterjunk** [comment]
https://stackoverflow.com/questions/37116721/python-typeerror-in-threading-function-takes-x-positional-argument-but-y-were

This stackoverflow issue solved it for me. add a comma after you argument if you only have one.

**Comment by untitaker** [comment]
@musterjunk I really don't think this issue is relevant

**Comment by untitaker** [comment]
@musterjunk I think this issue is unrelated

**Comment by shashwat-nf** [comment]
It happens for any unhandled exception. Without any message, I then have to guess the line throwing the exception. Is there any generic way to solve this?

**Comment by jcshott** [comment]
We're seeing this error in python 3.7.10 any updates on a fix?

**Comment by szokeasaurusrex** [comment]
@yardensachs @jcshott, I am struggling to reproduce this bug with the information you have provided so far. Can you please provide a specific code snippet which causes this error, and also provide the exact Python version and packages you have installed? And, can you please also verify whether you still observe the bug with the latest SDK version?

**Comment by yardensachs** [comment]
Yea we don't see this issue anymore FWIW
