### ISSUE TITLE
sentry_sdk.init does not accept "out" as DSN

### ISSUE THREAD

**Issue by mdaniel** [getsentry/sentry-python#699]
The sentry-java SDK accepts [`out://1?compression=false`](https://github.com/getsentry/sentry-java/blob/v1.7.30/sentry/src/main/java/io/sentry/DefaultSentryClientFactory.java#L357-L359) as a DSN, enabling one to use Sentry in a variety of setups where one would want to see the events, but without triggering the real notification

It appears `sentry_sdk` does not accept that:

```python
>>> import sentry_sdk
>>> sentry_sdk.init(dsn="out://1?compression=false")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/proj/venv/lib/python3.7/site-packages/sentry_sdk/hub.py", line 106, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "/proj/venv/lib/python3.7/site-packages/sentry_sdk/client.py", line 85, in __init__
    self._init_impl()
  File "/proj/venv/lib/python3.7/site-packages/sentry_sdk/client.py", line 116, in _init_impl
    self.transport = make_transport(self.options)
  File "/proj/venv/lib/python3.7/site-packages/sentry_sdk/transport.py", line 374, in make_transport
    return transport_cls(options)
  File "/proj/venv/lib/python3.7/site-packages/sentry_sdk/transport.py", line 126, in __init__
    Transport.__init__(self, options)
  File "/proj/venv/lib/python3.7/site-packages/sentry_sdk/transport.py", line 54, in __init__
    self.parsed_dsn = Dsn(options["dsn"])
  File "/proj/venv/lib/python3.7/site-packages/sentry_sdk/utils.py", line 114, in __init__
    raise BadDsn("Unsupported scheme %r" % parts.scheme)
sentry_sdk.utils.BadDsn: Unsupported scheme 'out'
```
---
sentry-sdk                0.14.4
Python 3.7.7

**Comment by untitaker** [comment]
sentry-java is probably the only SDK using `out://`. I would recommend `sentry_sdk.init(transport=print)`
