### ISSUE TITLE
Sentry Python SDK with proxy

### ISSUE THREAD

**Issue by simran66** [getsentry/sentry-python#741]
```
import sentry_sdk
 url="SENTRY_URL"
 proxy = 'http://localhost:8083'
 response = sentry_sdk.init(dsn=url, http_proxy=proxy)
```

I am getting Error: 
`ProxySchemeUnknown('Not supported proxy scheme None',)
`
What should proxy be replaced with to make it work?

**Comment by untitaker** [comment]
Where do you get that error? Can you post a full stacktrace?

**Comment by simran66** [comment]
@untitaker     ```
try:
        response = sentry_sdk.init(dsn=url, http_proxy=proxy)
        print("response")
        print response
    except Exception as e:
        print("exception"+repr(e))
```

The only exception trace I get here is:

`exceptionProxySchemeUnknown('Not supported proxy scheme None',)
`

**Comment by untitaker** [comment]
@simran66 if you don't catch the exception you should see a stacktrace. If not, please change your code like this:

```
    try:
        response = sentry_sdk.init(dsn=url, http_proxy=proxy)
        print("response")
        print response
    except Exception as e:
        import traceback
        traceback.print_exc()
```

**Comment by simran66** [comment]
@untitaker Thanks for your respoonse: Here's what I got:

`proxy is
localhost:8082
Traceback (most recent call last):
  File "tests/test_proxy.py", line 49, in test_sentry
    response = sentry_sdk.init(dsn=url, http_proxy=proxy)
  File "/Users/simran/Documents/dermsync/venv/lib/python2.7/site-packages/sentry_sdk/hub.py", line 106, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "/Users/simran/Documents/dermsync/venv/lib/python2.7/site-packages/sentry_sdk/client.py", line 85, in __init__
    self._init_impl()
  File "/Users/simran/Documents/dermsync/venv/lib/python2.7/site-packages/sentry_sdk/client.py", line 116, in _init_impl
    self.transport = make_transport(self.options)
  File "/Users/simran/Documents/dermsync/venv/lib/python2.7/site-packages/sentry_sdk/transport.py", line 374, in make_transport
    return transport_cls(options)
  File "/Users/simran/Documents/dermsync/venv/lib/python2.7/site-packages/sentry_sdk/transport.py", line 138, in __init__
    ca_certs=options["ca_certs"],
  File "/Users/simran/Documents/dermsync/venv/lib/python2.7/site-packages/sentry_sdk/transport.py", line 293, in _make_pool
    return urllib3.ProxyManager(proxy, **opts)
  File "/Users/simran/Documents/dermsync/venv/lib/python2.7/site-packages/urllib3/poolmanager.py", line 391, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
`

**Comment by simran66** [comment]
@untitaker do we know what the problem is?

**Comment by untitaker** [comment]
No, sorry. I cannot reproduce this. It might have to do with your concrete sentry DSN or some other aspect of your environment.

**Comment by untitaker** [comment]
Closing due to inactivity. Proxy support is generally implemented. I am not entire sure what the problem here is.

**Comment by przytular** [comment]
@untitaker try using dictionary instead of string

**Comment by untitaker** [comment]
It's not supposed to take a dictionary so I am not sure what you mean.
