### ISSUE TITLE
Error in sentry chalice integration

### ISSUE THREAD

**Issue by rafagan** [getsentry/sentry-python#828]
I have the following error in sentry-chalice:

```
Traceback (most recent call last):
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/chalice/cli/__init__.py", line 656, in main
    return cli(obj={})
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/chalice/cli/__init__.py", line 216, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 374, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 380, in _deploy
    self._validate_config(config)
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/chalice/deploy/deployer.py", line 406, in _validate_config
    validate_configuration(config)
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/chalice/deploy/validate.py", line 40, in validate_configuration
    routes = config.chalice_app.routes
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/chalice/config.py", line 141, in chalice_app
    app = v()
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/chalice/cli/factory.py", line 275, in load_chalice_app
    app = importlib.import_module('app')
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/wb_auth_business/app.py", line 9, in <module>
    sentry_sdk.init(
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/sentry_sdk/hub.py", line 106, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/sentry_sdk/client.py", line 86, in __init__
    self._init_impl()
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/sentry_sdk/client.py", line 128, in _init_impl
    self.integrations = setup_integrations(
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/__init__.py", line 119, in setup_integrations
    type(integration).setup_once()
  File "/Users/Projects/pessoal/WeBarber/wb-schedule-ws/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/chalice.py", line 95, in setup_once
    old_get_view_function_response = Chalice._get_view_function_response
AttributeError: type object 'Chalice' has no attribute '_get_view_function_response'
```

I've just imported and used the integration:

```
from sentry_sdk.integrations.chalice import ChaliceIntegration
sentry_sdk.init(
    dsn=os.environ['SENTRY_URL'],
    integrations=[ChaliceIntegration()]
)
```

Any help?

**Comment by matin** [comment]
It's an issue with `chalice>=1.20`. @Gleekzone is working on a fix now.

In the meantime, you could downgrade to Chalice 1.19

**Comment by untitaker** [comment]
Fixed by https://github.com/getsentry/sentry-python/pull/832

Thanks @matin @Gleekzone again!
