### ISSUE TITLE
Django 3.1 Exception in ASGI application with uvicorn

### ISSUE THREAD

**Issue by NightFury22** [getsentry/sentry-python#886]
All requests fail with this error, please help me find the problem. it appeared after I integrated **sentry-sdk** instead of **raven**. **Asyncio** is also used here. On my other project without **asyncio** everything is fine.

dependencies: 
async-timeout==3.0.1
Django==3.1.1
sentry-sdk==0.19.1

```py
# asgi.py

import sentry_sdk
import os

from sentry_sdk.integrations.django import DjangoIntegration

from django.core.asgi import get_asgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")

application = get_asgi_application()

# Sentry settings
SENTRY_DSN = os.environ.get('SENTRY_DSN')
ENV = os.environ.get('ENV', 'local')

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        environment=ENV,
    )
```

```
INFO:     127.0.0.1:46156 - "GET /health-check HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/vovalunev/venvs/no-api/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/vovalunev/venvs/no-api/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/vovalunev/venvs/no-api/lib/python3.8/site-packages/django/core/handlers/asgi.py", line 161, in __call__
    response = await self.get_response_async(request)
  File "/home/vovalunev/venvs/no-api/lib/python3.8/site-packages/django/core/handlers/base.py", line 149, in get_response_async
    response._resource_closers.append(request.close)
AttributeError: 'coroutine' object has no attribute '_resource_closers'
INFO:     127.0.0.1:46158 - "GET /favicon.ico HTTP/1.1" 500 Internal Server Error
/home/vovalunev/venvs/no-api/lib/python3.8/site-packages/uvicorn/main.py:382: RuntimeWarning: coroutine 'convert_exception_to_response.<locals>.inner' was never awaited
  loop.run_until_complete(self.serve(sockets=sockets))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by untitaker** [comment]
@NightFury22 why did you close it?

**Comment by NightFury22** [comment]
The problem was related to [asynchronous support middlewares in Django 3.1](https://docs.djangoproject.com/en/3.1/topics/http/middleware/#asynchronous-support). 

Sorry for wasting your time :(

**Comment by untitaker** [comment]
@NightFury22 are you sure this issue is still there if the sdk is disabled? I am willing to accept this as sdk bug if it only appears when using teh sdk

**Comment by NightFury22** [comment]
No, that was my problem. I upgraded to Django 3.1 and sentry-sdk and got this error because my middleware was not written correctly

before
```py
class UserInfoForSentryMiddleware(MiddlewareMixin):
    def process_request(self, request: HttpRequest):
        """
        Here all magic goes
        :return:
        """
        with configure_scope() as scope:
            user = getattr(request, 'user', None)
            if not user or not user.is_authenticated:
                scope.user = {
                    "id": hashlib.md5(
                        str(request.session.session_key).encode("utf8")
                    ).hexdigest()
                }
            else:
                scope.user = {
                    "id": str(user.id),
                }
        return self.get_response(request)
```

after
```py
@sync_and_async_middleware
def user_info_for_sentry_middleware(get_response):
    def configure_scope(request: HttpRequest) -> None:
        user = getattr(request, 'user', None)
        if not user or not user.is_authenticated:
            scope_user = {
                "id": hashlib.md5(
                    str(request.session.session_key).encode("utf8")
                ).hexdigest()
            }
        else:
            scope_user = {
                "id": str(user.id),
            }

        set_user(scope_user)

    if asyncio.iscoroutinefunction(get_response):
        async def middleware(request: HttpRequest) -> HttpResponse:
            configure_scope(request)
            response = await get_response(request)
            return response

    else:
        def middleware(request: HttpRequest) -> HttpResponse:
            configure_scope(request)
            response = get_response(request)
            return response

    return middleware
```
