### ISSUE TITLE
Crash in pure_eval

### ISSUE THREAD

**Issue by vmarkovtsev** [getsentry/sentry-python#893]
This happened while we were experiencing a DB outage:
```
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 443, in fetch
    return await self._execute(query, args, 0, timeout)
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1445, in _execute
    result, _ = await self.__execute(
  File "/server/athenian/api/db.py", line 191, in _asyncpg_execute
    result = await self._execute_original(query, args, limit, timeout, return_status)
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1454, in __execute
    return await self._do_execute(query, executor, timeout)
  File "/usr/local/lib/python3.8/dist-packages/asyncpg/connection.py", line 1476, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 196, in bind_execute
    return await waiter
asyncpg.exceptions.ConnectionDoesNotExistError: connection was closed in the middle of operation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/scope.py", line 353, in apply_to_event
    new_event = event_processor(event, hint)
  File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/integrations/pure_eval.py", line 79, in add_executing_info
    pure_eval_frame(tb.tb_frame) or sentry_frame["vars"]
  File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/integrations/pure_eval.py", line 128, in pure_eval_frame
    expressions.sort(key=closeness, reverse=True)
  File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/integrations/pure_eval.py", line 113, in closeness
    nodes_before_stmt = [
  File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/integrations/pure_eval.py", line 114, in <listcomp>
    node for node in nodes if node.first_token.startpos < stmt.last_token.endpos
AttributeError: 'Name' object has no attribute 'first_token'
```

**Comment by vmarkovtsev** [comment]
cc @alexmojaki

**Comment by untitaker** [comment]
I'll defer to @alexmojaki. Also let's wrap all of this in `with capture_internal_exceptions` in a way where the SDK may fail to attach locals, but does not crash the app

**Comment by alexmojaki** [comment]
@untitaker I'm pretty confused about when to use `capture_internal_exceptions`. Other integrations seem to use it sparingly. All the pure_eval logic is reached via `@add_global_event_processor` and thus this code in scope.py:

```python
        for event_processor in chain(global_event_processors, self._event_processors):
            new_event = event
            with capture_internal_exceptions():
                new_event = event_processor(event, hint)
```

so it seems like `capture_internal_exceptions` should already wrap the entire thing. How did the error cause a complete crash?

**Comment by untitaker** [comment]
On rereading teh stacktrace it perhaps didn't, you're completely right so ignore my comment.
