### ISSUE TITLE
Problem with Django + AWS Lambda integration

### ISSUE THREAD

**Issue by eplaut** [getsentry/sentry-python#959]
Hi,

I'm facing issues with sentry, where I believe is network related, in my deployment over AWS Lambda.

spec:
```
    python version 3.8.6
    zappa=0.52.0  # for deployment
    sentry-sdk==0.19.5
```
I saw latency from the lambda execution (2 seconds, and increased to 10 when I've changed the shutdown_timeout to 10 sec), but couldn't find anything with sentry's debug logs:

I've checked the tutorial example and got same results, here is part of the logs:

```
[1609084487408] [DEBUG] 2020-12-27T15:54:47.408Z 1f7ce3ea-bf58-473f-919e-9aa9e1ff5aed host found: [XXXXXX.execute-api.aws-region.amazonaws.com]
[1609084487408] [sentry] DEBUG: Sending envelope [envelope with 1 items (transaction)] project:11111 host:<sentry-url>
[1609084487408] [DEBUG] 2020-12-27T15:54:47.408Z 1f7ce3ea-bf58-473f-919e-9aa9e1ff5aed amazonaws found in host
[1609084487409] [sentry] DEBUG: [Tracing] Starting <http.server> transaction <generic WSGI request>
[1609084487409] [DEBUG] 2020-12-27T15:54:47.408Z 1f7ce3ea-bf58-473f-919e-9aa9e1ff5aed Sending envelope [envelope with 1 items (transaction)] project:11111 host:<sentry-url>
[1609084487409] [DEBUG] 2020-12-27T15:54:47.408Z 1f7ce3ea-bf58-473f-919e-9aa9e1ff5aed [Tracing] Starting <http.server> transaction <generic WSGI request>
[1609084487411] [DEBUG] 2020-12-27T15:54:47.409Z 1f7ce3ea-bf58-473f-919e-9aa9e1ff5aed Starting new HTTPS connection (1): <sentry-url>:443
[1609084487512] [ERROR] 2020-12-27T15:54:47.499Z 1f7ce3ea-bf58-473f-919e-9aa9e1ff5aed Internal Server Error: /test/sentry-debug/
Traceback (most recent call last):
  File "/var/task/django/core/handlers/exception.py", line 47, in inner
  response = get_response(request)
  File "/var/task/django/core/handlers/base.py", line 179, in _get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/task/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
  return callback(request, *args, **kwargs)
  File "/var/task/sentry_check/urls.py", line 20, in trigger_error
  division_by_zero = 1 / 0
ZeroDivisionError: division by zero
[1609084487512] Internal Server Error: /test/sentry-debug/
[1609084487512] Traceback (most recent call last):
[1609084487512] File "/var/task/django/core/handlers/exception.py", line 47, in inner
[1609084487512] response = get_response(request)
[1609084487512] File "/var/task/django/core/handlers/base.py", line 179, in _get_response
[1609084487512] response = wrapped_callback(request, *callback_args, **callback_kwargs)
[1609084487512] File "/var/task/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
[1609084487512] return callback(request, *args, **kwargs)
[1609084487512] File "/var/task/sentry_check/urls.py", line 20, in trigger_error
[1609084487512] division_by_zero = 1 / 0
[1609084487512] ZeroDivisionError: division by zero
[1609084487514] [INFO] 2020-12-27T15:54:47.513Z 1f7ce3ea-bf58-473f-919e-9aa9e1ff5aed 2.53.1.172 - - [27/Dec/2020:15:54:47 +0000] "GET /sentry-debug/ HTTP/1.1" 500 62667 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0" 0/105.78999999999999
[1609084488614] [DEBUG] 2020-12-27T15:54:48.614Z 30f00f5d-20ee-4afb-b2a4-efd3e07e465e Zappa Event: {'time': '2020-12-27T15:54:33Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': 'some-id', 'region': 'aws-region', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:aws-region:some-id:rule/sentry-test-test-zappa-keep-warm-handler.keep_warm_callback'], 'id': '417b2377-7090-73f5-7b2f-e7e2d3483466', 'kwargs': {}}
[1609084488615] [DEBUG] 2020-12-27T15:54:48.614Z 30f00f5d-20ee-4afb-b2a4-efd3e07e465e Zappa Event: {}
```

On testing environment (`./mange.py runserver`) everything was fine, and the error got to sentry dashboard.

I've tried using zappa-sentry(==0.4.1), with success.

Any idea what can cause it?

**Comment by untitaker** [comment]
can you tell me when and where you initialize the Python SDK + what the actual problem is that you're encountering?

**Comment by eplaut** [comment]
Wrong configuration of lambda function (web access + vpc)
