### ISSUE TITLE
AttributeError: type object 'type' has no attribute 'setup_once'

### ISSUE THREAD

**Issue by Samll-Kosmos** [getsentry/sentry-python#986]
Hi, I'm having trouble integrating sentry with my application. I'm using flask and Gunicorn with the sentry flaks integration. These are the package versions:

sentry-sdk==0.19.5
gunicorn==20.0.4
flask==1.1.2

Im using Python 3.6.9. I installed sentry with: `pip install --upgrade 'sentry-sdk[flask]'`

Output error:

```
Traceback (most recent call last):
  File ".venv-3.6/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File ".venv-3.6/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File ".venv-3.6/lib/python3.6/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File ".venv-3.6/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File ".venv-3.6/lib/python3.6/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File ".venv-3.6/lib/python3.6/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File ".venv-3.6/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File ".venv-3.6/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File ".venv-3.6/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File ".venv-3.6/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "wsgi.py", line 4, in <module>
    app = create_app()
  File "ws/__init__.py", line 44, in create_app
    traces_sample_rate=1.0,
  File ".venv-3.6/lib/python3.6/site-packages/sentry_sdk/hub.py", line 105, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File ".venv-3.6/lib/python3.6/site-packages/sentry_sdk/client.py", line 88, in __init__
    self._init_impl()
  File ".venv-3.6/lib/python3.6/site-packages/sentry_sdk/client.py", line 134, in _init_impl
    "auto_enabling_integrations"
  File ".venv-3.6/lib/python3.6/site-packages/sentry_sdk/integrations/__init__.py", line 120, in setup_integrations
    type(integration).setup_once()
AttributeError: type object 'type' has no attribute 'setup_once'
```

Initiating sentry:

```python
sentry_sdk.init(
    dsn=SENTRY_DNS,
    integrations=[FlaskIntegration],
    traces_sample_rate=1.0)
```

Thank you!

**Comment by untitaker** [comment]
Replace `FlaskIntegration` with `FlaskIntegration()`
